import type { DesktopApi } from "../desktop";
import { DemoLifecycleApi } from "./api-lifecycle";

class DemoApi extends DemoLifecycleApi implements DesktopApi {}

export function createDemoApi(): DesktopApi {
  const implementation = new DemoApi();
  return {
    mode: implementation.mode,
    getWorkflow: implementation.getWorkflow.bind(implementation),
    openWorkspace: implementation.openWorkspace.bind(implementation),
    createWorkspace: implementation.createWorkspace.bind(implementation),
    restoreWorkspace: implementation.restoreWorkspace.bind(implementation),
    scanWorkspace: implementation.scanWorkspace.bind(implementation),
    getProfile: implementation.getProfile.bind(implementation),
    updateProfile: implementation.updateProfile.bind(implementation),
    getTimestampSettings: implementation.getTimestampSettings.bind(implementation),
    updateTimestampSettings: implementation.updateTimestampSettings.bind(implementation),
    updateTimestampSecret: implementation.updateTimestampSecret.bind(implementation),
    testTimestampProvider: implementation.testTimestampProvider.bind(implementation),
    getAudioScreeningSettings: implementation.getAudioScreeningSettings.bind(implementation),
    updateAudioScreeningSettings: implementation.updateAudioScreeningSettings.bind(implementation),
    updateAudioScreeningSecret: implementation.updateAudioScreeningSecret.bind(implementation),
    testAudioScreeningProvider: implementation.testAudioScreeningProvider.bind(implementation),
    listGlobalEvidence: implementation.listGlobalEvidence.bind(implementation),
    importGlobalEvidence: implementation.importGlobalEvidence.bind(implementation),
    importGlobalTermsEvidence: implementation.importGlobalTermsEvidence.bind(implementation),
    updateGlobalTermsEvidenceMetadata: implementation.updateGlobalTermsEvidenceMetadata.bind(implementation),
    removeGlobalEvidence: implementation.removeGlobalEvidence.bind(implementation),
    attachGlobalEvidence: implementation.attachGlobalEvidence.bind(implementation),
    listTracks: implementation.listTracks.bind(implementation),
    listAlbums: implementation.listAlbums.bind(implementation),
    createAlbum: implementation.createAlbum.bind(implementation),
    createTrack: implementation.createTrack.bind(implementation),
    scanImportFolder: implementation.scanImportFolder.bind(implementation),
    executeFolderImport: implementation.executeFolderImport.bind(implementation),
    loadTrack: implementation.loadTrack.bind(implementation),
    loadTrackCover: implementation.loadTrackCover.bind(implementation),
    updateTrackLibrary: implementation.updateTrackLibrary.bind(implementation),
    renameAlbum: implementation.renameAlbum.bind(implementation),
    updateTrack: implementation.updateTrack.bind(implementation),
    adoptLegacyProfile: implementation.adoptLegacyProfile.bind(implementation),
    addDeviation: implementation.addDeviation.bind(implementation),
    resolveDeviation: implementation.resolveDeviation.bind(implementation),
    removeDeviation: implementation.removeDeviation.bind(implementation),
    setStepStatus: implementation.setStepStatus.bind(implementation),
    importEvidence: implementation.importEvidence.bind(implementation),
    removeEvidence: implementation.removeEvidence.bind(implementation),
    previewEvidence: implementation.previewEvidence.bind(implementation),
    verifyEvidence: implementation.verifyEvidence.bind(implementation),
    previewDocumentGeneration: implementation.previewDocumentGeneration.bind(implementation),
    generateDocuments: implementation.generateDocuments.bind(implementation),
    generateArtworkDisclosure: implementation.generateArtworkDisclosure.bind(implementation),
    calculateHashes: implementation.calculateHashes.bind(implementation),
    verifyHashes: implementation.verifyHashes.bind(implementation),
    runLocalAudioScreening: implementation.runLocalAudioScreening.bind(implementation),
    runExternalAudioScreening: implementation.runExternalAudioScreening.bind(implementation),
    validateTrack: implementation.validateTrack.bind(implementation),
    finalizeTrack: implementation.finalizeTrack.bind(implementation),
    attachExternalTimestamp: implementation.attachExternalTimestamp.bind(implementation),
    invalidateCertificate: implementation.invalidateCertificate.bind(implementation),
    createRevision: implementation.createRevision.bind(implementation),
    reEvaluateTrack: implementation.reEvaluateTrack.bind(implementation)
  };
}
