use super::*;

#[test]
fn generates_parseable_pdf_with_identity_full_hash_and_german_text() {
    let bytes = Fixture::new(1).generate();
    write_review_pdf("case-b-no-artwork-no-acrcloud.pdf", &bytes);
    assert!(bytes.starts_with(b"%PDF-"));
    validate_pdf_bytes(&bytes).expect("valid generated bytes");

    let (document, text) = parse_text(&bytes);
    assert!(!document.pages.is_empty());
    assert!(text.contains("Größe & Präzision"), "extracted text: {text}");
    assert!(text.contains("Künstlerin Änne Öster"));
    assert!(text.contains(CERTIFICATE_ID));
    assert!(text.contains(DIGEST_A));
    assert!(text.contains(&format!("{value:064x}", value = 1)));
    assert!(text.contains("Kein AI-Artwork dokumentiert"));
}

#[test]
fn summary_page_exposes_the_decision_facts_and_missing_artwork_fallback() {
    let bytes = Fixture::new(1).generate();
    let (document, _) = parse_text(&bytes);
    let pages = document.extract_text();
    let summary = pages.first().expect("summary page").join("\n");
    for expected in [
        DOCUMENT_TITLE,
        "Größe & Präzision",
        "Künstlerin Änne Öster",
        CERTIFICATE_ID,
        "2026-01-04T12:34:56Z",
        "DOCUMENTATION COMPLETE",
        "Blocking deviations",
        "Artwork preview not available",
        "not a rights clearance or legal approval",
    ] {
        assert!(summary.contains(expected), "summary omitted {expected}");
    }
    let summary_compact = normalized_text(&summary);
    let blocking_start = summary_compact
        .find("Blocking deviations")
        .expect("blocking-deviation summary label");
    let blocking_end = (blocking_start + 32).min(summary_compact.len());
    assert!(summary_compact[blocking_start..blocking_end].contains('0'));
    assert!(pages.iter().all(|page| {
        let text = page.join("\n");
        !text.trim().is_empty() && text.contains(CERTIFICATE_ID)
    }));
}

#[test]
fn clustered_timeline_callouts_use_separate_lanes_without_moving_ticks() {
    assert_eq!(timeline_label_lanes(&[20.0, 20.4, 20.8]), vec![0, 1, 2]);
    assert_eq!(timeline_label_lanes(&[20.0, 70.0, 120.0]), vec![0, 0, 0]);
    assert_eq!(timeline_label_lanes(&[120.0, 20.0, 20.4]), vec![0, 0, 1]);
}

#[test]
fn maximum_length_identity_values_are_bounded_in_summary_and_running_headers() {
    let mut fixture = Fixture::new(1);
    fixture.track.fields.title = "T".repeat(200);
    fixture.profile.artist_name = "A".repeat(500);
    fixture.track.fields.suno_model = "M".repeat(200);
    fixture.track.fields.suno_plan_at_generation = "P".repeat(200);

    let bytes = fixture.generate();
    validate_pdfa_2b_bytes(&bytes).expect("bounded long-value PDF/A");
    let (_, text) = parse_text(&bytes);
    let compact = text
        .chars()
        .filter(|character| !character.is_whitespace())
        .collect::<String>();
    assert!(text.contains('…'), "overview values should show truncation");
    assert!(compact.contains(&"T".repeat(200)));
    assert!(compact.contains(&"A".repeat(500)));

    let clipped = ellipsize_text_to_width(&"W".repeat(500), 36.0, 5.5, BuiltinFont::HelveticaBold);
    assert!(measure_text_width_mm(&clipped, 5.5, BuiltinFont::HelveticaBold) <= 36.0);
    let lines = bounded_wrapped_lines(&"W".repeat(500), 112.0, 15.0, BuiltinFont::HelveticaBold, 2);
    assert_eq!(lines.len(), 2);
    assert!(lines
        .iter()
        .all(|line| { measure_text_width_mm(line, 15.0, BuiltinFont::HelveticaBold) <= 112.0 }));
}

#[test]
fn artwork_previews_are_bounded_deduplicated_pdfa_safe_and_non_mutating() {
    let directory = tempfile::tempdir().expect("temporary artwork root");
    let artwork_directory = directory.path().join("05_ARTWORK");
    std::fs::create_dir_all(&artwork_directory).expect("artwork directory");
    let final_path = artwork_directory.join("FINAL.png");
    let human_path = artwork_directory.join("HUMAN.png");
    let image = image::RgbaImage::from_fn(1_200, 800, |x, y| {
        image::Rgba([
            (x % 251) as u8,
            (y % 239) as u8,
            ((x + y) % 233) as u8,
            if (x + y) % 7 == 0 { 160 } else { 255 },
        ])
    });
    image.save(&final_path).expect("write artwork fixture");
    std::fs::copy(&final_path, &human_path).expect("copy byte-identical artwork fixture");
    let original_final = std::fs::read(&final_path).expect("read final artwork");
    let original_human = std::fs::read(&human_path).expect("read human artwork");
    assert_eq!(original_final, original_human);
    let digest = crate::security::sha256_bytes(&original_final);

    let mut fixture = Fixture::new(1);
    let mut final_artwork = evidence_item(900);
    final_artwork.role = EvidenceRole::FinalArtwork;
    final_artwork.file_name = "FINAL.png".into();
    final_artwork.relative_path = "05_ARTWORK/FINAL.png".into();
    final_artwork.sha256 = Some(digest.clone());
    final_artwork.size_bytes = original_final.len() as u64;
    let mut human_artwork = evidence_item(901);
    human_artwork.role = EvidenceRole::HumanEditedArtwork;
    human_artwork.file_name = "HUMAN.png".into();
    human_artwork.relative_path = "05_ARTWORK/HUMAN.png".into();
    human_artwork.sha256 = Some(digest.clone());
    human_artwork.size_bytes = original_human.len() as u64;
    fixture.evidence.extend([final_artwork, human_artwork]);
    fixture
        .evidence
        .sort_by(|left, right| left.relative_path.cmp(&right.relative_path));
    let evidence_refs = fixture.evidence.iter().collect::<Vec<_>>();
    fixture.artwork_previews = prepare_artwork_previews(directory.path(), &evidence_refs);

    assert_eq!(fixture.artwork_previews.len(), 2);
    assert!(fixture
        .artwork_previews
        .iter()
        .all(|preview| preview.width_pixels == 640 && preview.height_pixels < 640));
    assert_eq!(
        fixture.artwork_previews[0].resource_id,
        fixture.artwork_previews[1].resource_id
    );

    let bytes = fixture.generate();
    write_review_pdf("case-a-artwork.pdf", &bytes);
    assert!(
        bytes.len() < 6 * 1024 * 1024,
        "bounded preview PDF grew unexpectedly"
    );
    validate_pdfa_2b_bytes(&bytes).expect("artwork certificate remains PDF/A-2b");
    assert_eq!(
        std::fs::read(&final_path).expect("reread final"),
        original_final
    );
    assert_eq!(
        std::fs::read(&human_path).expect("reread human"),
        original_human
    );
    assert_eq!(
        crate::security::sha256_file(&final_path).expect("final digest"),
        digest
    );

    assert_artwork_archive(&bytes);
}

fn assert_artwork_archive(bytes: &[u8]) {
    let archive = LoDocument::load_mem(bytes).expect("parse artwork certificate");
    let image_streams = archive
        .objects
        .values()
        .filter_map(|object| object.as_stream().ok())
        .filter(|stream| {
            stream.dict.get(b"Subtype").and_then(LoObject::as_name).ok() == Some(b"Image")
        })
        .collect::<Vec<_>>();
    assert_eq!(
        image_streams.len(),
        1,
        "identical artwork must be embedded once"
    );
    let image_stream = image_streams[0];
    assert!(!image_stream
        .dict
        .get(b"Interpolate")
        .and_then(LoObject::as_bool)
        .expect("image interpolation flag"));
    assert_eq!(
        image_stream
            .dict
            .get(b"ColorSpace")
            .and_then(LoObject::as_name)
            .expect("image color space"),
        b"DeviceCMYK"
    );
    assert!(!image_stream.dict.has(b"SMask"));
    assert!(!image_stream.dict.has(b"Mask"));

    let page_width_pt = PAGE_WIDTH_MM * 72.0 / 25.4;
    let page_height_pt = PAGE_HEIGHT_MM * 72.0 / 25.4;
    let mut placements = 0;
    for page_id in archive.get_pages().values() {
        let bytes = archive
            .get_page_content_with_limit(*page_id, PDF_PAGE_CONTENT_MAX_DECOMPRESSED_BYTES)
            .expect("bounded page content");
        let content = LoContent::decode(&bytes).expect("page operators");
        let mut matrix = [1.0_f32, 0.0, 0.0, 1.0, 0.0, 0.0];
        let mut stack = Vec::new();
        for operation in content.operations {
            match operation.operator.as_str() {
                "q" => stack.push(matrix),
                "Q" => matrix = stack.pop().unwrap_or([1.0, 0.0, 0.0, 1.0, 0.0, 0.0]),
                "cm" if operation.operands.len() == 6 => {
                    let values = operation
                        .operands
                        .iter()
                        .map(LoObject::as_float)
                        .collect::<std::result::Result<Vec<_>, _>>()
                        .expect("image placement matrix");
                    matrix = printpdf::CurTransMat::combine_matrix(
                        matrix,
                        [
                            values[0], values[1], values[2], values[3], values[4], values[5],
                        ],
                    );
                }
                "Do" => {
                    placements += 1;
                    let [a, b, c, d, e, f] = matrix;
                    let corners = [
                        (e, f),
                        (a + e, b + f),
                        (c + e, d + f),
                        (a + c + e, b + d + f),
                    ];
                    for (x, y) in corners {
                        assert!(x >= -0.02 && y >= -0.02);
                        assert!(x <= page_width_pt + 0.02);
                        assert!(y <= page_height_pt + 0.02);
                    }
                }
                _ => {}
            }
        }
    }
    assert!(
        placements >= 3,
        "summary and process artwork placements expected, found {placements}"
    );
    let (parsed, _) = parse_text(bytes);
    let pages = parsed.extract_text();
    assert!(pages[0].join("\n").contains("Final artwork preview"));
    assert!(pages[0].join("\n").contains("FINAL.png"));
}

#[test]
fn artwork_preview_uses_only_a_unique_hash_verified_case_fallback() {
    let directory = tempfile::tempdir().expect("temporary artwork root");
    let artwork_directory = directory.path().join("05_ARTWORK");
    std::fs::create_dir_all(&artwork_directory).expect("artwork directory");
    let actual_path = artwork_directory.join("GRAVITY_FINAL.png");
    image::RgbaImage::from_pixel(32, 32, image::Rgba([10, 20, 30, 255]))
        .save(&actual_path)
        .expect("write artwork fixture");
    let source = std::fs::read(&actual_path).expect("read artwork fixture");
    let mut item = evidence_item(902);
    item.role = EvidenceRole::FinalArtwork;
    item.file_name = "Gravaty_FINAL.png".into();
    item.relative_path = "05_ARTWORK/Gravaty_FINAL.png".into();
    item.size_bytes = source.len() as u64;
    item.sha256 = Some(crate::security::sha256_bytes(&source));
    let previews = prepare_artwork_previews(directory.path(), &[&item]);
    assert_eq!(previews.len(), 1);
    assert_eq!(previews[0].relative_path, item.relative_path);

    std::fs::copy(&actual_path, artwork_directory.join("SECOND_COPY.png"))
        .expect("second matching file");
    assert!(prepare_artwork_previews(directory.path(), &[&item]).is_empty());
}

#[test]
fn every_certificate_page_is_unrotated_a4_and_bookmarks_target_real_pages() {
    let bytes = Fixture::new(8).generate();
    let archive = LoDocument::load_mem(&bytes).expect("parse certificate");
    validate_a4_page_boxes(&archive).expect("all page boxes are A4");
    let (document, text) = parse_text(&bytes);
    assert!(text.contains("Contents"));
    assert!(text.contains("Summary"));
    assert!(text.contains("Track identity"));
    assert!(text.contains("Technical Appendix"));
    assert!(!document.bookmarks.map.is_empty());
    for bookmark in document.bookmarks.map.values() {
        assert!(
            (1..=document.pages.len()).contains(&bookmark.page),
            "invalid bookmark target for {}",
            bookmark.name
        );
    }
    assert!(document
        .bookmarks
        .map
        .values()
        .any(|bookmark| bookmark.name == "Summary" && bookmark.page == 1));
}

#[test]
fn generated_certificate_has_deterministic_pdfa_2b_archive_structure() {
    let bytes = Fixture::new(2).generate();
    validate_pdfa_2b_bytes(&bytes).expect("strict PDF/A-2b structure");

    let archive = LoDocument::load_mem(&bytes).expect("parse archive PDF");
    assert_eq!(archive.version, "1.7");
    let xmp = pdf_metadata_bytes(&archive)
        .expect("read XMP")
        .expect("embedded XMP");
    let xmp = std::str::from_utf8(&xmp).expect("UTF-8 XMP");
    assert!(xmp.contains("<pdfaid:part>2</pdfaid:part>"));
    assert!(xmp.contains("<pdfaid:conformance>B</pdfaid:conformance>"));
    assert!(xmp.contains("<xmp:CreateDate>2026-01-04T12:34:56Z</xmp:CreateDate>"));
    assert!(xmp.contains("<dc:language><rdf:Bag><rdf:li>en-US</rdf:li>"));

    let metadata = certificate_pdf_archive_metadata();
    assert_eq!(metadata.archive_format, "PDF/A-2b");
    assert_eq!(metadata.font_embedding, "full");
    assert_eq!(metadata.embedded_fonts.len(), 4);
    assert_eq!(metadata.embedded_font_sha256.len(), 4);
    assert_eq!(metadata.font_version, "DejaVu 2.37");
    assert_eq!(metadata.font_license, "DejaVu Fonts License");
    assert_eq!(metadata.output_intent, CERTIFICATE_PDF_OUTPUT_INTENT);
    assert_eq!(bytes, Fixture::new(2).generate());
}

#[test]
fn german_and_english_renditions_have_distinct_deterministic_identifiers() {
    fn xmp_uuid<'a>(xmp: &'a str, element: &str) -> &'a str {
        let prefix = format!("<{element}>uuid:");
        let suffix = format!("</{element}>");
        let start = xmp.find(&prefix).expect("XMP UUID element") + prefix.len();
        let end = start
            + xmp[start..]
                .find(&suffix)
                .expect("XMP UUID closing element");
        &xmp[start..end]
    }

    fn archive_identifiers(bytes: &[u8]) -> (String, String, Vec<Vec<u8>>) {
        let archive = LoDocument::load_mem(bytes).expect("parse archive PDF");
        let xmp = pdf_metadata_bytes(&archive)
            .expect("read XMP")
            .expect("embedded XMP");
        let xmp = std::str::from_utf8(&xmp).expect("UTF-8 XMP");
        let document_id = xmp_uuid(xmp, "xmpMM:DocumentID").to_owned();
        let instance_id = xmp_uuid(xmp, "xmpMM:InstanceID").to_owned();
        let trailer_ids = archive
            .trailer
            .get(b"ID")
            .and_then(LoObject::as_array)
            .expect("trailer ID array")
            .iter()
            .map(|value| value.as_str().expect("trailer ID string").to_vec())
            .collect();
        (document_id, instance_id, trailer_ids)
    }

    fn expected_trailer_ids(rendition_seed: &str) -> Vec<Vec<u8>> {
        let digest = crate::security::sha256_bytes(rendition_seed.as_bytes());
        vec![
            digest.as_bytes()[..32].to_vec(),
            digest.as_bytes()[32..].to_vec(),
        ]
    }

    let mut english = Fixture::new(1);
    english.render_options = CertificateRenderOptions {
        language: CertificateLanguage::En,
        bilingual: false,
    };
    let mut german = Fixture::new(1);
    german.render_options = CertificateRenderOptions {
        language: CertificateLanguage::De,
        bilingual: false,
    };

    let english_ids = archive_identifiers(&english.generate());
    let german_ids = archive_identifiers(&german.generate());
    assert_eq!(
        english_ids.0,
        deterministic_uuid(&format!("{CERTIFICATE_ID}:en-US"), "document")
    );
    assert_eq!(
        english_ids.1,
        deterministic_uuid(&format!("{CERTIFICATE_ID}:en-US"), "instance")
    );
    assert_eq!(
        german_ids.0,
        deterministic_uuid(&format!("{CERTIFICATE_ID}:de-DE"), "document")
    );
    assert_eq!(
        german_ids.1,
        deterministic_uuid(&format!("{CERTIFICATE_ID}:de-DE"), "instance")
    );
    assert_eq!(
        english_ids.2,
        expected_trailer_ids(&format!("{CERTIFICATE_ID}:en-US"))
    );
    assert_eq!(
        german_ids.2,
        expected_trailer_ids(&format!("{CERTIFICATE_ID}:de-DE"))
    );
    assert_ne!(english_ids.0, german_ids.0);
    assert_ne!(english_ids.1, german_ids.1);
    assert_ne!(english_ids.2, german_ids.2);
}

#[test]
fn strict_archive_validation_rejects_removed_pdfa_xmp() {
    let bytes = Fixture::new(1).generate();
    let mut archive = LoDocument::load_mem(&bytes).expect("parse archive PDF");
    let root_id = archive
        .trailer
        .get(b"Root")
        .and_then(LoObject::as_reference)
        .expect("catalog reference");
    archive
        .get_dictionary_mut(root_id)
        .expect("catalog")
        .remove(b"Metadata");
    let mut tampered = Vec::new();
    archive
        .save_to(&mut tampered)
        .expect("serialize tampered PDF");

    let error = validate_pdfa_2b_bytes(&tampered).expect_err("missing XMP is rejected");
    assert!(error.to_string().contains("no XMP metadata"));
}

#[test]
fn historical_non_pdfa_pdf_remains_accepted_by_public_validator() {
    let mut historical = PdfDocument::new("Historical certificate");
    historical.with_pages(vec![PdfPage::new(
        Mm(210.0),
        Mm(297.0),
        vec![
            Op::StartTextSection,
            Op::SetFont {
                font: PdfFontHandle::Builtin(BuiltinFont::Helvetica),
                size: Pt(10.0),
            },
            Op::ShowText {
                items: vec![TextItem::Text("Historical certificate".into())],
            },
            Op::EndTextSection,
        ],
    )]);
    let mut warnings = Vec::new();
    let bytes = historical.save(&PdfSaveOptions::default(), &mut warnings);
    assert!(!pdf_claims_pdfa(&bytes).expect("inspect historical PDF"));
    validate_pdf_bytes(&bytes).expect("historical parseable PDF remains supported");
}

#[test]
fn renders_german_and_bilingual_certificate_labels() {
    let mut german = Fixture::new(1);
    german.render_options = CertificateRenderOptions {
        language: crate::model::CertificateLanguage::De,
        bilingual: false,
    };
    let (_, german_text) = parse_text(&german.generate());
    assert!(german_text.contains("SunoDM – Technisches Dokumentations- und Evidenzzertifikat"));
    assert!(german_text.contains("C. Finale Suno-Erzeugung"));
    assert!(german_text.contains("ID der finalen Erzeugung"));
    assert!(normalized_text(&german_text)
        .contains("Dieses technische Zertifikat bestätigt die erfassten Eingaben"));
    assert!(!german_text.contains("C. Final Suno Generation"));

    let mut bilingual = Fixture::new(1);
    bilingual.render_options = CertificateRenderOptions {
        language: crate::model::CertificateLanguage::De,
        bilingual: true,
    };
    let (_, bilingual_text) = parse_text(&bilingual.generate());
    let bilingual_normalized = normalized_text(&bilingual_text);
    assert!(bilingual_normalized.contains("C. Finale Suno-Erzeugung / C. Final Suno Generation"));
    // In the bilingual table the value can be interleaved between wrapped
    // label lines by text extraction; both localized labels must survive.
    assert!(
        bilingual_normalized.contains("ID der finalen Erzeugung [Vom Nutzer bestätigte Angabe]")
    );
    let id_label_start = bilingual_normalized
        .find("ID der finalen Erzeugung")
        .expect("German final-generation ID label");
    let id_label_end = (id_label_start + 280).min(bilingual_normalized.len());
    let id_label_region = &bilingual_normalized[id_label_start..id_label_end];
    assert!(id_label_region.contains("Final generation"));
    assert!(id_label_region.contains("User-confirmed fact"));
    assert!(id_label_region.contains("generation-fixture"));
}

#[test]
fn renders_localized_audio_screening_without_raw_values() {
    let mut german = Fixture::new(1);
    german.track.audio_screening.local.status = AudioScreeningStatus::FingerprintGenerated;
    german.track.audio_screening.local.fingerprint = "RAW_FINGERPRINT_MUST_NOT_RENDER".into();
    german.track.audio_screening.local.message = "LOCAL_MESSAGE_MUST_NOT_RENDER".into();
    german.track.audio_screening.local.artifact_relative_path =
        "03_DOCUMENTATION/AUDIO_SCREENING/LOCAL_FINGERPRINT.json".into();
    german.track.audio_screening.local.artifact_sha256 = DIGEST_A.into();
    german.track.audio_screening.external.status = AudioScreeningStatus::MatchDetected;
    german.track.audio_screening.external.configured_at_snapshot = Some(false);
    german.track.audio_screening.external.message = "EXTERNAL_MESSAGE_MUST_NOT_RENDER".into();
    german
        .track
        .audio_screening
        .external
        .matches
        .extend((0..6).map(|index| crate::model::AudioScreeningMatch {
            title: format!("Provider title {index}"),
            artists: vec![format!("Provider artist {index}")],
            ..Default::default()
        }));
    german.render_options = CertificateRenderOptions {
        language: crate::model::CertificateLanguage::De,
        bilingual: false,
    };

    let (_, german_text) = parse_text(&german.generate());
    assert!(german_text.contains("K.2 Audio-Screening vor Veröffentlichung"));
    assert!(german_text.contains("Status des lokalen Screenings"));
    assert!(german_text.contains("Provider title 0"));
    assert!(german_text.contains("Provider title 4"));
    assert!(german_text.contains("Provider title 5"));
    assert!(german_text.contains(
        "Audio-Screening-Ergebnisse sind ausschließlich technische Vergleichsdatensätze."
    ));
    for forbidden in [
        "RAW_FINGERPRINT_MUST_NOT_RENDER",
        "LOCAL_MESSAGE_MUST_NOT_RENDER",
        "EXTERNAL_MESSAGE_MUST_NOT_RENDER",
    ] {
        assert!(!german_text.contains(forbidden), "PDF leaked {forbidden}");
    }

    german.render_options = CertificateRenderOptions {
        language: crate::model::CertificateLanguage::De,
        bilingual: true,
    };
    let (_, bilingual_text) = parse_text(&german.generate());
    let bilingual_normalized = normalized_text(&bilingual_text);
    assert!(bilingual_normalized
        .contains("K.2 Audio-Screening vor Veröffentlichung / K.2 Pre-release audio screening"));
    assert!(bilingual_normalized.contains(
        "Audio-Screening-Ergebnisse sind ausschließlich technische Vergleichsdatensätze."
    ));
    assert!(bilingual_normalized
        .contains("Audio-screening results are technical comparison records only."));
}

#[test]
fn renders_multi_sample_screening_facts_for_english_and_german_k2() {
    let mut fixture = Fixture::new(1);
    let external = &mut fixture.track.audio_screening.external;
    external.screening_mode = AudioScreeningMode::MultiSample;
    external.status = AudioScreeningStatus::NoMatchDetected;
    external.provider_status = AudioScreeningProviderStatus::Ready;
    external.requested_intensity_percent = 25;
    external.dynamic_by_track_duration = true;
    external.reference_duration_seconds = Some(300);
    external.source_duration_milliseconds = Some(646_160);
    external.target_duration_milliseconds = 75_000;
    external.planned_request_count = 7;
    external.executed_request_count = 2;
    external.request_count = 2;
    external.unique_sample_count = 2;
    external.duplicate_sample_count = 0;
    external.overlapping_sample_count = 0;
    external.unique_sample_duration_milliseconds = 24_000;
    external.track_coverage_percent = (external.unique_sample_duration_milliseconds as f64 * 100.0)
        / external
            .source_duration_milliseconds
            .expect("fixture source duration") as f64;
    external.message = "RAW_EXTERNAL_MESSAGE_MUST_NOT_RENDER".into();
    external.response_relative_path =
        Some("03_DOCUMENTATION/AUDIO_SCREENING/ACRCLOUD_RESPONSE.json".into());
    external.response_sha256 = Some(DIGEST_A.into());
    external.samples = vec![
        crate::model::AudioScreeningSampleRecord {
            sequence: 1,
            offset_milliseconds: 30_000,
            end_offset_milliseconds: 42_000,
            duration_milliseconds: 12_000,
            status: AudioScreeningStatus::NoMatchDetected,
            message: "RAW_SAMPLE_MESSAGE_MUST_NOT_RENDER".into(),
            provider_status_code: Some(1001),
            provider_status_message: Some("No result".into()),
            provider_api_version: Some("1.0".into()),
            matches: Vec::new(),
            response_relative_path: Some(
                "03_DOCUMENTATION/AUDIO_SCREENING/ACRCLOUD_RESPONSE.json".into(),
            ),
            response_sha256: Some(DIGEST_A.into()),
        },
        crate::model::AudioScreeningSampleRecord {
            sequence: 2,
            offset_milliseconds: 95_000,
            end_offset_milliseconds: 107_000,
            duration_milliseconds: 12_000,
            status: AudioScreeningStatus::NoMatchDetected,
            message: "SECOND_RAW_SAMPLE_MESSAGE_MUST_NOT_RENDER".into(),
            provider_status_code: Some(1001),
            provider_status_message: Some("No result".into()),
            provider_api_version: Some("1.0".into()),
            matches: Vec::new(),
            response_relative_path: Some(
                "03_DOCUMENTATION/AUDIO_SCREENING/ACRCLOUD_RESPONSE.json".into(),
            ),
            response_sha256: Some(DIGEST_A.into()),
        },
    ];

    assert_multi_sample_rendering(&mut fixture);
}

fn assert_multi_sample_rendering(fixture: &mut Fixture) {
    let external = &fixture.track.audio_screening.external;
    let rows = multi_sample_pdf_rows(external);
    let row_value = |label: &str| {
        rows.iter()
            .find(|row| row.label.starts_with(label))
            .map(|row| row.value.as_str())
    };
    assert_eq!(row_value("Reference duration (seconds)"), Some("300"));
    assert_eq!(row_value("Duplicate samples"), Some("0"));
    assert_eq!(row_value("Overlapping samples"), Some("0"));
    let english_bytes = fixture.generate();
    write_review_pdf("case-a-acrcloud-en.pdf", &english_bytes);
    let (_, english_text) = parse_text(&english_bytes);
    let english = normalized_text(&english_text);
    for expected in [
        "External screening mode",
        "MULTI-SAMPLE",
        "Requested coverage",
        "25 %",
        "Planned requests",
        "Reference duration (seconds)",
        "300",
        "Executed requests",
        "Unique samples",
        "Duplicate samples",
        "Overlapping samples",
        "Unique sampled duration (ms)",
        "Track coverage (%)",
        "3.71",
        "10:46",
        "Overall result",
        "NO MATCH DETECTED",
        "ACRCloud: 1001",
        "No result",
        "API 1.0",
        "Appendix A — ACRCloud sample records",
        "Consolidated response archive: 2 ACRCloud sample responses",
        "ACRCLOUD_RESPONSE.json",
        "30000–42000 ms",
        "00:30.000 – 00:42.000",
        "95000–107000 ms",
        "Audio-screening results are technical comparison records only.",
    ] {
        assert!(english.contains(expected), "English PDF omitted {expected}");
    }

    fixture.render_options = CertificateRenderOptions {
        language: CertificateLanguage::De,
        bilingual: false,
    };
    let german_bytes = fixture.generate();
    write_review_pdf("case-a-acrcloud-de.pdf", &german_bytes);
    let (_, german_text) = parse_text(&german_bytes);
    let german = normalized_text(&german_text);
    for expected in [
        "K.2 Audio-Screening vor Veröffentlichung",
        "Modus des externen Screenings",
        "Angeforderte Abdeckung",
        "Geplante Anfragen",
        "Ausgeführte Anfragen",
        "Eindeutige Proben",
        "Doppelte Proben",
        "Überlappende Proben",
        "Referenzdauer (Sekunden)",
        "300",
        "3.71",
        "Anhang A — ACRCloud-Probendatensätze",
        "Konsolidiertes Antwortarchiv: 2 ACRCloud-Probenantworten",
        "30000–42000 ms",
        "95000–107000 ms",
        "ACRCloud: 1001",
        "No result",
        "API 1.0",
        "Gesamtergebnis",
        "MEHRFACH-PROBE",
        "Abdeckung",
    ] {
        assert!(german.contains(expected), "German PDF omitted {expected}");
    }
    assert!(
        !german.contains("Coverage"),
        "German PDF retained the English summary label Coverage"
    );
    assert!(german.contains("KEIN TREFFER ERKANNT"));
    assert!(
        !german.contains('…'),
        "German no-match summary must fit without visual truncation"
    );
    for forbidden in [
        "RAW_EXTERNAL_MESSAGE_MUST_NOT_RENDER",
        "RAW_SAMPLE_MESSAGE_MUST_NOT_RENDER",
        "SECOND_RAW_SAMPLE_MESSAGE_MUST_NOT_RENDER",
    ] {
        assert!(
            !english.contains(forbidden),
            "English PDF leaked {forbidden}"
        );
        assert!(!german.contains(forbidden), "German PDF leaked {forbidden}");
    }
}
