pub(super) const LABEL_REPLACEMENTS_C: &[(&str, &str)] = &[
    (
        "Code-audio post-processing",
        "Nachbearbeitung für codegeneriertes Audio",
    ),
    (
        "External audio provenance statement",
        "Herkunftsangabe zu externem Audio",
    ),
    ("External audio source", "Quelle des externen Audios"),
    (
        "Own audio provenance statement",
        "Herkunftsangabe zu eigenem Audio",
    ),
    ("Own audio source", "Quelle des eigenen Audios"),
    (
        "Third-party sample provenance statement",
        "Herkunftsangabe zu Samples Dritter",
    ),
    ("Third-party sample source", "Quelle der Samples Dritter"),
    (
        "Other code-audio post-processing note",
        "Sonstige Anmerkung zur Nachbearbeitung des codegenerierten Audios",
    ),
    (
        "Human editing performed",
        "Menschliche Bearbeitung durchgeführt",
    ),
    (
        "Confirmed human editing",
        "Bestätigte menschliche Bearbeitung",
    ),
    (
        "Desktop-PC editing after the Suno WAV",
        "Desktop-PC-Bearbeitung nach dem Suno-WAV",
    ),
    (
        "Confirmed desktop-PC editing",
        "Bestätigte Desktop-PC-Bearbeitung",
    ),
    (
        "Confirmed human artwork process",
        "Bestätigter menschlicher Artwork-Prozess",
    ),
    (
        "Human artwork process notes",
        "Anmerkungen zum menschlichen Artwork-Prozess",
    ),
    (
        "Confirmed human artwork modifications",
        "Bestätigte menschliche Artwork-Änderungen",
    ),
    (
        "Other human artwork change",
        "Sonstige menschliche Artwork-Änderung",
    ),
    (
        "Suno Instrumental Mode Selected",
        "Ausgewählter Suno-Instrumentalmodus",
    ),
    (
        "Generation Text Field Available",
        "Generierungstextfeld verfügbar",
    ),
    (
        "Generation Text Field Used",
        "Generierungstextfeld verwendet",
    ),
    ("Content Classification", "Inhaltsklassifizierung"),
    ("Vocal Lyrics Present", "Vocal Lyrics vorhanden"),
    (
        "Structure Instructions Present",
        "Strukturanweisungen vorhanden",
    ),
    ("Vocal Intent", "Vokale Intention"),
    (
        "Final Audio Contains Vocals",
        "Finaler Audioinhalt enthält Gesang",
    ),
    ("Instrumental track", "Instrumentaltrack"),
    ("Vocal lyrics present", "Vocal Lyrics vorhanden"),
    (
        "Structure instructions present",
        "Strukturanweisungen vorhanden",
    ),
    (
        "Exact Generation Text Field Content",
        "Exakter Text des Suno-Textfelds",
    ),
    ("Legacy source value", "Historischer Quellenwert"),
    ("Legacy text", "Historischer Text"),
    ("Classification", "Klassifizierung"),
    ("Generative AI used", "Generative KI verwendet"),
    ("AI system", "KI-System"),
    ("AI-assisted audio elements", "KI-assistierte Audioelemente"),
    ("AI-generated audio elements", "KI-generierte Audioelemente"),
    (
        "Real person voice intentionally imitated",
        "Stimme einer realen Person absichtlich imitiert",
    ),
    (
        "Real person's identity intentionally represented",
        "Identität einer realen Person absichtlich dargestellt",
    ),
    (
        "Real event represented as authentic recording",
        "Reales Ereignis als authentische Aufnahme dargestellt",
    ),
    (
        "Real location / institution / event presented as authentic AI recording",
        "Realer Ort / Institution / Ereignis als authentische KI-Aufnahme dargestellt",
    ),
    ("Disclosure applied", "Hinweis angewendet"),
    ("Disclosure locations", "Orte des Hinweises"),
    ("Disclosure text", "Hinweistext"),
    ("Disclosure reason / note", "Grund / Anmerkung zum Hinweis"),
    (
        "Deepfake-related indicator summary",
        "Zusammenfassung zu Deepfake-bezogenen Indikatoren",
    ),
    ("Suno style prompt", "Suno-Style-Prompt"),
    ("Artwork origin", "Herkunft des Artworks"),
    ("AI image service", "KI-Bilddienst"),
    ("Human artwork process", "Menschlicher Artwork-Prozess"),
    ("Human artwork changes", "Menschliche Artwork-Änderungen"),
    ("Depicts real person", "Reale Person dargestellt"),
    ("Real-person note", "Anmerkung zur realen Person"),
    ("Depicts real event", "Reales Ereignis dargestellt"),
    ("Real-event note", "Anmerkung zum realen Ereignis"),
    ("Trademark/logo note", "Anmerkung zu Marke/Logo"),
    ("Trademark/logo", "Marke/Logo"),
    ("Artwork disclosure applied", "Artwork-Hinweis angewendet"),
    (
        "Artwork disclosure deliberately not applied",
        "Artwork-Hinweis bewusst nicht angewendet",
    ),
    ("Artwork disclosure text", "Artwork-Hinweistext"),
    (
        "Human-edited/final artwork comparison",
        "Vergleich von menschlich bearbeitetem und finalem Artwork",
    ),
    ("Subscription evidence", "Abo-Evidence"),
    ("Terms document", "Dokument zu Nutzungsbedingungen"),
    ("Evidence ID", "Evidence-ID"),
    ("evidence ID", "Evidence-ID"),
    (" title", " Titel"),
    (" provider/source", " Anbieter/Quelle"),
    (" source URL", " Quell-URL"),
    (" retrieval date", " Abrufdatum"),
    (
        " applicable production period",
        " anwendbarer Produktionszeitraum",
    ),
    (" factual note", " sachliche Anmerkung"),
    (" path", " Pfad"),
    (" original filename", " ursprünglicher Dateiname"),
    (" imported at", " importiert am"),
    (" provenance", " Herkunft"),
    (" coverage start", " Abdeckungsbeginn"),
    (" coverage end", " Abdeckungsende"),
    ("Original filename", "Ursprünglicher Dateiname"),
    ("Original file name", "Ursprünglicher Dateiname"),
    ("Managed filename", "Verwalteter Dateiname"),
    ("File name", "Dateiname"),
    ("Relative path", "Relativer Pfad"),
    ("Document title", "Dokumenttitel"),
    ("Provider/source", "Anbieter/Quelle"),
    ("Source URL", "Quell-URL"),
    ("Retrieval date", "Abrufdatum"),
    ("Effective date", "Gültigkeitsdatum"),
    (
        "Applicable production period",
        "Anwendbarer Produktionszeitraum",
    ),
    ("Factual note", "Sachliche Anmerkung"),
    ("Imported at", "Importiert am"),
    ("Provenance", "Herkunft"),
    (
        "Source global evidence ID",
        "ID der globalen Ausgangs-Evidence",
    ),
    ("Derived from evidence ID", "Abgeleitet von Evidence-ID"),
    ("Generator version", "Generatorversion"),
    ("Generated disclosure text", "Generierter Hinweistext"),
    ("File extension", "Dateiendung"),
    ("MIME type", "MIME-Typ"),
    ("Audio format", "Audioformat"),
    ("Audio channels", "Audiokanäle"),
    ("Audio sample rate (Hz)", "Audio-Abtastrate (Hz)"),
    ("Audio duration (ms)", "Audiodauer (ms)"),
    ("Audio bit depth", "Audio-Bittiefe"),
    ("Suno created timestamp", "Suno-Erstellungszeitstempel"),
    ("Suno created date", "Suno-Erstellungsdatum"),
    ("Suno ID", "Suno-ID"),
    ("Raw Suno metadata", "Suno-Rohmetadaten"),
    ("Embedded metadata", "Eingebettete Metadaten"),
    (" key", " Schlüssel"),
    (" value", " Wert"),
    ("Coverage start", "Abdeckungsbeginn"),
    ("Coverage end", "Abdeckungsende"),
    (
        "Phase-two attachment policy",
        "Richtlinie für Phase-zwei-Anhänge",
    ),
    (
        "Post-finalization addendum; phase-one snapshot remains unchanged",
        "Nachtrag nach Finalisierung; Snapshot der ersten Phase bleibt unverändert",
    ),
    ("Release audio SHA-256", "SHA-256 des Release-Audios"),
    ("Final artwork SHA-256", "SHA-256 des finalen Artworks"),
    ("Previous revision count", "Anzahl früherer Revisionen"),
    ("Generated by", "Erzeugt von"),
    ("Workflow version", "Workflow-Version"),
    ("Workflow ID", "Workflow-ID"),
    ("Workflow", "Workflow"),
    ("Meaning", "Bedeutung"),
    ("PASS definition", "PASS-Definition"),
    ("Role", "Rolle"),
    ("Size (bytes)", "Größe (Bytes)"),
    (
        "Evidence register (continuation)",
        "Evidenzregister (Fortsetzung)",
    ),
    ("(continuation)", "(Fortsetzung)"),
    ("DOCUMENTATION COMPLETE", "DOKUMENTATION ABGESCHLOSSEN"),
    (
        "MULTIPLE — see Technical Appendix",
        "MEHRERE — siehe Technischer Anhang",
    ),
    ("FINGERPRINT GENERATED", "FINGERPRINT ERZEUGT"),
    ("NO MATCH DETECTED", "KEIN TREFFER ERKANNT"),
    ("MATCH DETECTED", "ÜBEREINSTIMMUNG ERKANNT"),
    ("NO MATCH", "KEINE ÜBEREINSTIMMUNG"),
    ("NOT RUN", "NICHT AUSGEFÜHRT"),
    ("NONE RECORDED", "KEINE ERFASST"),
    ("DYNAMIC BY TRACK DURATION", "DYNAMISCH NACH TRACKDAUER"),
    ("FIXED REFERENCE DURATION", "FESTE REFERENZDAUER"),
    (
        "eIDAS QUALIFIED TRUST SERVICE – VERIFIED",
        "eIDAS-QUALIFIZIERTER VERTRAUENSDIENST – VERIFIZIERT",
    ),
    (
        "VERIFICATION CONFIGURATION INCOMPLETE",
        "VERIFIKATIONSKONFIGURATION UNVOLLSTÄNDIG",
    ),
    (
        "PROVIDER IDENTITY VERIFIED",
        "PROVIDERIDENTITÄT VERIFIZIERT",
    ),
    (
        "QUALIFIED SERVICE VERIFIED",
        "QUALIFIZIERTER DIENST VERIFIZIERT",
    ),
    ("TRUST SERVICE VERIFIED", "VERTRAUENSDIENST VERIFIZIERT"),
    ("AUTHENTICATION REQUIRED", "AUTHENTIFIZIERUNG ERFORDERLICH"),
    ("CONFIGURATION INCOMPLETE", "KONFIGURATION UNVOLLSTÄNDIG"),
    ("VERIFICATION FAILED", "VERIFIKATION FEHLGESCHLAGEN"),
    ("CONNECTION FAILED", "VERBINDUNG FEHLGESCHLAGEN"),
    ("UNSUPPORTED RESPONSE", "NICHT UNTERSTÜTZTE ANTWORT"),
    ("ANCHOR MISMATCH", "ANKERABWEICHUNG"),
    ("PROVIDER ERROR", "PROVIDERFEHLER"),
    ("CHECK FAILED", "PRÜFUNG FEHLGESCHLAGEN"),
    ("NOT CHECKED", "NICHT GEPRÜFT"),
    ("REQUESTING", "WIRD ANGEFORDERT"),
    ("ATTACHED", "ANGEHÄNGT"),
    ("ENABLED", "AKTIVIERT"),
    ("VERIFIED", "VERIFIZIERT"),
    ("FAILED", "FEHLGESCHLAGEN"),
    ("READY", "BEREIT"),
    ("DISABLED", "DEAKTIVIERT"),
    ("NOT CONFIGURED", "NICHT KONFIGURIERT"),
    ("AUTHENTICATION FAILED", "AUTHENTIFIZIERUNG FEHLGESCHLAGEN"),
    ("PROVIDER UNAVAILABLE", "ANBIETER NICHT VERFÜGBAR"),
    ("CONFIGURATION INVALID", "KONFIGURATION UNGÜLTIG"),
    (
        "SKIPPED NOT CONFIGURED",
        "ÜBERSPRUNGEN — NICHT KONFIGURIERT",
    ),
    ("ENGINE UNAVAILABLE", "ENGINE NICHT VERFÜGBAR"),
    ("UNSUPPORTED FORMAT", "NICHT UNTERSTÜTZTES FORMAT"),
    ("PROCESSING FAILED", "VERARBEITUNG FEHLGESCHLAGEN"),
    ("STALE", "VERALTET"),
    ("NOT_RUN", "NICHT_AUSGEFÜHRT"),
    ("FAIL", "FEHLGESCHLAGEN"),
    ("BLOCKED", "BLOCKIERT"),
    ("NOT_VERIFIED", "NICHT_VERIFIZIERT"),
    ("MULTI-SAMPLE", "MEHRFACH-PROBE"),
    (
        "INCOMPLETE – generative AI use NOT DOCUMENTED",
        "UNVOLLSTÄNDIG – Nutzung generativer KI NICHT DOKUMENTIERT",
    ),
    (
        "Potential deepfake-related indicator recorded",
        "Potenzieller Deepfake-bezogener Indikator erfasst",
    ),
    (
        "Documented deepfake-related indicators: none recorded",
        "Dokumentierte Deepfake-bezogene Indikatoren: keine erfasst",
    ),
    (
        "Deepfake-related indicator documentation: INCOMPLETE",
        "Dokumentation Deepfake-bezogener Indikatoren: UNVOLLSTÄNDIG",
    ),
    (
        "BYTE-IDENTICAL / SHA-256 MATCH",
        "BYTE-IDENTISCH / SHA-256-ÜBEREINSTIMMUNG",
    ),
    ("NO SHA-256 MATCH", "KEINE SHA-256-ÜBEREINSTIMMUNG"),
    ("VOCAL_LYRICS_ONLY", "NUR_VOCAL_LYRICS"),
    ("STRUCTURE_ONLY", "NUR_STRUKTUR"),
    ("MIXED", "GEMISCHT"),
    ("OTHER", "SONSTIGES"),
    ("EMPTY", "LEER"),
    ("VOCAL", "MIT_GESANG"),
    ("INSTRUMENTAL", "INSTRUMENTAL"),
    ("UNSPECIFIED", "NICHT_SPEZIFIZIERT"),
    ("YES", "JA"),
    ("NO", "NEIN"),
    ("NOT DOCUMENTED", "NICHT DOKUMENTIERT"),
    ("NOT RECORDED", "NICHT ERFASST"),
    ("NOT VERIFIED", "NICHT VERIFIZIERT"),
    ("DOCUMENTED", "DOKUMENTIERT"),
    ("COMPLETE", "VOLLSTÄNDIG"),
];
