pub(super) const LABEL_REPLACEMENTS_A: &[(&str, &str)] = &[
        (
            "SunoDM – Technical Documentation and Evidence Certificate",
            "SunoDM – Technisches Dokumentations- und Evidenzzertifikat",
        ),
        (
            "SunoDM Technical Documentation and Evidence Certificate",
            "SunoDM Technisches Dokumentations- und Evidenzzertifikat",
        ),
        ("Summary", "Zusammenfassung"),
        ("Evidence Overview", "Evidenzübersicht"),
        ("Contents", "Inhaltsverzeichnis"),
        (
            "Full Technical Certificate",
            "Vollständiges technisches Zertifikat",
        ),
        (
            "Technical Evidence Certificate",
            "Technisches Evidenzzertifikat",
        ),
        ("Technical Appendix", "Technischer Anhang"),
        (
            "Appendix A — ACRCloud sample records",
            "Anhang A — ACRCloud-Probendatensätze",
        ),
        (
            "Appendix B — Previous revision references",
            "Anhang B — Referenzen früherer Revisionen",
        ),
        ("TRACK", "TRACK"),
        ("Human Work", "Menschliche Arbeit"),
        ("AI Transparency", "KI-Transparenz"),
        ("Evidence & Licenses", "Evidenz & Lizenzen"),
        ("Integrity", "Integrität"),
        ("Finalize", "Finalisierung"),
        ("Source", "Quelle"),
        ("INTEGRITY", "INTEGRITÄT"),
        ("RIGHTS EVIDENCE", "RECHTE-EVIDENCE"),
        ("AI TRANSPARENCY", "KI-TRANSPARENZ"),
        ("AUDIO SCREENING", "AUDIO-SCREENING"),
        ("EXTERNAL TIMESTAMP", "EXTERNER ZEITSTEMPEL"),
        ("Final artwork preview", "Vorschau des finalen Artworks"),
        ("Final generation", "Finale Erzeugung"),
        ("Suno plan", "Suno-Tarif"),
        (
            "Release = Suno final export",
            "Release = finaler Suno-Export",
        ),
        ("Evidence files", "Evidence-Dateien"),
        ("Production period covered", "Produktionszeitraum abgedeckt"),
        ("Final generation covered", "Finale Erzeugung abgedeckt"),
        ("Terms archived", "Nutzungsbedingungen archiviert"),
        ("Generative AI documented", "Generative KI dokumentiert"),
        ("Disclosure documented", "Hinweis dokumentiert"),
        ("Artwork documented", "Artwork dokumentiert"),
        ("Status", "Status"),
        ("SHA-256 MATCH", "SHA-256-ÜBEREINSTIMMUNG"),
        ("SHA-256 MISMATCH", "SHA-256-ABWEICHUNG"),
        ("NOT AVAILABLE", "NICHT VERFÜGBAR"),
        ("NOT COVERED", "NICHT ABGEDECKT"),
        ("NOTICE", "HINWEIS"),
        ("ERROR", "FEHLER"),
        ("PASS", "PASS"),
        (
            "Track / production timeline",
            "Track- / Produktions-Timeline",
        ),
        ("Technical finalization", "Technische Finalisierung"),
        (
            "Artwork process overview",
            "Übersicht des Artwork-Prozesses",
        ),
        ("Suno original", "Suno-Original"),
        ("AI original", "KI-Original"),
        ("AI edited", "KI-bearbeitet"),
        ("Human edited", "Menschlich bearbeitet"),
        ("Final", "Final"),
        ("Release artwork", "Release-Artwork"),
        ("Preview N/A", "Vorschau N/A"),
        (
            "Audio sampling visualization",
            "Visualisierung der Audio-Proben",
        ),
        ("External screening", "Externes Screening"),
        ("Sample summary", "Probenzusammenfassung"),
        ("Sampled duration", "Geprüfte Dauer"),
        ("Coverage", "Abdeckung"),
        (
            "Screening and workflow snapshot",
            "Screening- und Workflow-Snapshot",
        ),
        ("Provider response", "Providerantwort"),
        ("A. Technical timestamp", "A. Technischer Zeitstempel"),
        (
            "B. Provider trust and qualification",
            "B. Providervertrauen und Qualifikation",
        ),
        (
            "Provider Trust and Qualification",
            "Providervertrauen und Qualifikation",
        ),
        (
            "Provider configuration detail",
            "Details zur Providerkonfiguration",
        ),
        ("Provider configuration", "Providerkonfiguration"),
        (
            "Automatic request for this finalization",
            "Automatische Anfrage für diese Finalisierung",
        ),
        (
            "Concrete timestamp status",
            "Status des konkreten Zeitstempels",
        ),
        (
            "Concrete timestamp detail",
            "Details zum konkreten Zeitstempel",
        ),
        ("Referenced artifact", "Referenziertes Artefakt"),
        ("Manifest anchor SHA-256", "SHA-256 des Manifestankers"),
        ("Timestamp protocol", "Zeitstempelprotokoll"),
        ("Technical status", "Technischer Status"),
        ("Provider qualification", "Providerqualifikation"),
        ("Protocol", "Protokoll"),
        ("Hash algorithm", "Hash-Algorithmus"),
        ("Provider response format", "Format der Providerantwort"),
        ("Provider adapter", "Provideradapter"),
        ("Timestamp value", "Zeitstempelwert"),
        ("Provider reference ID", "Provider-Referenz-ID"),
        ("Provider endpoint", "Provider-Endpunkt"),
        ("Policy OID", "Policy-OID"),
        ("Service identifier", "Dienstkennung"),
        (
            "Signer certificate subject",
            "Subjekt des Signer-Zertifikats",
        ),
        (
            "Signer certificate issuer",
            "Aussteller des Signer-Zertifikats",
        ),
        (
            "Signer certificate serial",
            "Seriennummer des Signer-Zertifikats",
        ),
        (
            "Signer certificate SHA-256",
            "SHA-256 des Signer-Zertifikats",
        ),
        (
            "Technical verification timestamp",
            "Zeitpunkt der technischen Verifikation",
        ),
        (
            "Provider response structurally valid",
            "Providerantwort strukturell gültig",
        ),
        ("Manifest hash binding", "Manifest-Hashbindung"),
        (
            "Timestamp signature applicable",
            "Zeitstempelsignatur anwendbar",
        ),
        ("Timestamp signature valid", "Zeitstempelsignatur gültig"),
        ("Certificate chain applicable", "Zertifikatskette anwendbar"),
        (
            "Certificate chain technically verified",
            "Zertifikatskette technisch verifiziert",
        ),
        (
            "Provider identity technically recognized",
            "Provideridentität technisch erkannt",
        ),
        ("Policy match", "Policy-Übereinstimmung"),
        ("Hash binding", "Hashbindung"),
        ("Provider identity", "Provideridentität"),
        ("eIDAS qualification", "eIDAS-Qualifikation"),
        (
            "Qualification at timestamp",
            "Qualifikation zum Zeitstempelzeitpunkt",
        ),
        ("Current qualification", "Aktuelle Qualifikation"),
        ("Qualification result detail", "Details zum Qualifikationsergebnis"),
        ("Qualification detail", "Details zur Qualifikation"),
        (
            "Verified higher qualification",
            "Verifizierte höhere Qualifikation",
        ),
        ("Qualification checked at", "Qualifikation geprüft am"),
        (
            "Recognized Trust Service Provider",
            "Erkannter Vertrauensdiensteanbieter",
        ),
        ("Recognized Trust Service", "Erkannter Vertrauensdienst"),
        ("Trust Service type", "Vertrauensdiensttyp"),
        ("Trust Service status", "Vertrauensdienststatus"),
        (
            "Service status at timestamp",
            "Dienststatus zum Zeitstempelzeitpunkt",
        ),
        ("Current service status", "Aktueller Dienststatus"),
        ("Trust Service identifier", "Vertrauensdienstkennung"),
        ("Trust Service", "Vertrauensdienst"),
        ("Qualification type", "Qualifikationstyp"),
        ("Status valid from", "Status gültig ab"),
        ("Status valid until", "Status gültig bis"),
        (
            "Timestamp-time status valid from",
            "Zeitstempelzeitpunkt-Status gültig ab",
        ),
        (
            "Timestamp-time status valid until",
            "Zeitstempelzeitpunkt-Status gültig bis",
        ),
        ("Current status valid from", "Aktueller Status gültig ab"),
        ("Current status valid until", "Aktueller Status gültig bis"),
        (
            "Identity certificate SHA-256",
            "SHA-256 des Identitätszertifikats",
        ),
        (
            "Identity certificate subject",
            "Subjekt des Identitätszertifikats",
        ),
        (
            "Identity certificate issuer",
            "Aussteller des Identitätszertifikats",
        ),
        (
            "Identity certificate serial",
            "Seriennummer des Identitätszertifikats",
        ),
        ("Identity policy OID", "Identitäts-Policy-OID"),
        ("Trusted List source", "Quelle der Vertrauensliste"),
        ("Trusted List territory", "Gebiet der Vertrauensliste"),
        ("Trusted List version", "Version der Vertrauensliste"),
        ("Trusted List sequence", "Sequenz der Vertrauensliste"),
        ("Trusted List issued at", "Vertrauensliste ausgestellt am"),
        (
            "Trusted List next update",
            "Nächste Aktualisierung der Vertrauensliste",
        ),
        ("Trusted List SHA-256", "SHA-256 der Vertrauensliste"),
        (
            "Trusted List validated at",
            "Vertrauensliste validiert am",
        ),
        ("Trusted List validation", "Validierung der Vertrauensliste"),
        (
            "Independent trust verification",
            "Unabhängige Vertrauensprüfung",
        ),
        (
            "No validated qualification source was checked. This does not mean that the provider is unsafe or not qualified.",
            "Es wurde keine validierte Qualifikationsquelle geprüft. Dies bedeutet nicht, dass der Provider unsicher oder nicht qualifiziert ist.",
        ),
        ("API version", "API-Version"),
        ("Workflow checks", "Workflow-Prüfungen"),
        (
            "Provider configuration status",
            "Status der Providerkonfiguration",
        ),
        ("Step", "Schritt"),
        (
            "Authoritative status / N/A reason",
            "Autoritativer Status / N/A-Grund",
        ),
        ("N/A reason", "N/A-Grund"),
        (
            "Evidence Register (continued)",
            "Evidenzregister (Fortsetzung)",
        ),
        ("Provider response archive", "Provider-Antwortarchiv"),
        (
            "Consolidated response archive",
            "Konsolidiertes Antwortarchiv",
        ),
        ("ACRCloud sample responses", "ACRCloud-Probenantworten"),
        (
            "Single ACRCloud response archive",
            "Archiv einer einzelnen ACRCloud-Antwort",
        ),
        (
            "Multiple response archives retained in the sample records",
            "Mehrere Antwortarchive sind in den Probendatensätzen erhalten",
        ),
        (
            "Shared response archive referenced by all sample records",
            "Gemeinsames Antwortarchiv wird von allen Probendatensätzen referenziert",
        ),
        (
            "Partial consolidated response archive",
            "Teilweise konsolidiertes Antwortarchiv",
        ),
        (" of ", " von "),
        ("sample records", "Probendatensätze"),
        (
            "Top-level response archive recorded; per-sample bindings not documented",
            "Übergeordnetes Antwortarchiv erfasst; Bindungen je Probe nicht dokumentiert",
        ),
        (
            "Conflicting top-level and per-sample response archive references retained",
            "Widersprüchliche übergeordnete und probenspezifische Antwortarchiv-Referenzen erhalten",
        ),
        ("No response archive recorded", "Kein Antwortarchiv erfasst"),
        (
            "Human contribution documented",
            "Menschlicher Beitrag dokumentiert",
        ),
        (
            "Documented human contribution",
            "Dokumentierter menschlicher Beitrag",
        ),
];
