pub(super) const LABEL_REPLACEMENTS_B: &[(&str, &str)] = &[
    (
        "External desktop/post-export editing documented",
        "Externe Desktop-/Post-Export-Bearbeitung dokumentiert",
    ),
    (
        "Documented desktop/post-export editing",
        "Dokumentierte Desktop-/Post-Export-Bearbeitung",
    ),
    (
        "Documented Suno style prompt",
        "Dokumentierter Suno-Style-Prompt",
    ),
    ("Source Evidence ID", "Quell-Evidence-ID"),
    ("Source SHA-256", "Quell-SHA-256"),
    ("Previous revisions", "Frühere Revisionen"),
    (
        "Full numbered list in Technical Appendix",
        "Vollständige nummerierte Liste im technischen Anhang",
    ),
    ("Position", "Position"),
    ("Duration", "Dauer"),
    ("Result", "Ergebnis"),
    ("Provider", "Provider"),
    (
        "A. Certificate / Snapshot Identity",
        "A. Zertifikats- / Snapshot-Identität",
    ),
    ("B. Track identity", "B. Track-Identität"),
    ("C. Final Suno Generation", "C. Finale Suno-Erzeugung"),
    ("D. Source provenance", "D. Herkunft der Quellen"),
    ("E. Human contribution", "E. Menschlicher Beitrag"),
    (
        "F. Suno Generation Text Field",
        "F. Suno Generierungs-Textfeld",
    ),
    (
        "F.1 Unclassified legacy lyrics data",
        "F.1 Nicht klassifizierte historische Lyrics-Daten",
    ),
    (
        "G.1 AI Transparency Assessment – Audio",
        "G.1 KI-Transparenzbewertung – Audio",
    ),
    (
        "G.2 AI Transparency Assessment – Artwork",
        "G.2 KI-Transparenzbewertung – Artwork",
    ),
    (
        "G. AI Transparency Assessment",
        "G. KI-Transparenzbewertung",
    ),
    (
        "H. License and rights evidence",
        "H. Lizenz- und Rechte-Evidence",
    ),
    (
        "I. External Timestamp Evidence",
        "I. Externe Zeitstempel-Evidence",
    ),
    ("J. Evidence register", "J. Evidenzregister"),
    (
        "K. Integrity anchors and workflow",
        "K. Integritätsanker und Workflow",
    ),
    ("K. Integrity anchors", "K. Integritätsanker"),
    (
        "K.1 Configured workflow checks",
        "K.1 Konfigurierte Workflow-Prüfungen",
    ),
    (
        "K.2 Pre-release audio screening",
        "K.2 Audio-Screening vor Veröffentlichung",
    ),
    (
        "Pre-release audio screening",
        "Audio-Screening vor Veröffentlichung",
    ),
    ("Local screening status", "Status des lokalen Screenings"),
    ("Local engine", "Lokale Engine"),
    ("Local engine version", "Version der lokalen Engine"),
    ("Fingerprint algorithm", "Fingerprint-Algorithmus"),
    ("Local source Evidence ID", "Lokale Quell-Evidence-ID"),
    ("Local source path", "Lokaler Quellpfad"),
    ("Local source SHA-256", "Lokaler Quell-SHA-256"),
    ("Local source size (bytes)", "Lokale Quellgröße (Bytes)"),
    ("Local measured duration (ms)", "Lokal gemessene Dauer (ms)"),
    ("Local record path", "Pfad des lokalen Datensatzes"),
    ("Local record SHA-256", "SHA-256 des lokalen Datensatzes"),
    ("Local generated at", "Lokal erzeugt am"),
    (
        "External screening provider",
        "Anbieter des externen Screenings",
    ),
    (
        "External screening status",
        "Status des externen Screenings",
    ),
    (
        "External provider configured at snapshot",
        "Externer Anbieter im Snapshot konfiguriert",
    ),
    ("External source Evidence ID", "Externe Quell-Evidence-ID"),
    ("External source path", "Externer Quellpfad"),
    ("External source SHA-256", "Externer Quell-SHA-256"),
    ("External checked at", "Extern geprüft am"),
    (
        "External sample offset (ms)",
        "Offset der externen Probe (ms)",
    ),
    (
        "External sample duration (ms)",
        "Dauer der externen Probe (ms)",
    ),
    (
        "External source duration (ms)",
        "Dauer der externen Quelle (ms)",
    ),
    ("External request count", "Anzahl externer Anfragen"),
    ("External response archive", "Archiv der externen Antwort"),
    ("External response SHA-256", "SHA-256 der externen Antwort"),
    ("External screening mode", "Modus des externen Screenings"),
    ("Requested coverage", "Angeforderte Abdeckung"),
    ("Calculation mode", "Berechnungsmodus"),
    ("Reference duration (seconds)", "Referenzdauer (Sekunden)"),
    ("Target screening duration (ms)", "Ziel-Prüfdauer (ms)"),
    ("Planned requests", "Geplante Anfragen"),
    ("Executed requests", "Ausgeführte Anfragen"),
    ("Unique samples", "Eindeutige Proben"),
    ("Duplicate samples", "Doppelte Proben"),
    ("Overlapping samples", "Überlappende Proben"),
    (
        "Unique sampled duration (ms)",
        "Eindeutig geprüfte Audiodauer (ms)",
    ),
    ("Track coverage (%)", "Track-Abdeckung (%)"),
    ("ACRCloud provider status", "ACRCloud-Anbieterstatus"),
    ("Overall result", "Gesamtergebnis"),
    ("track coverage", "Track-Abdeckung"),
    ("Sample results", "Probenergebnisse"),
    ("Response archive", "Antwortarchiv"),
    ("Response SHA-256", "Antwort-SHA-256"),
    ("Sample", "Probe"),
    ("Provider matches", "Anbietertreffer"),
    ("Provider match", "Anbietertreffer"),
    (
        "recorded; complete per-sample records in Technical Appendix",
        "erfasst; vollständige probenspezifische Datensätze im technischen Anhang",
    ),
    (
        "Provider-derived metadata",
        "Vom Anbieter abgeleitete Metadaten",
    ),
    (
        "L. Technical certificate statement",
        "L. Erklärung zum technischen Zertifikat",
    ),
    (
        "Configured documentation requirements for this step were satisfied.",
        "Die konfigurierten Dokumentationsanforderungen für diesen Schritt wurden erfüllt.",
    ),
    (
        "configured documentation requirements completed",
        "konfigurierte Dokumentationsanforderungen abgeschlossen",
    ),
    (
        "Historical user data; not a plan-at-generation claim",
        "Historische Nutzerdaten; keine Aussage zum Tarif bei der Erzeugung",
    ),
    (
        "Legacy plan-at-creation value",
        "Historischer Tarifwert bei der Erstellung",
    ),
    ("Evidence-derived metadata", "Aus Evidenzmetadaten"),
    ("User-confirmed fact", "Vom Nutzer bestätigte Angabe"),
    (
        "Classification-derived presentation",
        "Aus der Klassifizierung abgeleitete Darstellung",
    ),
    ("System verification", "Systemprüfung"),
    ("System value", "Systemwert"),
    (
        "Actual Suno export filename",
        "Tatsächlicher Dateiname des Suno-Exports",
    ),
    (
        "Actual release filename",
        "Tatsächlicher Dateiname der Veröffentlichung",
    ),
    (
        "Final generation date origin",
        "Herkunft des Datums der finalen Erzeugung",
    ),
    ("Final generation date", "Datum der finalen Erzeugung"),
    ("Final generation ID", "ID der finalen Erzeugung"),
    (
        "Final-generation date covered",
        "Datum der finalen Erzeugung abgedeckt",
    ),
    ("Finalized at", "Finalisiert am"),
    ("Finalization timestamp", "Zeitpunkt der Finalisierung"),
    ("Final result", "Endergebnis"),
    ("Suno project URL", "Suno-Projekt-URL"),
    (
        "Suno Studio metadata detected",
        "Suno-Studio-Metadaten erkannt",
    ),
    (
        "Metadata detection origin",
        "Herkunft der Metadatenerkennung",
    ),
    ("Metadata origin", "Metadatenherkunft"),
    ("Suno plan at generation", "Suno-Tarif bei der Erzeugung"),
    ("Suno model", "Suno-Modell"),
    (
        "Download/export date origin",
        "Herkunft des Download-/Exportdatums",
    ),
    ("Download/export date", "Download-/Exportdatum"),
    (
        "Release identical to Suno final export",
        "Release identisch mit finalem Suno-Export",
    ),
    ("Release identity origin", "Herkunft der Release-Identität"),
    (
        "Assigned subscription evidence jointly covers the production period",
        "Zugeordnete Abo-Evidence deckt den Produktionszeitraum gemeinsam ab",
    ),
    (
        "Terms evidence not available",
        "Evidence zu Nutzungsbedingungen nicht verfügbar",
    ),
    (
        "Terms evidence exists",
        "Evidence zu Nutzungsbedingungen vorhanden",
    ),
    (
        "Terms evidence IDs",
        "IDs der Evidence zu Nutzungsbedingungen",
    ),
    (
        "Archived service-terms evidence",
        "Archivierte Evidence zu Nutzungsbedingungen",
    ),
    (
        "Terms applicable to documented production period",
        "Für den dokumentierten Produktionszeitraum geltende Nutzungsbedingungen",
    ),
    (
        "Future archived Terms",
        "Künftig geltende archivierte Nutzungsbedingungen",
    ),
    (
        "Other archived Terms",
        "Weitere archivierte Nutzungsbedingungen",
    ),
    (
        "Not applicable to production before",
        "Nicht auf Produktionen vor diesem Datum anwendbar:",
    ),
    ("Terms version", "Nutzungsbedingungen-Fassung"),
    ("effective date", "Gültigkeitsdatum"),
    (
        "documented production period",
        "dokumentierter Produktionszeitraum",
    ),
    (
        "External timestamp evidence at technical finalization",
        "Externer Zeitstempelnachweis bei technischer Finalisierung",
    ),
    ("Evidence file count", "Anzahl der Evidence-Dateien"),
    ("Previous revision archives", "Archive früherer Revisionen"),
    ("Blocking deviations", "Blockierende Abweichungen"),
    (
        "Mandatory steps completed",
        "Abgeschlossene Pflichtschritte",
    ),
    ("N/A steps with reasons", "N/A-Schritte mit Begründungen"),
    ("Application version", "Anwendungsversion"),
    ("Certificate schema", "Zertifikatsschema"),
    ("Certificate version", "Zertifikatsversion"),
    ("Certificate ID", "Zertifikats-ID"),
    ("Page", "Seite"),
    ("Documentation status", "Dokumentationsstatus"),
    ("Documented title", "Dokumentierter Titel"),
    ("Track identity", "Track-Identität"),
    ("Track", "Track"),
    ("Artist", "Künstler/in"),
    ("Production start", "Produktionsbeginn"),
    ("Production end", "Produktionsende"),
    ("Last editing date", "Datum der letzten Bearbeitung"),
    ("Commercial use intended", "Kommerzielle Nutzung vorgesehen"),
    ("Suno profile", "Suno-Profil"),
    ("Suno handle", "Suno-Benutzername"),
    ("External audio uploaded", "Externes Audio hochgeladen"),
    ("Own audio uploaded", "Eigenes Audio hochgeladen"),
    (
        "Third-party samples uploaded",
        "Samples Dritter hochgeladen",
    ),
    ("Third-party samples", "Samples Dritter"),
    ("Code-based generation", "Codebasierte Erzeugung"),
    ("Source-code evidence", "Evidence zum Quellcode"),
    (
        "Code-generated audio evidence",
        "Evidence zu codegeneriertem Audio",
    ),
    (
        "Code-audio post-processing operations",
        "Nachbearbeitungsschritte für codegeneriertes Audio",
    ),
];
