use crate::error::{AppError, Result};
use crate::model::{
    BlockingDeviation, EvidenceItem, EvidenceRole, FactOrigin, Profile, StepState, StepStatus,
    TrackAutomation, TrackRecord,
};
use crate::workflow;
use printpdf::{
    BuiltinFont, Color, Line, LinePoint, Mm, Op, ParsedFont, PdfDocument, PdfFontHandle, PdfPage,
    PdfParseErrorSeverity, PdfParseOptions, PdfSaveOptions, Point, Pt, Rgb, TextItem,
};
use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

const DOCUMENT_TITLE: &str = "SunoDM – Technischer Dokumentations- und Evidenznachweis";
const GENERATED_BY: &str = "Generated by Suno Documentation Manager";
const CERTIFICATE_STATEMENT: &str = "This technical certificate confirms the recorded inputs, finalized snapshot, registered evidence, recorded provenance, SHA-256 values, and configured workflow checks. It does not confirm authorship, rights ownership, non-infringement, legality, license validity, judicial evidentiary weight, statutory compliance, or governmental certification.";

const PAGE_WIDTH_MM: f32 = 210.0;
const PAGE_HEIGHT_MM: f32 = 297.0;
const LEFT_MM: f32 = 16.0;
const RIGHT_MM: f32 = 194.0;
const FIRST_PAGE_TOP_MM: f32 = 282.0;
const CONTINUATION_TOP_MM: f32 = 276.0;
const CONTENT_BOTTOM_MM: f32 = 21.0;
const FOOTER_RULE_Y_MM: f32 = 16.0;
const FOOTER_TEXT_Y_MM: f32 = 10.5;

/// The immutable, finalized data used to render a documentation certificate PDF.
///
/// `steps` is authoritative and is rendered in exactly the supplied order. `evidence` must be
/// the already filtered and `relative_path`-sorted slice used for the finalized evidence
/// manifest. The renderer validates those invariants but deliberately does not re-evaluate,
/// filter, or sort either slice.
pub struct CertificatePdfSnapshot<'a> {
    pub track: &'a TrackRecord,
    pub automation: &'a TrackAutomation,
    pub profile: &'a Profile,
    pub steps: &'a [StepState],
    pub evidence: &'a [&'a EvidenceItem],
    pub deviations: &'a [BlockingDeviation],
    pub revision_references: &'a [String],
    pub certificate_id: &'a str,
    pub finalized_at: &'a str,
    pub certificate_version: &'a str,
    pub sha256sums_sha256: &'a str,
    pub evidence_manifest_sha256: &'a str,
    pub markdown_certificate_sha256: &'a str,
}

/// Render an A4, multi-page technical certificate from a finalized snapshot.
pub fn generate_pdf(snapshot: &CertificatePdfSnapshot<'_>) -> Result<Vec<u8>> {
    let workflow_config = validate_snapshot(snapshot)?;
    let step_labels = workflow_config
        .steps
        .iter()
        .map(|step| (step.id.as_str(), step.name.as_str()))
        .collect::<HashMap<_, _>>();

    let mut layout = PdfLayout::new();
    render_document_title(&mut layout);
    render_header_metadata(&mut layout, snapshot);
    render_track_data(&mut layout, snapshot);
    render_final_suno_generation(&mut layout, snapshot);
    render_sources_and_generation(&mut layout, snapshot);
    render_human_contribution(&mut layout, snapshot);
    render_ai_usage(&mut layout, snapshot);
    render_artwork_checks(&mut layout, snapshot);
    render_license_and_rights(&mut layout, snapshot);
    render_evidence_register(&mut layout, snapshot.evidence);
    render_integrity_anchors(&mut layout, snapshot);
    render_workflow(&mut layout, snapshot.steps, &step_labels);
    render_certificate_statement(&mut layout, snapshot);

    let pages = layout.into_pages(snapshot.certificate_id);
    let mut document = PdfDocument::new(DOCUMENT_TITLE);
    document.metadata.info.author = snapshot.profile.artist_name.clone();
    document.metadata.info.creator = GENERATED_BY.to_owned();
    document.metadata.info.producer = GENERATED_BY.to_owned();
    document.metadata.info.subject =
        "Finalized technical documentation, evidence, and integrity snapshot".to_owned();
    document.metadata.info.identifier = snapshot.certificate_id.to_owned();
    document.metadata.info.keywords = vec![
        "SunoDM".to_owned(),
        "documentation".to_owned(),
        "evidence".to_owned(),
        "SHA-256".to_owned(),
    ];
    document.with_pages(pages);

    let mut warnings = Vec::new();
    let mut bytes = document.save(&PdfSaveOptions::default(), &mut warnings);
    if let Some(warning) = warnings
        .iter()
        .find(|warning| warning.severity == PdfParseErrorSeverity::Error)
    {
        return Err(AppError::Data(format!(
            "Certificate PDF serialization failed: {}",
            warning.msg
        )));
    }
    make_pdf_trailer_id_deterministic(&mut bytes, snapshot.certificate_id)?;
    validate_pdf_bytes(&bytes)?;
    Ok(bytes)
}

fn make_pdf_trailer_id_deterministic(bytes: &mut [u8], certificate_id: &str) -> Result<()> {
    const PREFIX: &[u8] = b"/ID[(";
    const SEPARATOR: &[u8] = b")(";
    const SUFFIX: &[u8] = b")]";
    const ID_LEN: usize = 32;

    let prefix = bytes
        .windows(PREFIX.len())
        .rposition(|window| window == PREFIX)
        .ok_or_else(|| AppError::Data("Certificate PDF trailer has no document ID.".into()))?;
    let first = prefix + PREFIX.len();
    let separator = first + ID_LEN;
    let second = separator + SEPARATOR.len();
    let suffix = second + ID_LEN;
    if bytes.get(separator..second) != Some(SEPARATOR)
        || bytes.get(suffix..suffix + SUFFIX.len()) != Some(SUFFIX)
    {
        return Err(AppError::Data(
            "Certificate PDF trailer has an unexpected document ID format.".into(),
        ));
    }

    let digest = crate::security::sha256_bytes(certificate_id.as_bytes());
    bytes[first..separator].copy_from_slice(&digest.as_bytes()[..ID_LEN]);
    bytes[second..suffix].copy_from_slice(&digest.as_bytes()[ID_LEN..]);
    Ok(())
}

/// Parse staged PDF bytes and reject malformed or empty documents before publication.
pub fn validate_pdf_bytes(bytes: &[u8]) -> Result<()> {
    if !bytes.starts_with(b"%PDF-") {
        return Err(AppError::Validation(
            "Generated certificate PDF has no valid PDF header.".into(),
        ));
    }

    let mut warnings = Vec::new();
    let document =
        PdfDocument::parse(bytes, &PdfParseOptions::default(), &mut warnings).map_err(|error| {
            AppError::Validation(format!(
                "Generated certificate PDF cannot be parsed: {error}"
            ))
        })?;
    if document.pages.is_empty() {
        return Err(AppError::Validation(
            "Generated certificate PDF contains no pages.".into(),
        ));
    }
    if let Some(warning) = warnings
        .iter()
        .find(|warning| warning.severity == PdfParseErrorSeverity::Error)
    {
        return Err(AppError::Validation(format!(
            "Generated certificate PDF contains an invalid operation: {}",
            warning.msg
        )));
    }
    Ok(())
}

fn validate_snapshot(snapshot: &CertificatePdfSnapshot<'_>) -> Result<workflow::WorkflowConfig> {
    for (label, value) in [
        ("certificate ID", snapshot.certificate_id),
        ("finalization timestamp", snapshot.finalized_at),
        ("certificate version", snapshot.certificate_version),
    ] {
        if value.trim().is_empty() {
            return Err(AppError::Data(format!(
                "Certificate PDF snapshot has no {label}."
            )));
        }
    }
    for (label, digest) in [
        ("SHA256SUMS.txt", snapshot.sha256sums_sha256),
        ("EVIDENCE_MANIFEST.json", snapshot.evidence_manifest_sha256),
        (
            "DOCUMENTATION_CERTIFICATE.md",
            snapshot.markdown_certificate_sha256,
        ),
    ] {
        validate_sha256(label, digest)?;
    }

    if snapshot
        .evidence
        .windows(2)
        .any(|items| items[0].relative_path > items[1].relative_path)
    {
        return Err(AppError::Data(
            "Certificate PDF evidence is not sorted by relative path.".into(),
        ));
    }
    for item in snapshot.evidence {
        if !item.verified || item.verification_error.is_some() {
            return Err(AppError::Data(format!(
                "Certificate PDF evidence is not verified: {}",
                item.relative_path
            )));
        }
        let digest = item.sha256.as_deref().ok_or_else(|| {
            AppError::Data(format!(
                "Certificate PDF evidence has no SHA-256: {}",
                item.relative_path
            ))
        })?;
        validate_sha256(&item.relative_path, digest)?;
    }

    let config = workflow::config()?;
    if snapshot.track.workflow_id != config.id || snapshot.track.workflow_version != config.version
    {
        return Err(AppError::Data(
            "Certificate PDF workflow metadata does not match the configured workflow.".into(),
        ));
    }
    let configured_ids = config
        .steps
        .iter()
        .map(|step| step.id.as_str())
        .collect::<HashSet<_>>();
    let mut supplied_ids = HashSet::new();
    for step in snapshot.steps {
        if !configured_ids.contains(step.id.as_str()) {
            return Err(AppError::Data(format!(
                "Certificate PDF contains an unknown workflow step: {}",
                step.id
            )));
        }
        if !supplied_ids.insert(step.id.as_str()) {
            return Err(AppError::Data(format!(
                "Certificate PDF contains a duplicate workflow step: {}",
                step.id
            )));
        }
        match step.status {
            StepStatus::Pass => {}
            StepStatus::NotApplicable => {
                if step
                    .na_reason
                    .as_deref()
                    .is_none_or(|reason| reason.trim().is_empty())
                {
                    return Err(AppError::Data(format!(
                        "Certificate PDF workflow step has no N/A reason: {}",
                        step.id
                    )));
                }
            }
            _ => {
                return Err(AppError::Validation(format!(
                    "Certificate PDF workflow step is not complete: {} ({})",
                    step.id,
                    step_status(&step.status)
                )));
            }
        }
    }
    if supplied_ids.len() != configured_ids.len() {
        return Err(AppError::Data(
            "Certificate PDF workflow snapshot is incomplete.".into(),
        ));
    }
    if snapshot
        .deviations
        .iter()
        .any(|deviation| deviation.blocking && !deviation.resolved)
    {
        return Err(AppError::Validation(
            "Certificate PDF snapshot contains an open blocking deviation.".into(),
        ));
    }
    validate_rendered_text(snapshot, &config)?;
    Ok(config)
}

fn validate_sha256(label: &str, digest: &str) -> Result<()> {
    if digest.len() != 64 || !digest.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(AppError::Data(format!(
            "Certificate PDF has an invalid SHA-256 for {label}."
        )));
    }
    Ok(())
}

fn validate_rendered_text(
    snapshot: &CertificatePdfSnapshot<'_>,
    config: &workflow::WorkflowConfig,
) -> Result<()> {
    let fields = snapshot.track.fields.normalized_conditionals();
    for (label, value) in [
        ("track title", fields.title.as_str()),
        ("artist", snapshot.profile.artist_name.as_str()),
        ("Suno profile", snapshot.profile.suno_profile_name.as_str()),
        ("Suno handle", snapshot.profile.suno_handle.as_str()),
        (
            "Suno subscription start",
            snapshot.profile.subscription_start_date.as_str(),
        ),
        ("production start", fields.production_start_date.as_str()),
        ("production end", fields.production_end_date.as_str()),
        ("last editing date", fields.final_export_date.as_str()),
        ("Suno model", fields.suno_model.as_str()),
        ("Suno project URL", fields.suno_project_url.as_str()),
        (
            "Suno final generation date",
            fields.suno_final_generation_date.as_str(),
        ),
        (
            "Suno download/export date",
            fields.suno_download_export_date.as_str(),
        ),
        (
            "Suno plan at creation",
            fields.suno_plan_at_creation.as_str(),
        ),
        ("lyrics source", fields.lyrics_source.as_str()),
        ("Suno style prompt", fields.suno_style_prompt.as_str()),
        (
            "external audio source",
            fields.external_audio_source.as_str(),
        ),
        (
            "external audio provenance statement",
            fields.external_audio_ownership.as_str(),
        ),
        ("own audio source", fields.own_audio_source.as_str()),
        (
            "own audio provenance statement",
            fields.own_audio_ownership.as_str(),
        ),
        (
            "third-party sample source",
            fields.third_party_sample_source.as_str(),
        ),
        (
            "third-party sample provenance statement",
            fields.third_party_sample_ownership.as_str(),
        ),
        (
            "human editing details",
            fields.human_editing_details.as_str(),
        ),
        (
            "post-export editing details",
            fields.post_export_editing_details.as_str(),
        ),
        ("artwork origin", fields.artwork_origin.as_str()),
        ("AI image service", fields.ai_image_service.as_str()),
        (
            "code-audio post-processing note",
            fields.code_audio_post_processing_note.as_str(),
        ),
        (
            "human artwork process notes",
            fields.human_artwork_process_notes.as_str(),
        ),
        (
            "custom artwork change",
            fields.custom_artwork_change.as_str(),
        ),
        ("disclosure text", fields.disclosure_text.as_str()),
        ("workflow ID", snapshot.track.workflow_id.as_str()),
        ("workflow version", snapshot.track.workflow_version.as_str()),
        ("certificate ID", snapshot.certificate_id),
        ("finalization timestamp", snapshot.finalized_at),
        ("certificate version", snapshot.certificate_version),
    ] {
        validate_win_ansi(label, value)?;
    }

    for (label, values) in [
        (
            "code-audio post-processing operation",
            fields.code_audio_post_processing_operations.as_slice(),
        ),
        (
            "human artwork process operation",
            fields.human_artwork_process_operations.as_slice(),
        ),
        (
            "human artwork modification",
            fields.human_artwork_modifications.as_slice(),
        ),
    ] {
        for value in values {
            validate_win_ansi(label, value)?;
        }
    }

    for step in snapshot.steps {
        if let Some(reason) = step.na_reason.as_deref() {
            validate_win_ansi("workflow N/A reason", reason)?;
        }
    }
    for step in &config.steps {
        validate_win_ansi("workflow step label", &step.name)?;
    }
    for revision in snapshot.revision_references {
        validate_win_ansi("revision archive reference", revision)?;
    }
    for item in snapshot.evidence {
        validate_win_ansi("evidence relative path", &item.relative_path)?;
        validate_win_ansi("evidence imported timestamp", &item.imported_at)?;
        for (label, value) in [
            (
                "evidence original file name",
                item.metadata.original_file_name.as_str(),
            ),
            (
                "evidence document title",
                item.metadata.document_title.as_str(),
            ),
            ("evidence provider", item.metadata.provider.as_str()),
            ("evidence source URL", item.metadata.source_url.as_str()),
            (
                "evidence retrieval date",
                item.metadata.retrieval_date.as_str(),
            ),
            (
                "evidence effective date",
                item.metadata.effective_date.as_str(),
            ),
            ("evidence factual note", item.metadata.factual_note.as_str()),
            (
                "external timestamp",
                item.metadata.external_timestamp.as_str(),
            ),
            ("referenced hash", item.metadata.referenced_hash.as_str()),
            (
                "referenced artifact",
                item.metadata.referenced_artifact.as_str(),
            ),
        ] {
            validate_win_ansi(label, value)?;
        }
        for (label, value) in [
            ("evidence coverage start", item.coverage_start.as_deref()),
            ("evidence coverage end", item.coverage_end.as_deref()),
            (
                "source global evidence ID",
                item.source_global_evidence_id.as_deref(),
            ),
            (
                "derived evidence ID",
                item.derived_from_evidence_id.as_deref(),
            ),
            (
                "evidence generator version",
                item.generator_version.as_deref(),
            ),
        ] {
            if let Some(value) = value {
                validate_win_ansi(label, value)?;
            }
        }
    }
    Ok(())
}

fn validate_win_ansi(label: &str, value: &str) -> Result<()> {
    if let Some(character) = value.chars().find(|character| !is_win_ansi(*character)) {
        return Err(AppError::Data(format!(
            "Certificate PDF {label} contains a character unsupported by the built-in PDF fonts: U+{:04X}.",
            character as u32
        )));
    }
    Ok(())
}

fn is_win_ansi(character: char) -> bool {
    if character == '\n' {
        return true;
    }
    match character as u32 {
        0x20..=0x7e | 0xa0..=0xff => true,
        _ => matches!(
            character,
            '\u{20ac}'
                | '\u{201a}'
                | '\u{0192}'
                | '\u{201e}'
                | '\u{2026}'
                | '\u{2020}'
                | '\u{2021}'
                | '\u{02c6}'
                | '\u{2030}'
                | '\u{0160}'
                | '\u{2039}'
                | '\u{0152}'
                | '\u{017d}'
                | '\u{2018}'
                | '\u{2019}'
                | '\u{201c}'
                | '\u{201d}'
                | '\u{2022}'
                | '\u{2013}'
                | '\u{2014}'
                | '\u{02dc}'
                | '\u{2122}'
                | '\u{0161}'
                | '\u{203a}'
                | '\u{0153}'
                | '\u{017e}'
                | '\u{0178}'
        ),
    }
}

fn render_document_title(layout: &mut PdfLayout) {
    layout.write_wrapped(
        DOCUMENT_TITLE,
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        14.0,
        BuiltinFont::HelveticaBold,
        1.28,
    );
    layout.write_wrapped(
        "Finalisierter technischer Snapshot – keine rechtliche Zertifizierung",
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.5,
        BuiltinFont::Helvetica,
        1.2,
    );
    layout.y_mm -= 1.0;
    layout.rule(LEFT_MM, RIGHT_MM, layout.y_mm, 0.6);
    layout.y_mm -= 3.0;
}

fn render_header_metadata(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("A. Certificate / Snapshot Identity");
    let rows = vec![
        TableRow::plain("Track", documented(&snapshot.track.fields.title)),
        TableRow::plain("Artist", documented(&snapshot.profile.artist_name)),
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::mono("Finalization timestamp", snapshot.finalized_at),
        TableRow::plain("Documentation status", "DOCUMENTATION COMPLETE"),
        TableRow::mono("Application version", env!("CARGO_PKG_VERSION")),
        TableRow::mono("Workflow ID", &snapshot.track.workflow_id),
        TableRow::mono("Workflow version", &snapshot.track.workflow_version),
        TableRow::mono("Certificate version", snapshot.certificate_version),
    ];
    layout.table_rows(&rows, 45.0);
}

fn render_track_data(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("B. Track identity");
    let fields = &snapshot.track.fields;
    let rows = vec![
        TableRow::plain(
            "Documented title [User-confirmed fact]",
            documented(&fields.title),
        ),
        TableRow::plain(
            "Artist [User-confirmed fact]",
            documented(&snapshot.profile.artist_name),
        ),
        TableRow::plain(
            "Actual release filename [Evidence-derived metadata]",
            evidence_original_file_name(snapshot.evidence, EvidenceRole::ReleaseWav),
        ),
        TableRow::plain(
            "Actual Suno export filename [Evidence-derived metadata]",
            evidence_original_file_name(snapshot.evidence, EvidenceRole::SunoFinalExport),
        ),
        TableRow::plain(
            "Production start",
            documented(&fields.production_start_date),
        ),
        TableRow::plain("Production end", documented(&fields.production_end_date)),
        TableRow::plain(
            format!(
                "Last editing date [{}]",
                fact_origin_label(snapshot.automation.final_export_origin)
            ),
            documented(&fields.final_export_date),
        ),
        TableRow::plain(
            "Commercial use intended",
            yes_no(Some(fields.commercial_use_intended)),
        ),
        TableRow::plain(
            "Suno profile",
            documented(&snapshot.profile.suno_profile_name),
        ),
        TableRow::mono("Suno handle", documented(&snapshot.profile.suno_handle)),
    ];
    layout.table_rows(&rows, 45.0);
}

fn render_final_suno_generation(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("C. Final Suno Generation");
    let fields = &snapshot.track.fields;
    let rows = vec![
        TableRow::plain(
            "Final Suno generation",
            documented(&fields.suno_final_generation_date),
        ),
        TableRow::plain(
            "Origin",
            fact_origin_label(snapshot.automation.final_generation_origin),
        ),
        TableRow::plain(
            "Suno Studio metadata detected",
            yes_no_bool(snapshot.automation.suno_metadata_detected),
        ),
        TableRow::plain(
            "Suno ID [Evidence-derived metadata]",
            snapshot
                .automation
                .suno_id
                .as_deref()
                .unwrap_or("Not documented"),
        ),
        TableRow::plain(
            "Release identical to Suno final export",
            yes_no_bool(snapshot.automation.release_identical_to_suno_export),
        ),
        TableRow::plain(
            format!(
                "Download/export date [{}]",
                fact_origin_label(snapshot.automation.download_export_origin)
            ),
            documented(&fields.suno_download_export_date),
        ),
    ];
    layout.table_rows(&rows, 61.0);
}

fn render_sources_and_generation(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("D. Source provenance");
    let fields = snapshot.track.fields.normalized_conditionals();
    let mut rows = vec![
        TableRow::plain(
            "External audio uploaded",
            yes_no(fields.external_audio_uploaded),
        ),
        TableRow::plain("Own audio uploaded", yes_no(fields.own_audio_uploaded)),
        TableRow::plain(
            "Third-party samples",
            yes_no(fields.third_party_samples_uploaded),
        ),
        TableRow::plain(
            "Code-based generation",
            yes_no(fields.code_based_generation),
        ),
        TableRow::plain(
            "Source-code evidence",
            branch_value(
                fields.code_based_generation,
                evidence_relative_path(snapshot.evidence, EvidenceRole::SourceCodeFile),
            ),
        ),
        TableRow::plain(
            "Code-generated audio evidence",
            branch_value(
                fields.code_based_generation,
                evidence_relative_path(snapshot.evidence, EvidenceRole::CodeGeneratedAudioFile),
            ),
        ),
        TableRow::plain(
            "Code-audio post-processing",
            branch_value(
                fields.code_based_generation,
                yes_no(fields.code_audio_post_processed),
            ),
        ),
        TableRow::plain(
            "Code-audio post-processing operations",
            if fields.code_based_generation == Some(true)
                && fields.code_audio_post_processed == Some(true)
            {
                if fields.code_audio_post_processing_operations.is_empty() {
                    "Not recorded".into()
                } else {
                    fields.code_audio_post_processing_operations.join(", ")
                }
            } else {
                "N/A".into()
            },
        ),
        TableRow::plain(
            "External audio source",
            branch_value(
                fields.external_audio_uploaded,
                &fields.external_audio_source,
            ),
        ),
        TableRow::plain(
            "External audio provenance statement",
            branch_value(
                fields.external_audio_uploaded,
                &fields.external_audio_ownership,
            ),
        ),
        TableRow::plain(
            "Own audio source",
            branch_value(fields.own_audio_uploaded, &fields.own_audio_source),
        ),
        TableRow::plain(
            "Own audio provenance statement",
            branch_value(fields.own_audio_uploaded, &fields.own_audio_ownership),
        ),
        TableRow::plain(
            "Third-party sample source",
            branch_value(
                fields.third_party_samples_uploaded,
                &fields.third_party_sample_source,
            ),
        ),
        TableRow::plain(
            "Third-party sample provenance statement",
            branch_value(
                fields.third_party_samples_uploaded,
                &fields.third_party_sample_ownership,
            ),
        ),
    ];

    if fields.code_based_generation == Some(true) && fields.code_audio_post_processed == Some(true)
    {
        push_documented_detail(
            &mut rows,
            "Other code-audio post-processing",
            &fields.code_audio_post_processing_note,
        );
    }

    layout.table_rows(&rows, 49.0);
}

fn render_human_contribution(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("E. Human contribution");
    let fields = &snapshot.track.fields;
    let lyrics_line = if fields.instrumental_track == Some(true) {
        "Lyrics: N/A – instrumental track".to_owned()
    } else {
        format!("Lyrics: {}", documented(&fields.lyrics_text))
    };
    layout.write_wrapped(
        &lyrics_line,
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.6,
        BuiltinFont::Helvetica,
        1.3,
    );
    layout.y_mm -= 1.0;
    let mut rows = vec![
        TableRow::plain(
            "Instrumental track [User-confirmed fact]",
            yes_no(fields.instrumental_track),
        ),
        TableRow::plain(
            "Lyrics source [User-confirmed fact]",
            documented(&fields.lyrics_source),
        ),
    ];
    if fields.human_editing_performed == Some(true) {
        rows.push(TableRow::plain(
            "Selected human work [User-confirmed fact]",
            documented(&fields.human_editing_details),
        ));
    } else {
        rows.push(TableRow::plain("Selected human work", "N/A"));
    }
    if fields.post_export_editing_performed == Some(true) {
        rows.push(TableRow::plain(
            "Selected desktop-PC editing [User-confirmed fact]",
            documented(&fields.post_export_editing_details),
        ));
    } else {
        rows.push(TableRow::plain("Selected desktop-PC editing", "N/A"));
    }
    if !fields.human_artwork_process_operations.is_empty() {
        rows.push(TableRow::plain(
            "Selected human artwork process [User-confirmed fact]",
            fields.human_artwork_process_operations.join(", "),
        ));
    }
    if !fields.human_artwork_modifications.is_empty() {
        rows.push(TableRow::plain(
            "Selected human artwork modifications [User-confirmed fact]",
            fields.human_artwork_modifications.join(", "),
        ));
    }
    layout.table_rows(&rows, 59.0);
}

fn render_ai_usage(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("F. AI Usage");
    let fields = &snapshot.track.fields;
    let rows = vec![
        TableRow::plain(
            "Suno model [User-confirmed fact]",
            documented(&fields.suno_model),
        ),
        TableRow::plain(
            "Suno style prompt [User-confirmed fact]",
            documented(&fields.suno_style_prompt),
        ),
        TableRow::plain(
            "Artwork origin [User-confirmed fact]",
            documented(&fields.artwork_origin),
        ),
        TableRow::plain(
            "AI image service [User-confirmed fact]",
            if matches!(
                fields.artwork_origin.as_str(),
                "ai_generated" | "ai_assisted"
            ) {
                documented(&fields.ai_image_service)
            } else {
                "N/A"
            },
        ),
        TableRow::plain(
            "Human artwork changes [User-confirmed fact]",
            if fields.human_artwork_modifications.is_empty() {
                "N/A".into()
            } else {
                fields.human_artwork_modifications.join(", ")
            },
        ),
        TableRow::plain(
            "Disclosure applied [User-confirmed fact]",
            if fields.artwork_origin == "none" {
                "N/A"
            } else {
                yes_no(fields.disclosure_applied)
            },
        ),
        TableRow::plain(
            "Disclosure text [User-confirmed fact]",
            if fields.disclosure_applied == Some(true) {
                documented(&fields.disclosure_text)
            } else {
                "N/A"
            },
        ),
    ];
    layout.table_rows(&rows, 58.0);
}

fn render_artwork_checks(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("G. Artwork content checks");
    let fields = &snapshot.track.fields;
    let rows = vec![
        TableRow::plain(
            "Artwork origin [User-confirmed fact]",
            documented(&fields.artwork_origin),
        ),
        TableRow::plain(
            "Human artwork process [User-confirmed fact]",
            if fields.human_artwork_process_operations.is_empty() {
                "N/A".into()
            } else {
                fields.human_artwork_process_operations.join(", ")
            },
        ),
        TableRow::plain(
            "Human artwork changes [User-confirmed fact]",
            if fields.human_artwork_modifications.is_empty() {
                "N/A".into()
            } else {
                fields.human_artwork_modifications.join(", ")
            },
        ),
        TableRow::plain(
            "Depicts real person [User-confirmed fact]",
            artwork_answer(&fields.artwork_origin, fields.depicts_real_person),
        ),
        TableRow::plain(
            "Real-person note [User-confirmed fact]",
            artwork_note(
                &fields.artwork_origin,
                fields.depicts_real_person,
                &fields.real_person_notes,
            ),
        ),
        TableRow::plain(
            "Depicts real event [User-confirmed fact]",
            artwork_answer(&fields.artwork_origin, fields.depicts_real_event),
        ),
        TableRow::plain(
            "Real-event note [User-confirmed fact]",
            artwork_note(
                &fields.artwork_origin,
                fields.depicts_real_event,
                &fields.real_event_notes,
            ),
        ),
        TableRow::plain(
            "Trademark/logo [User-confirmed fact]",
            artwork_answer(&fields.artwork_origin, fields.contains_trademark),
        ),
        TableRow::plain(
            "Trademark/logo note [User-confirmed fact]",
            artwork_note(
                &fields.artwork_origin,
                fields.contains_trademark,
                &fields.trademark_notes,
            ),
        ),
        TableRow::plain(
            "Disclosure applied [User-confirmed fact]",
            artwork_answer(&fields.artwork_origin, fields.disclosure_applied),
        ),
        TableRow::plain(
            "Disclosure text [User-confirmed fact]",
            if fields.disclosure_applied == Some(true) {
                documented(&fields.disclosure_text)
            } else {
                "N/A"
            },
        ),
    ];
    layout.table_rows(&rows, 62.0);
}

fn render_license_and_rights(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("H. License and rights evidence");
    let coverage = subscription_coverage(snapshot);
    let production_coverage = subscription_production_coverage(snapshot);
    let terms = snapshot
        .evidence
        .iter()
        .filter(|item| item.role == EvidenceRole::SunoTermsRights)
        .collect::<Vec<_>>();
    let timestamp_exists = snapshot
        .evidence
        .iter()
        .any(|item| item.role == EvidenceRole::ExternalTimestamp);
    layout.write_wrapped(
        &format!("Assigned subscription evidence jointly covers the production period: {production_coverage}; final-generation date: {coverage} [System verification]"),
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.6,
        BuiltinFont::HelveticaBold,
        1.3,
    );
    layout.y_mm -= 1.0;
    let mut rows = vec![
        TableRow::plain(
            "Terms evidence exists [System verification]",
            if terms.is_empty() { "NO" } else { "YES" },
        ),
        TableRow::plain(
            "Terms evidence not available [User-confirmed fact]",
            yes_no(snapshot.track.fields.suno_terms_evidence_not_available),
        ),
        TableRow::plain(
            "External timestamp evidence [System verification]",
            if timestamp_exists {
                "External timestamp evidence recorded"
            } else {
                "No external timestamp evidence recorded"
            },
        ),
    ];
    for (index, item) in snapshot
        .evidence
        .iter()
        .filter(|item| item.role == EvidenceRole::SubscriptionPayment)
        .enumerate()
    {
        rows.push(TableRow::mono(
            format!("Subscription evidence {} path", index + 1),
            &item.relative_path,
        ));
        rows.push(TableRow::plain(
            format!("Subscription evidence {} coverage start", index + 1),
            documented(item.coverage_start.as_deref().unwrap_or_default()),
        ));
        rows.push(TableRow::plain(
            format!("Subscription evidence {} coverage end", index + 1),
            documented(item.coverage_end.as_deref().unwrap_or_default()),
        ));
        rows.push(TableRow::mono(
            format!("Subscription evidence {} SHA-256", index + 1),
            item.sha256.as_deref().unwrap_or("Not recorded"),
        ));
    }
    for role in [
        EvidenceRole::ExternalAudioLicense,
        EvidenceRole::ThirdPartySampleLicense,
    ] {
        for item in snapshot.evidence.iter().filter(|item| item.role == role) {
            rows.push(TableRow::mono(
                format!("{} evidence", role.as_str()),
                &item.relative_path,
            ));
        }
    }
    for (index, item) in terms.iter().enumerate() {
        rows.push(TableRow::plain(
            format!("Terms document {} title", index + 1),
            documented(&item.metadata.document_title),
        ));
        rows.push(TableRow::plain(
            format!("Terms document {} provider/source", index + 1),
            documented(&item.metadata.provider),
        ));
        rows.push(TableRow::mono(
            format!("Terms document {} source URL", index + 1),
            documented(&item.metadata.source_url),
        ));
        rows.push(TableRow::plain(
            format!("Terms document {} retrieval date", index + 1),
            documented(&item.metadata.retrieval_date),
        ));
        rows.push(TableRow::plain(
            format!("Terms document {} effective date", index + 1),
            documented(&item.metadata.effective_date),
        ));
        rows.push(TableRow::plain(
            format!("Terms document {} factual note", index + 1),
            documented(&item.metadata.factual_note),
        ));
    }
    layout.table_rows(&rows, 72.0);
    layout.write_wrapped("Factual archive and coverage status only. No rights ownership, license validity, legality, or non-infringement conclusion is made.", LEFT_MM, RIGHT_MM - LEFT_MM, 7.2, BuiltinFont::Helvetica, 1.3);
}

fn push_documented_detail(rows: &mut Vec<TableRow>, label: &str, value: &str) {
    if !value.trim().is_empty() {
        rows.push(TableRow::plain(label, value));
    }
}

fn render_workflow(layout: &mut PdfLayout, steps: &[StepState], labels: &HashMap<&str, &str>) {
    layout.section_title("J.1 Configured workflow checks");
    layout.column_heading("Schritt", "Autoritativer Status / N/A-Grund", 63.0);
    for step in steps {
        let mut value = step_status(&step.status).to_owned();
        if step.status == StepStatus::NotApplicable {
            value.push_str(" | N/A-Grund: ");
            value.push_str(
                step.na_reason
                    .as_deref()
                    .filter(|reason| !reason.trim().is_empty())
                    .unwrap_or("Not documented"),
            );
        }
        layout.table_row(
            &TableRow::plain(
                labels
                    .get(step.id.as_str())
                    .copied()
                    .expect("validated workflow step label"),
                value,
            ),
            63.0,
        );
    }
}

fn render_evidence_register(layout: &mut PdfLayout, evidence: &[&EvidenceItem]) {
    layout.section_title("I. Evidence register");
    render_evidence_column_heading(layout);
    for (index, item) in evidence.iter().enumerate() {
        let digest = item
            .sha256
            .as_deref()
            .expect("validated certificate PDF evidence digest");
        let minimum_height = 16.0
            + estimated_row_height(&item.relative_path, 144.0, 6.4, BuiltinFont::Courier)
            + estimated_row_height(digest, 144.0, 6.4, BuiltinFont::Courier);
        if !layout.fits(minimum_height) && minimum_height <= layout.full_content_height() {
            layout.new_page();
            layout.continuation_title("Evidenzregister (Fortsetzung)");
            render_evidence_column_heading(layout);
        }

        layout.evidence_summary_row(
            index + 1,
            item.role.as_str(),
            item.provenance.as_str(),
            item.size_bytes,
        );
        layout.table_row(&TableRow::mono("Evidence ID", &item.id), 34.0);
        layout.table_row(&TableRow::plain("File name", &item.file_name), 34.0);
        layout.table_row(
            &TableRow::plain(
                "Original file name [Evidence-derived metadata]",
                documented(&item.metadata.original_file_name),
            ),
            56.0,
        );
        layout.table_row(&TableRow::mono("Relative path", &item.relative_path), 34.0);
        layout.table_row(&TableRow::mono("SHA-256", digest), 34.0);

        if !item.imported_at.trim().is_empty() {
            layout.table_row(&TableRow::mono("Imported at", &item.imported_at), 34.0);
        }
        if let Some(value) = nonempty(item.coverage_start.as_deref()) {
            layout.table_row(&TableRow::mono("Coverage start", value), 34.0);
        }
        if let Some(value) = nonempty(item.coverage_end.as_deref()) {
            layout.table_row(&TableRow::mono("Coverage end", value), 34.0);
        }
        if let Some(value) = nonempty(item.source_global_evidence_id.as_deref()) {
            layout.table_row(&TableRow::mono("Source global evidence ID", value), 45.0);
        }
        if let Some(value) = nonempty(item.derived_from_evidence_id.as_deref()) {
            layout.table_row(&TableRow::mono("Derived from evidence ID", value), 45.0);
        }
        if let Some(value) = nonempty(item.generator_version.as_deref()) {
            layout.table_row(&TableRow::mono("Generator version", value), 38.0);
        }
        if let Some(value) = nonempty(item.generated_disclosure_text.as_deref()) {
            layout.table_row(&TableRow::plain("Generated disclosure text", value), 45.0);
        }
        for (label, value, mono) in [
            (
                "Document title",
                item.metadata.document_title.as_str(),
                false,
            ),
            ("Provider/source", item.metadata.provider.as_str(), false),
            ("Source URL", item.metadata.source_url.as_str(), true),
            (
                "Retrieval date",
                item.metadata.retrieval_date.as_str(),
                false,
            ),
            (
                "Effective date",
                item.metadata.effective_date.as_str(),
                false,
            ),
            ("Factual note", item.metadata.factual_note.as_str(), false),
            (
                "External timestamp",
                item.metadata.external_timestamp.as_str(),
                true,
            ),
            (
                "Referenced hash",
                item.metadata.referenced_hash.as_str(),
                true,
            ),
            (
                "Referenced artifact",
                item.metadata.referenced_artifact.as_str(),
                true,
            ),
        ] {
            if !value.trim().is_empty() {
                let row = if mono {
                    TableRow::mono(label, value)
                } else {
                    TableRow::plain(label, value)
                };
                layout.table_row(&row, 45.0);
            }
        }
        layout.y_mm -= 1.8;
    }
}

fn render_evidence_column_heading(layout: &mut PdfLayout) {
    layout.ensure_space(6.0);
    let y = layout.y_mm - 2.5;
    layout.text_at(LEFT_MM + 1.0, y, "#", 6.5, BuiltinFont::HelveticaBold);
    layout.text_at(LEFT_MM + 12.0, y, "Role", 6.5, BuiltinFont::HelveticaBold);
    layout.text_at(
        LEFT_MM + 77.0,
        y,
        "Provenance",
        6.5,
        BuiltinFont::HelveticaBold,
    );
    layout.text_at(
        LEFT_MM + 130.0,
        y,
        "Size (bytes)",
        6.5,
        BuiltinFont::HelveticaBold,
    );
    layout.y_mm -= 4.0;
    layout.rule(LEFT_MM, RIGHT_MM, layout.y_mm, 0.45);
    layout.y_mm -= 1.0;
}

fn render_integrity_anchors(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("J. Integrity anchors");
    let release_wav =
        evidence_digest(snapshot.evidence, EvidenceRole::ReleaseWav).unwrap_or("Not documented");
    let final_artwork =
        evidence_digest(snapshot.evidence, EvidenceRole::FinalArtwork).unwrap_or("N/A");
    let open_blocking_deviations = snapshot
        .deviations
        .iter()
        .filter(|deviation| deviation.blocking && !deviation.resolved)
        .count();
    let rows = vec![
        TableRow::mono("Evidence file count", snapshot.evidence.len().to_string()),
        TableRow::mono("Release WAV SHA-256", release_wav),
        TableRow::mono("Final artwork SHA-256", final_artwork),
        TableRow::mono("SHA256SUMS.txt SHA-256", snapshot.sha256sums_sha256),
        TableRow::mono(
            "EVIDENCE_MANIFEST.json SHA-256",
            snapshot.evidence_manifest_sha256,
        ),
        TableRow::mono(
            "DOCUMENTATION_CERTIFICATE.md SHA-256",
            snapshot.markdown_certificate_sha256,
        ),
        TableRow::plain("Blocking deviations", open_blocking_deviations.to_string()),
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::mono("Finalization timestamp", snapshot.finalized_at),
        TableRow::mono(
            "Previous revision archives [System verification]",
            if snapshot.revision_references.is_empty() {
                "None recorded".into()
            } else {
                snapshot.revision_references.join(", ")
            },
        ),
        TableRow::plain("Final result", "DOCUMENTATION COMPLETE"),
    ];
    layout.table_rows(&rows, 54.0);
}

fn render_certificate_statement(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("J.2 Technical certificate statement");
    layout.write_wrapped(
        CERTIFICATE_STATEMENT,
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        8.0,
        BuiltinFont::Helvetica,
        1.35,
    );
    layout.y_mm -= 2.0;
    layout.write_wrapped(
        "Origin labels: User-confirmed fact / Evidence-derived metadata / System verification.",
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.2,
        BuiltinFont::HelveticaBold,
        1.3,
    );
    layout.y_mm -= 1.0;
    let rows = vec![
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::plain("Generated by", "Suno Documentation Manager"),
        TableRow::mono("Application version", env!("CARGO_PKG_VERSION")),
        TableRow::mono(
            "Workflow",
            format!(
                "{} / {}",
                snapshot.track.workflow_id, snapshot.track.workflow_version
            ),
        ),
        TableRow::mono("Finalized at", snapshot.finalized_at),
    ];
    layout.table_rows(&rows, 42.0);
}

fn evidence_digest<'a>(evidence: &'a [&'a EvidenceItem], role: EvidenceRole) -> Option<&'a str> {
    evidence
        .iter()
        .find(|item| item.role == role)
        .and_then(|item| item.sha256.as_deref())
}

fn documented(value: &str) -> &str {
    if value.trim().is_empty() {
        "Not documented"
    } else {
        value
    }
}

fn fact_origin_label(origin: FactOrigin) -> &'static str {
    match origin {
        FactOrigin::UserConfirmedFact => "User-confirmed fact",
        FactOrigin::EvidenceDerivedMetadata => "Evidence-derived metadata",
        FactOrigin::NotDocumented => "Not documented",
    }
}

fn yes_no_bool(value: bool) -> &'static str {
    if value {
        "YES"
    } else {
        "NO"
    }
}

fn evidence_original_file_name<'a>(
    evidence: &'a [&'a EvidenceItem],
    role: EvidenceRole,
) -> &'a str {
    evidence
        .iter()
        .find(|item| item.role == role)
        .map(|item| item.metadata.original_file_name.as_str())
        .filter(|value| !value.trim().is_empty())
        .unwrap_or("Not recorded")
}

fn evidence_relative_path<'a>(evidence: &'a [&'a EvidenceItem], role: EvidenceRole) -> &'a str {
    evidence
        .iter()
        .find(|item| item.role == role)
        .map(|item| item.relative_path.as_str())
        .unwrap_or("Not recorded")
}

fn applicable_note(answer: Option<bool>, note: &str) -> &str {
    match answer {
        Some(true) => documented(note),
        Some(false) => "N/A",
        None => "Not recorded",
    }
}

fn artwork_answer(origin: &str, answer: Option<bool>) -> &'static str {
    if origin == "none" {
        "N/A"
    } else {
        yes_no(answer)
    }
}

fn artwork_note<'a>(origin: &str, answer: Option<bool>, note: &'a str) -> &'a str {
    if origin == "none" {
        "N/A"
    } else {
        applicable_note(answer, note)
    }
}

fn branch_value(answer: Option<bool>, value: &str) -> &str {
    match answer {
        Some(true) => documented(value),
        Some(false) => "N/A",
        None => "Not recorded",
    }
}

fn subscription_coverage(snapshot: &CertificatePdfSnapshot<'_>) -> &'static str {
    let evidence = snapshot
        .evidence
        .iter()
        .map(|item| (*item).clone())
        .collect::<Vec<_>>();
    coverage_status_label(workflow::subscription_generation_coverage(
        snapshot.track,
        &evidence,
    ))
}

fn subscription_production_coverage(snapshot: &CertificatePdfSnapshot<'_>) -> &'static str {
    let evidence = snapshot
        .evidence
        .iter()
        .map(|item| (*item).clone())
        .collect::<Vec<_>>();
    coverage_status_label(workflow::subscription_production_coverage(
        snapshot.track,
        &evidence,
    ))
}

fn coverage_status_label(status: workflow::CoverageStatus) -> &'static str {
    match status {
        workflow::CoverageStatus::Yes => "YES",
        workflow::CoverageStatus::No => "NO",
        workflow::CoverageStatus::NotVerified => "NOT VERIFIED",
    }
}

fn nonempty(value: Option<&str>) -> Option<&str> {
    value.filter(|value| !value.trim().is_empty())
}

fn yes_no(value: Option<bool>) -> &'static str {
    match value {
        Some(true) => "Yes",
        Some(false) => "No",
        None => "Not documented",
    }
}

fn step_status(status: &StepStatus) -> &'static str {
    match status {
        StepStatus::NotRun => "NOT_RUN",
        StepStatus::Pass => "PASS",
        StepStatus::Fail => "FAIL",
        StepStatus::Blocked => "BLOCKED",
        StepStatus::NotApplicable => "N/A",
        StepStatus::NotVerified => "NOT_VERIFIED",
    }
}

struct TableRow {
    label: String,
    value: String,
    value_font: BuiltinFont,
    value_size_pt: f32,
}

impl TableRow {
    fn plain(label: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            value: value.into(),
            value_font: BuiltinFont::Helvetica,
            value_size_pt: 7.1,
        }
    }

    fn mono(label: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            value: value.into(),
            value_font: BuiltinFont::Courier,
            value_size_pt: 6.4,
        }
    }
}

struct PdfLayout {
    pages: Vec<Vec<Op>>,
    y_mm: f32,
}

impl PdfLayout {
    fn new() -> Self {
        Self {
            pages: vec![Vec::new()],
            y_mm: FIRST_PAGE_TOP_MM,
        }
    }

    fn current_ops(&mut self) -> &mut Vec<Op> {
        self.pages
            .last_mut()
            .expect("PDF layout always contains a page")
    }

    fn fits(&self, height_mm: f32) -> bool {
        self.y_mm - height_mm >= CONTENT_BOTTOM_MM
    }

    fn full_content_height(&self) -> f32 {
        CONTINUATION_TOP_MM - CONTENT_BOTTOM_MM
    }

    fn ensure_space(&mut self, height_mm: f32) {
        if !self.fits(height_mm) {
            self.new_page();
        }
    }

    fn new_page(&mut self) {
        self.pages.push(Vec::new());
        self.y_mm = CONTINUATION_TOP_MM;
        self.text_at(
            LEFT_MM,
            285.0,
            DOCUMENT_TITLE,
            6.8,
            BuiltinFont::HelveticaBold,
        );
        self.rule(LEFT_MM, RIGHT_MM, 281.5, 0.35);
    }

    fn continuation_title(&mut self, title: &str) {
        self.ensure_space(8.0);
        self.text_at(
            LEFT_MM,
            self.y_mm - 3.2,
            title,
            9.5,
            BuiltinFont::HelveticaBold,
        );
        self.y_mm -= 6.5;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.5);
        self.y_mm -= 1.5;
    }

    fn section_title(&mut self, title: &str) {
        self.ensure_space(13.0);
        self.y_mm -= 2.0;
        self.text_at(
            LEFT_MM,
            self.y_mm - 3.5,
            title,
            10.0,
            BuiltinFont::HelveticaBold,
        );
        self.y_mm -= 7.0;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.5);
        self.y_mm -= 1.5;
    }

    fn write_wrapped(
        &mut self,
        text: &str,
        x_mm: f32,
        width_mm: f32,
        size_pt: f32,
        font: BuiltinFont,
        line_factor: f32,
    ) {
        let lines = wrap_text(text, width_mm, size_pt, font);
        let line_height_mm = size_pt * 0.352_778 * line_factor;
        for line in lines {
            self.ensure_space(line_height_mm);
            let baseline = self.y_mm - size_pt * 0.352_778 * 0.82;
            self.text_at(x_mm, baseline, &line, size_pt, font);
            self.y_mm -= line_height_mm;
        }
    }

    fn table_rows(&mut self, rows: &[TableRow], label_width_mm: f32) {
        for row in rows {
            self.table_row(row, label_width_mm);
        }
    }

    fn table_row(&mut self, row: &TableRow, label_width_mm: f32) {
        let label_x = LEFT_MM + 1.0;
        let value_x = LEFT_MM + label_width_mm + 2.0;
        let value_width = RIGHT_MM - value_x - 1.0;
        let label_lines = wrap_text(
            &row.label,
            label_width_mm - 2.0,
            6.7,
            BuiltinFont::HelveticaBold,
        );
        let value_lines = wrap_text(&row.value, value_width, row.value_size_pt, row.value_font);
        let line_count = label_lines.len().max(value_lines.len()).max(1);
        let line_height_mm = 3.35;
        let total_height = line_count as f32 * line_height_mm + 2.0;
        if total_height <= self.full_content_height() && !self.fits(total_height) {
            self.new_page();
        }

        self.y_mm -= 0.8;
        for line_index in 0..line_count {
            let continued = if !self.fits(line_height_mm + 0.8) {
                self.new_page();
                self.text_at(
                    label_x,
                    self.y_mm - 2.45,
                    &format!("{} (Fortsetzung)", row.label),
                    6.7,
                    BuiltinFont::HelveticaBold,
                );
                true
            } else {
                false
            };
            let baseline = self.y_mm - 2.45;
            if !continued {
                if let Some(line) = label_lines.get(line_index) {
                    self.text_at(label_x, baseline, line, 6.7, BuiltinFont::HelveticaBold);
                }
            }
            if let Some(line) = value_lines.get(line_index) {
                self.text_at(value_x, baseline, line, row.value_size_pt, row.value_font);
            }
            self.y_mm -= line_height_mm;
        }
        self.y_mm -= 0.4;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.2);
        self.y_mm -= 0.8;
    }

    fn column_heading(&mut self, left: &str, right: &str, label_width_mm: f32) {
        self.ensure_space(6.0);
        let y = self.y_mm - 2.5;
        self.text_at(LEFT_MM + 1.0, y, left, 6.5, BuiltinFont::HelveticaBold);
        self.text_at(
            LEFT_MM + label_width_mm + 2.0,
            y,
            right,
            6.5,
            BuiltinFont::HelveticaBold,
        );
        self.y_mm -= 4.0;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.45);
        self.y_mm -= 1.0;
    }

    fn evidence_summary_row(
        &mut self,
        index: usize,
        role: &str,
        provenance: &str,
        size_bytes: u64,
    ) {
        self.ensure_space(6.0);
        let y = self.y_mm - 2.5;
        self.text_at(
            LEFT_MM + 1.0,
            y,
            &index.to_string(),
            6.4,
            BuiltinFont::CourierBold,
        );
        self.text_at(LEFT_MM + 12.0, y, role, 6.4, BuiltinFont::Courier);
        self.text_at(LEFT_MM + 77.0, y, provenance, 6.4, BuiltinFont::Courier);
        self.text_at(
            LEFT_MM + 130.0,
            y,
            &size_bytes.to_string(),
            6.4,
            BuiltinFont::Courier,
        );
        self.y_mm -= 4.0;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.25);
        self.y_mm -= 0.7;
    }

    fn text_at(&mut self, x_mm: f32, y_mm: f32, text: &str, size_pt: f32, font: BuiltinFont) {
        self.current_ops().extend([
            Op::StartTextSection,
            Op::SetTextCursor {
                pos: Point::new(Mm(x_mm), Mm(y_mm)),
            },
            Op::SetFont {
                font: PdfFontHandle::Builtin(font),
                size: Pt(size_pt),
            },
            Op::ShowText {
                items: vec![TextItem::Text(text.to_owned())],
            },
            Op::EndTextSection,
        ]);
    }

    fn rule(&mut self, from_x_mm: f32, to_x_mm: f32, y_mm: f32, thickness_pt: f32) {
        self.current_ops().extend([
            Op::SaveGraphicsState,
            Op::SetOutlineColor {
                col: Color::Rgb(Rgb {
                    r: 0.48,
                    g: 0.48,
                    b: 0.48,
                    icc_profile: None,
                }),
            },
            Op::SetOutlineThickness {
                pt: Pt(thickness_pt),
            },
            Op::DrawLine {
                line: Line {
                    points: vec![
                        LinePoint {
                            p: Point::new(Mm(from_x_mm), Mm(y_mm)),
                            bezier: false,
                        },
                        LinePoint {
                            p: Point::new(Mm(to_x_mm), Mm(y_mm)),
                            bezier: false,
                        },
                    ],
                    is_closed: false,
                },
            },
            Op::RestoreGraphicsState,
        ]);
    }

    fn into_pages(mut self, certificate_id: &str) -> Vec<PdfPage> {
        let page_count = self.pages.len();
        for (index, ops) in self.pages.iter_mut().enumerate() {
            append_rule(ops, LEFT_MM, RIGHT_MM, FOOTER_RULE_Y_MM, 0.35);
            append_text(
                ops,
                LEFT_MM,
                FOOTER_TEXT_Y_MM,
                &format!("Certificate ID: {}", certificate_id),
                5.8,
                BuiltinFont::Helvetica,
            );
            append_text(
                ops,
                166.0,
                FOOTER_TEXT_Y_MM,
                &format!("Seite {} / {}", index + 1, page_count),
                6.5,
                BuiltinFont::Helvetica,
            );
        }
        self.pages
            .into_iter()
            .map(|ops| PdfPage::new(Mm(PAGE_WIDTH_MM), Mm(PAGE_HEIGHT_MM), ops))
            .collect()
    }
}

fn append_text(
    ops: &mut Vec<Op>,
    x_mm: f32,
    y_mm: f32,
    text: &str,
    size_pt: f32,
    font: BuiltinFont,
) {
    ops.extend([
        Op::StartTextSection,
        Op::SetTextCursor {
            pos: Point::new(Mm(x_mm), Mm(y_mm)),
        },
        Op::SetFont {
            font: PdfFontHandle::Builtin(font),
            size: Pt(size_pt),
        },
        Op::ShowText {
            items: vec![TextItem::Text(text.to_owned())],
        },
        Op::EndTextSection,
    ]);
}

fn append_rule(ops: &mut Vec<Op>, from_x_mm: f32, to_x_mm: f32, y_mm: f32, thickness_pt: f32) {
    ops.extend([
        Op::SaveGraphicsState,
        Op::SetOutlineColor {
            col: Color::Rgb(Rgb {
                r: 0.48,
                g: 0.48,
                b: 0.48,
                icc_profile: None,
            }),
        },
        Op::SetOutlineThickness {
            pt: Pt(thickness_pt),
        },
        Op::DrawLine {
            line: Line {
                points: vec![
                    LinePoint {
                        p: Point::new(Mm(from_x_mm), Mm(y_mm)),
                        bezier: false,
                    },
                    LinePoint {
                        p: Point::new(Mm(to_x_mm), Mm(y_mm)),
                        bezier: false,
                    },
                ],
                is_closed: false,
            },
        },
        Op::RestoreGraphicsState,
    ]);
}

fn estimated_row_height(text: &str, width_mm: f32, size_pt: f32, font: BuiltinFont) -> f32 {
    wrap_text(text, width_mm, size_pt, font).len() as f32 * 3.35 + 2.0
}

fn wrap_text(text: &str, width_mm: f32, size_pt: f32, font: BuiltinFont) -> Vec<String> {
    let normalized = text
        .chars()
        .map(|character| match character {
            '\n' => '\n',
            '\t' => ' ',
            character if character.is_control() => ' ',
            character => character,
        })
        .collect::<String>();

    let mut result = Vec::new();
    for paragraph in normalized.split('\n') {
        let mut remaining = paragraph.chars().collect::<Vec<_>>();
        if remaining.is_empty() {
            result.push(String::new());
            continue;
        }
        while !remaining.is_empty() {
            let mut used_width_mm = 0.0;
            let mut maximum_fit = 0;
            let mut last_wrap_opportunity = None;
            for (index, character) in remaining.iter().copied().enumerate() {
                let character_width_mm =
                    measure_text_width_mm(&character.to_string(), size_pt, font);
                if maximum_fit > 0 && used_width_mm + character_width_mm > width_mm {
                    break;
                }
                used_width_mm += character_width_mm;
                maximum_fit = index + 1;
                if is_wrap_opportunity(character) {
                    last_wrap_opportunity = Some(maximum_fit);
                }
                if used_width_mm > width_mm {
                    break;
                }
            }
            if maximum_fit >= remaining.len() && used_width_mm <= width_mm {
                result.push(remaining.iter().collect());
                break;
            }
            let minimum_clean_break = maximum_fit / 2;
            let break_at = last_wrap_opportunity
                .filter(|index| *index >= minimum_clean_break)
                .unwrap_or(maximum_fit.max(1));
            result.push(remaining[..break_at].iter().collect());
            remaining.drain(..break_at);
        }
    }
    if result.is_empty() {
        result.push(String::new());
    }
    result
}

fn measure_text_width_mm(text: &str, size_pt: f32, font: BuiltinFont) -> f32 {
    let metrics = builtin_font_metrics(font);
    let units_per_em = f32::from(metrics.units_per_em.max(1));
    let width_in_em = text
        .chars()
        .map(|character| {
            metrics
                .lookup_glyph_index(character as u32)
                .and_then(|glyph| metrics.get_glyph_width(glyph))
                .map(f32::from)
                .unwrap_or(units_per_em)
                / units_per_em
        })
        .sum::<f32>();
    width_in_em * size_pt * 0.352_778
}

fn builtin_font_metrics(font: BuiltinFont) -> &'static ParsedFont {
    static HELVETICA: OnceLock<ParsedFont> = OnceLock::new();
    static HELVETICA_BOLD: OnceLock<ParsedFont> = OnceLock::new();
    static COURIER: OnceLock<ParsedFont> = OnceLock::new();
    static COURIER_BOLD: OnceLock<ParsedFont> = OnceLock::new();

    match font {
        BuiltinFont::Helvetica | BuiltinFont::HelveticaOblique => HELVETICA.get_or_init(|| {
            BuiltinFont::Helvetica
                .get_parsed_font()
                .expect("built-in Helvetica metrics")
        }),
        BuiltinFont::HelveticaBold | BuiltinFont::HelveticaBoldOblique => HELVETICA_BOLD
            .get_or_init(|| {
                BuiltinFont::HelveticaBold
                    .get_parsed_font()
                    .expect("built-in Helvetica Bold metrics")
            }),
        BuiltinFont::Courier | BuiltinFont::CourierOblique => COURIER.get_or_init(|| {
            BuiltinFont::Courier
                .get_parsed_font()
                .expect("built-in Courier metrics")
        }),
        BuiltinFont::CourierBold | BuiltinFont::CourierBoldOblique => {
            COURIER_BOLD.get_or_init(|| {
                BuiltinFont::CourierBold
                    .get_parsed_font()
                    .expect("built-in Courier Bold metrics")
            })
        }
        _ => HELVETICA.get_or_init(|| {
            BuiltinFont::Helvetica
                .get_parsed_font()
                .expect("built-in Helvetica metrics")
        }),
    }
}

fn is_wrap_opportunity(character: char) -> bool {
    character.is_whitespace() || matches!(character, '/' | '\\' | '-' | '_' | '.' | ':' | ';' | ',')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{
        CertificateState, DocumentState, EvidenceProvenance, IntegrityState, TrackFields,
        TrackLibraryPlacement, TrackStatus,
    };

    const CERTIFICATE_ID: &str = "SUNODM-CERT-2026-0001";
    const DIGEST_A: &str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    const DIGEST_B: &str = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    const DIGEST_C: &str = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";

    struct Fixture {
        track: TrackRecord,
        profile: Profile,
        steps: Vec<StepState>,
        evidence: Vec<EvidenceItem>,
        deviations: Vec<BlockingDeviation>,
        revision_references: Vec<String>,
    }

    impl Fixture {
        fn new(evidence_count: usize) -> Self {
            let workflow_config = workflow::config().expect("workflow fixture");
            let profile = Profile {
                artist_name: "Künstlerin Änne Öster".into(),
                suno_profile_name: "Studio Überklang".into(),
                suno_handle: "@ueberklang".into(),
                suno_plan: "Pro".into(),
                subscription_start_date: "2025-01-01".into(),
                ..Profile::default()
            };
            let fields = TrackFields {
                title: "Größe & Präzision".into(),
                production_start_date: "2026-01-02".into(),
                production_end_date: "2026-01-03".into(),
                final_export_date: "2026-01-04".into(),
                suno_model: "v4.5".into(),
                suno_project_url: "https://suno.example/project/fixture".into(),
                suno_plan_at_creation: "Pro".into(),
                lyrics_source: "mixed".into(),
                external_audio_uploaded: Some(false),
                own_audio_uploaded: Some(false),
                code_based_generation: Some(true),
                third_party_samples_uploaded: Some(false),
                human_editing_performed: Some(true),
                human_editing_details: "Timing and cuts; EQ; Mixing".into(),
                post_export_editing_performed: Some(false),
                artwork_origin: "human".into(),
                ..TrackFields::default()
            };
            let track = TrackRecord {
                id: "track-fixture".into(),
                relative_path: ".".into(),
                status: TrackStatus::Ready,
                workflow_id: workflow_config.id.clone(),
                workflow_version: workflow_config.version.clone(),
                profile_snapshot: profile.clone(),
                library: TrackLibraryPlacement::default(),
                field_origins: Default::default(),
                fields,
                documents: DocumentState::default(),
                integrity: IntegrityState::default(),
                certificate: CertificateState::default(),
                created_at: "2026-01-02T00:00:00Z".into(),
                updated_at: "2026-01-04T00:00:00Z".into(),
                legacy: false,
            };
            let steps = workflow_config
                .steps
                .into_iter()
                .map(|step| StepState {
                    id: step.id.clone(),
                    status: if step.id == "ai_transparency" {
                        StepStatus::NotApplicable
                    } else {
                        StepStatus::Pass
                    },
                    na_reason: (step.id == "ai_transparency")
                        .then(|| "Kein AI-Artwork dokumentiert".into()),
                    updated_at: Some("2026-01-04T00:00:00Z".into()),
                })
                .collect();
            let evidence = (0..evidence_count).map(evidence_item).collect();
            Self {
                track,
                profile,
                steps,
                evidence,
                deviations: Vec::new(),
                revision_references: Vec::new(),
            }
        }

        fn generate(&self) -> Vec<u8> {
            self.generate_result()
                .expect("generate fixture certificate PDF")
        }

        fn generate_result(&self) -> Result<Vec<u8>> {
            let evidence_refs = self.evidence.iter().collect::<Vec<_>>();
            let automation = workflow::automation_summary(&self.track, &self.evidence);
            generate_pdf(&CertificatePdfSnapshot {
                track: &self.track,
                automation: &automation,
                profile: &self.profile,
                steps: &self.steps,
                evidence: &evidence_refs,
                deviations: &self.deviations,
                revision_references: &self.revision_references,
                certificate_id: CERTIFICATE_ID,
                finalized_at: "2026-01-04T12:34:56Z",
                certificate_version: "1",
                sha256sums_sha256: DIGEST_A,
                evidence_manifest_sha256: DIGEST_B,
                markdown_certificate_sha256: DIGEST_C,
            })
        }
    }

    fn evidence_item(index: usize) -> EvidenceItem {
        let role = match index % 3 {
            0 => EvidenceRole::ReleaseWav,
            1 => EvidenceRole::SourceCodeFile,
            _ => EvidenceRole::SunoScreenshot,
        };
        EvidenceItem {
            id: format!("evidence-{index:04}"),
            role,
            file_name: format!("evidence-{index:04}.dat"),
            relative_path: format!("02_SUNO/evidence-{index:04}.dat"),
            sha256: Some(format!("{value:064x}", value = index + 1)),
            size_bytes: 1_024 + index as u64,
            imported_at: "2026-01-04T10:00:00Z".into(),
            verified: true,
            verification_error: None,
            source_global_evidence_id: index
                .is_multiple_of(4)
                .then(|| format!("global-{index:04}")),
            coverage_start: index.is_multiple_of(5).then(|| "2026-01-01".into()),
            coverage_end: index.is_multiple_of(5).then(|| "2026-01-31".into()),
            provenance: if index.is_multiple_of(4) {
                EvidenceProvenance::GlobalCopy
            } else {
                EvidenceProvenance::ManagedCopy
            },
            derived_from_evidence_id: index
                .is_multiple_of(6)
                .then(|| format!("source-{index:04}")),
            generator_version: index.is_multiple_of(7).then(|| "generator-1.0".into()),
            generated_disclosure_text: None,
            metadata: Default::default(),
        }
    }

    fn parse_text(bytes: &[u8]) -> (PdfDocument, String) {
        let mut warnings = Vec::new();
        let document = PdfDocument::parse(bytes, &PdfParseOptions::default(), &mut warnings)
            .expect("parse generated certificate PDF");
        assert!(
            warnings
                .iter()
                .all(|warning| warning.severity != PdfParseErrorSeverity::Error),
            "parser errors: {warnings:?}"
        );
        let text = document
            .extract_text()
            .into_iter()
            .flatten()
            .collect::<Vec<_>>()
            .join("\n");
        (document, text)
    }

    #[test]
    fn generates_parseable_pdf_with_identity_full_hash_and_german_text() {
        let bytes = Fixture::new(1).generate();
        assert!(bytes.starts_with(b"%PDF-"));
        validate_pdf_bytes(&bytes).expect("valid generated bytes");

        let (document, text) = parse_text(&bytes);
        assert!(!document.pages.is_empty());
        assert!(text.contains("Größe & Präzision"));
        assert!(text.contains("Künstlerin Änne Öster"));
        assert!(text.contains(CERTIFICATE_ID));
        assert!(text.contains(DIGEST_A));
        assert!(text.contains(&format!("{value:064x}", value = 1)));
        assert!(text.contains("Kein AI-Artwork dokumentiert"));
    }

    #[test]
    fn renders_clean_instrumental_lyrics_statement_and_scope_boundary() {
        let mut fixture = Fixture::new(1);
        fixture.track.fields.instrumental_track = Some(true);
        fixture.track.fields.lyrics_source = "instrumental".into();
        fixture.track.fields.lyrics_text.clear();
        fixture.track.fields.human_editing_performed = Some(false);
        fixture.track.fields.human_editing_details.clear();
        let (_, text) = parse_text(&fixture.generate());
        assert!(text.contains("Lyrics: N/A – instrumental track"));
        assert!(text.contains("does not confirm authorship"));
        assert!(!text.contains("Commercial rights confirmed"));
    }

    #[test]
    fn omits_retired_generation_identifiers_and_time_from_pdf() {
        let mut fixture = Fixture::new(1);
        fixture.track.fields.suno_project_version_id = "legacy-project-version".into();
        fixture.track.fields.suno_final_generation_id = "legacy-generation-id".into();
        fixture.track.fields.suno_final_generation_time = "14:35".into();

        let (_, text) = parse_text(&fixture.generate());
        assert!(!text.contains("Project/version ID"));
        assert!(!text.contains("Final generation ID"));
        assert!(!text.contains("Final generation time"));
        assert!(!text.contains("legacy-project-version"));
        assert!(!text.contains("legacy-generation-id"));
        assert!(!text.contains("14:35"));
    }

    #[test]
    fn renders_suno_automation_with_evidence_derived_id_but_without_raw_timestamp() {
        let mut fixture = Fixture::new(1);
        fixture.track.fields.suno_final_generation_date = "2026-08-17".into();
        let release_hash = fixture.evidence[0]
            .sha256
            .clone()
            .expect("release fixture digest");
        let mut suno = evidence_item(42);
        suno.role = EvidenceRole::SunoFinalExport;
        suno.relative_path = "02_SUNO/suno-final.wav".into();
        suno.sha256 = Some(release_hash.clone());
        suno.metadata.suno_studio_detected = true;
        suno.metadata.suno_created_timestamp = "2026-08-17T06:38:06Z".into();
        suno.metadata.suno_created_date = "2026-08-17".into();
        suno.metadata.suno_id = "6c8a40fd-32bf-4c7b-ab59-23579ff95828".into();
        suno.metadata.suno_raw_metadata = "made with suno studio; created=2026-08-17T06:38:06Z; id=6c8a40fd-32bf-4c7b-ab59-23579ff95828".into();
        fixture.track.field_origins.suno_final_generation_date =
            Some(crate::model::EvidenceDerivedField {
                value: "2026-08-17".into(),
                original_value: "2026-08-17T06:38:06Z".into(),
                evidence_id: suno.id.clone(),
                evidence_sha256: release_hash,
            });
        fixture.evidence.push(suno);
        fixture
            .evidence
            .sort_by(|left, right| left.relative_path.cmp(&right.relative_path));

        let (_, text) = parse_text(&fixture.generate());

        assert!(text.contains("Final Suno generation"));
        assert!(text.contains("2026-08-17"));
        assert!(text.contains("Evidence-derived metadata"));
        assert!(text.contains("Suno Studio metadata detected"));
        assert!(text.contains("Release identical to Suno final export"));
        assert!(!text.contains("2026-08-17T06:38:06Z"));
        assert!(text.contains("6c8a40fd-32bf-4c7b-ab59-23579ff95828"));
    }

    #[test]
    fn renders_terms_and_external_timestamp_as_factual_local_evidence() {
        let mut fixture = Fixture::new(1);
        let mut terms = evidence_item(10);
        terms.role = EvidenceRole::SunoTermsRights;
        terms.relative_path = "04_LICENSES/suno-terms.pdf".into();
        terms.metadata.document_title = "Archived Suno Terms".into();
        terms.metadata.provider = "Suno".into();
        terms.metadata.source_url = "https://suno.example/terms".into();
        terms.metadata.retrieval_date = "2026-01-03".into();
        let mut timestamp = evidence_item(11);
        timestamp.role = EvidenceRole::ExternalTimestamp;
        timestamp.relative_path = "03_DOCUMENTATION/timestamp.pdf".into();
        timestamp.metadata.provider = "Example Timestamp Issuer".into();
        timestamp.metadata.external_timestamp = "2026-01-04T12:00:00Z".into();
        timestamp.metadata.referenced_hash = DIGEST_A.into();
        timestamp.metadata.referenced_artifact = "EVIDENCE_MANIFEST.json".into();
        fixture.evidence.extend([terms, timestamp]);
        fixture
            .evidence
            .sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
        let (_, text) = parse_text(&fixture.generate());
        assert!(text.contains("Archived Suno Terms"));
        assert!(text.contains("Example Timestamp Issuer"));
        assert!(text.contains("External timestamp evidence recorded"));
        assert!(!text.contains("qualified timestamp"));
    }

    #[test]
    fn identical_snapshot_produces_identical_pdf_bytes() {
        let fixture = Fixture::new(4);
        assert_eq!(fixture.generate(), fixture.generate());
    }

    #[test]
    fn renders_multiple_evidence_items_and_optional_manifest_fields() {
        let mut fixture = Fixture::new(4);
        fixture
            .revision_references
            .push(".archive/revisions/revision-fixture".into());
        let bytes = fixture.generate();
        let (_, text) = parse_text(&bytes);
        assert!(text.contains("02_SUNO/evidence-0000.dat"));
        assert!(text.contains("02_SUNO/evidence-0001.dat"));
        assert!(text.contains("02_SUNO/evidence-0002.dat"));
        assert!(text.contains("release_wav"));
        assert!(text.contains("source_code_file"));
        assert!(text.contains("global-0000"));
        assert!(text.contains("generator-1.0"));
        assert!(text.contains(".archive/revisions/revision-fixture"));
    }

    #[test]
    fn large_evidence_register_paginates() {
        let bytes = Fixture::new(80).generate();
        let (document, text) = parse_text(&bytes);
        assert!(document.pages.len() > 1);
        assert!(text.contains("02_SUNO/evidence-0079.dat"));
        assert!(text.contains(&format!("Seite {} / {}", 1, document.pages.len())));
        assert!(text.contains(&format!(
            "Seite {} / {}",
            document.pages.len(),
            document.pages.len()
        )));
    }

    #[test]
    fn long_evidence_paths_wrap_without_truncation() {
        let mut fixture = Fixture::new(1);
        let long_path = format!(
            "02_SUNO/{components}evidence.wav",
            components = "nested_component_".repeat(25)
        );
        fixture.evidence[0].relative_path = long_path.clone();
        let bytes = fixture.generate();
        let (_, text) = parse_text(&bytes);
        let compact_text = text
            .chars()
            .filter(|character| !character.is_whitespace())
            .collect::<String>();
        assert!(compact_text.contains(&long_path));
    }

    #[test]
    fn conditional_details_are_normalized_before_rendering() {
        let mut fixture = Fixture::new(1);
        fixture.track.fields.external_audio_uploaded = Some(false);
        fixture.track.fields.external_audio_source = "stale hidden source".into();
        fixture.track.fields.external_audio_ownership = "stale hidden statement".into();
        let bytes = fixture.generate();
        let (_, text) = parse_text(&bytes);
        assert!(!text.contains("stale hidden source"));
        assert!(!text.contains("stale hidden statement"));
    }

    #[test]
    fn rejects_non_win_ansi_snapshot_text_instead_of_replacing_it() {
        let mut fixture = Fixture::new(1);
        fixture.track.fields.title = "Tokyo 東京".into();
        let error = fixture
            .generate_result()
            .expect_err("unsupported built-in-font character");
        assert!(error.to_string().contains("U+6771"));
    }

    #[test]
    fn rejects_incomplete_statuses_and_open_blocking_deviations() {
        let mut fixture = Fixture::new(1);
        fixture.steps[0].status = StepStatus::Fail;
        assert!(fixture.generate_result().is_err());

        fixture.steps[0].status = StepStatus::Pass;
        fixture.deviations.push(BlockingDeviation {
            id: "deviation-1".into(),
            title: "Open blocker".into(),
            description: "Unresolved technical deviation".into(),
            blocking: true,
            resolved: false,
            created_at: "2026-01-04T00:00:00Z".into(),
            resolved_at: None,
        });
        assert!(fixture.generate_result().is_err());
    }

    #[test]
    fn wrapping_uses_builtin_font_metrics_for_wide_glyphs() {
        let width_mm = 24.0;
        let lines = wrap_text(&"W".repeat(100), width_mm, 8.0, BuiltinFont::HelveticaBold);
        assert!(lines.len() > 1);
        assert!(lines.iter().all(|line| {
            measure_text_width_mm(line, 8.0, BuiltinFont::HelveticaBold) <= width_mm + 0.001
        }));
        assert_eq!(lines.concat(), "W".repeat(100));
    }

    #[test]
    fn rejects_non_pdf_staged_bytes() {
        assert!(validate_pdf_bytes(b"not a PDF").is_err());
    }

    #[test]
    fn rejects_unsorted_or_unverified_evidence_without_reordering_or_filtering() {
        let mut fixture = Fixture::new(2);
        fixture.evidence.swap(0, 1);
        {
            let evidence_refs = fixture.evidence.iter().collect::<Vec<_>>();
            let automation = workflow::automation_summary(&fixture.track, &fixture.evidence);
            let snapshot = CertificatePdfSnapshot {
                track: &fixture.track,
                automation: &automation,
                profile: &fixture.profile,
                steps: &fixture.steps,
                evidence: &evidence_refs,
                deviations: &fixture.deviations,
                revision_references: &fixture.revision_references,
                certificate_id: CERTIFICATE_ID,
                finalized_at: "2026-01-04T12:34:56Z",
                certificate_version: "1",
                sha256sums_sha256: DIGEST_A,
                evidence_manifest_sha256: DIGEST_B,
                markdown_certificate_sha256: DIGEST_C,
            };
            assert!(generate_pdf(&snapshot).is_err());
        }

        fixture
            .evidence
            .sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
        fixture.evidence[0].verified = false;
        let evidence_refs = fixture.evidence.iter().collect::<Vec<_>>();
        let automation = workflow::automation_summary(&fixture.track, &fixture.evidence);
        let snapshot = CertificatePdfSnapshot {
            track: &fixture.track,
            automation: &automation,
            profile: &fixture.profile,
            steps: &fixture.steps,
            evidence: &evidence_refs,
            deviations: &fixture.deviations,
            revision_references: &fixture.revision_references,
            certificate_id: CERTIFICATE_ID,
            finalized_at: "2026-01-04T12:34:56Z",
            certificate_version: "1",
            sha256sums_sha256: DIGEST_A,
            evidence_manifest_sha256: DIGEST_B,
            markdown_certificate_sha256: DIGEST_C,
        };
        assert!(generate_pdf(&snapshot).is_err());
    }
}
