use crate::error::{AppError, Result};
use crate::model::{
    BlockingDeviation, EvidenceItem, EvidenceRole, Profile, StepState, StepStatus, TrackRecord,
};
use crate::workflow;
use printpdf::{
    BuiltinFont, Color, Line, LinePoint, Mm, Op, ParsedFont, PdfDocument, PdfFontHandle, PdfPage,
    PdfParseErrorSeverity, PdfParseOptions, PdfSaveOptions, Point, Pt, Rgb, TextItem,
};
use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

const DOCUMENT_TITLE: &str = "SunoDM – Technischer Dokumentations- und Evidenznachweis";
const GENERATED_BY: &str = "Generated by Suno Documentation Manager";
const CERTIFICATE_STATEMENT: &str = "Dieses Dokument wurde durch Suno Documentation Manager aus dem finalisierten Track-Snapshot erzeugt. Es dokumentiert die zum Zeitpunkt der Finalisierung erfassten Daten, Evidenzdateien, Workflow-Ergebnisse und kryptografischen Integritätswerte.";

const PAGE_WIDTH_MM: f32 = 210.0;
const PAGE_HEIGHT_MM: f32 = 297.0;
const LEFT_MM: f32 = 16.0;
const RIGHT_MM: f32 = 194.0;
const FIRST_PAGE_TOP_MM: f32 = 282.0;
const CONTINUATION_TOP_MM: f32 = 276.0;
const CONTENT_BOTTOM_MM: f32 = 21.0;
const FOOTER_RULE_Y_MM: f32 = 16.0;
const FOOTER_TEXT_Y_MM: f32 = 10.5;

/// The immutable, finalized data used to render a documentation certificate PDF.
///
/// `steps` is authoritative and is rendered in exactly the supplied order. `evidence` must be
/// the already filtered and `relative_path`-sorted slice used for the finalized evidence
/// manifest. The renderer validates those invariants but deliberately does not re-evaluate,
/// filter, or sort either slice.
pub struct CertificatePdfSnapshot<'a> {
    pub track: &'a TrackRecord,
    pub profile: &'a Profile,
    pub steps: &'a [StepState],
    pub evidence: &'a [&'a EvidenceItem],
    pub deviations: &'a [BlockingDeviation],
    pub certificate_id: &'a str,
    pub finalized_at: &'a str,
    pub certificate_version: &'a str,
    pub sha256sums_sha256: &'a str,
    pub evidence_manifest_sha256: &'a str,
    pub markdown_certificate_sha256: &'a str,
}

/// Render an A4, multi-page technical certificate from a finalized snapshot.
pub fn generate_pdf(snapshot: &CertificatePdfSnapshot<'_>) -> Result<Vec<u8>> {
    let workflow_config = validate_snapshot(snapshot)?;
    let step_labels = workflow_config
        .steps
        .iter()
        .map(|step| (step.id.as_str(), step.name.as_str()))
        .collect::<HashMap<_, _>>();

    let mut layout = PdfLayout::new();
    render_document_title(&mut layout);
    render_header_metadata(&mut layout, snapshot);
    render_track_data(&mut layout, snapshot);
    render_sources_and_generation(&mut layout, snapshot);
    render_workflow(&mut layout, snapshot.steps, &step_labels);
    render_evidence_register(&mut layout, snapshot.evidence);
    render_integrity_anchors(&mut layout, snapshot);
    render_certificate_statement(&mut layout, snapshot);

    let pages = layout.into_pages();
    let mut document = PdfDocument::new(DOCUMENT_TITLE);
    document.metadata.info.author = snapshot.profile.artist_name.clone();
    document.metadata.info.creator = GENERATED_BY.to_owned();
    document.metadata.info.producer = GENERATED_BY.to_owned();
    document.metadata.info.subject =
        "Finalized technical documentation, evidence, and integrity snapshot".to_owned();
    document.metadata.info.identifier = snapshot.certificate_id.to_owned();
    document.metadata.info.keywords = vec![
        "SunoDM".to_owned(),
        "documentation".to_owned(),
        "evidence".to_owned(),
        "SHA-256".to_owned(),
    ];
    document.with_pages(pages);

    let mut warnings = Vec::new();
    let bytes = document.save(&PdfSaveOptions::default(), &mut warnings);
    if let Some(warning) = warnings
        .iter()
        .find(|warning| warning.severity == PdfParseErrorSeverity::Error)
    {
        return Err(AppError::Data(format!(
            "Certificate PDF serialization failed: {}",
            warning.msg
        )));
    }
    validate_pdf_bytes(&bytes)?;
    Ok(bytes)
}

/// Parse staged PDF bytes and reject malformed or empty documents before publication.
pub fn validate_pdf_bytes(bytes: &[u8]) -> Result<()> {
    if !bytes.starts_with(b"%PDF-") {
        return Err(AppError::Validation(
            "Generated certificate PDF has no valid PDF header.".into(),
        ));
    }

    let mut warnings = Vec::new();
    let document =
        PdfDocument::parse(bytes, &PdfParseOptions::default(), &mut warnings).map_err(|error| {
            AppError::Validation(format!(
                "Generated certificate PDF cannot be parsed: {error}"
            ))
        })?;
    if document.pages.is_empty() {
        return Err(AppError::Validation(
            "Generated certificate PDF contains no pages.".into(),
        ));
    }
    if let Some(warning) = warnings
        .iter()
        .find(|warning| warning.severity == PdfParseErrorSeverity::Error)
    {
        return Err(AppError::Validation(format!(
            "Generated certificate PDF contains an invalid operation: {}",
            warning.msg
        )));
    }
    Ok(())
}

fn validate_snapshot(snapshot: &CertificatePdfSnapshot<'_>) -> Result<workflow::WorkflowConfig> {
    for (label, value) in [
        ("certificate ID", snapshot.certificate_id),
        ("finalization timestamp", snapshot.finalized_at),
        ("certificate version", snapshot.certificate_version),
    ] {
        if value.trim().is_empty() {
            return Err(AppError::Data(format!(
                "Certificate PDF snapshot has no {label}."
            )));
        }
    }
    for (label, digest) in [
        ("SHA256SUMS.txt", snapshot.sha256sums_sha256),
        ("EVIDENCE_MANIFEST.json", snapshot.evidence_manifest_sha256),
        (
            "DOCUMENTATION_CERTIFICATE.md",
            snapshot.markdown_certificate_sha256,
        ),
    ] {
        validate_sha256(label, digest)?;
    }

    if snapshot
        .evidence
        .windows(2)
        .any(|items| items[0].relative_path > items[1].relative_path)
    {
        return Err(AppError::Data(
            "Certificate PDF evidence is not sorted by relative path.".into(),
        ));
    }
    for item in snapshot.evidence {
        if !item.verified || item.verification_error.is_some() {
            return Err(AppError::Data(format!(
                "Certificate PDF evidence is not verified: {}",
                item.relative_path
            )));
        }
        let digest = item.sha256.as_deref().ok_or_else(|| {
            AppError::Data(format!(
                "Certificate PDF evidence has no SHA-256: {}",
                item.relative_path
            ))
        })?;
        validate_sha256(&item.relative_path, digest)?;
    }

    let config = workflow::config()?;
    if snapshot.track.workflow_id != config.id || snapshot.track.workflow_version != config.version
    {
        return Err(AppError::Data(
            "Certificate PDF workflow metadata does not match the configured workflow.".into(),
        ));
    }
    let configured_ids = config
        .steps
        .iter()
        .map(|step| step.id.as_str())
        .collect::<HashSet<_>>();
    let mut supplied_ids = HashSet::new();
    for step in snapshot.steps {
        if !configured_ids.contains(step.id.as_str()) {
            return Err(AppError::Data(format!(
                "Certificate PDF contains an unknown workflow step: {}",
                step.id
            )));
        }
        if !supplied_ids.insert(step.id.as_str()) {
            return Err(AppError::Data(format!(
                "Certificate PDF contains a duplicate workflow step: {}",
                step.id
            )));
        }
        match step.status {
            StepStatus::Pass => {}
            StepStatus::NotApplicable => {
                if step
                    .na_reason
                    .as_deref()
                    .is_none_or(|reason| reason.trim().is_empty())
                {
                    return Err(AppError::Data(format!(
                        "Certificate PDF workflow step has no N/A reason: {}",
                        step.id
                    )));
                }
            }
            _ => {
                return Err(AppError::Validation(format!(
                    "Certificate PDF workflow step is not complete: {} ({})",
                    step.id,
                    step_status(&step.status)
                )));
            }
        }
    }
    if supplied_ids.len() != configured_ids.len() {
        return Err(AppError::Data(
            "Certificate PDF workflow snapshot is incomplete.".into(),
        ));
    }
    if snapshot
        .deviations
        .iter()
        .any(|deviation| deviation.blocking && !deviation.resolved)
    {
        return Err(AppError::Validation(
            "Certificate PDF snapshot contains an open blocking deviation.".into(),
        ));
    }
    validate_rendered_text(snapshot, &config)?;
    Ok(config)
}

fn validate_sha256(label: &str, digest: &str) -> Result<()> {
    if digest.len() != 64 || !digest.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(AppError::Data(format!(
            "Certificate PDF has an invalid SHA-256 for {label}."
        )));
    }
    Ok(())
}

fn validate_rendered_text(
    snapshot: &CertificatePdfSnapshot<'_>,
    config: &workflow::WorkflowConfig,
) -> Result<()> {
    let fields = snapshot.track.fields.normalized_conditionals();
    for (label, value) in [
        ("track title", fields.title.as_str()),
        ("artist", snapshot.profile.artist_name.as_str()),
        ("Suno profile", snapshot.profile.suno_profile_name.as_str()),
        ("Suno handle", snapshot.profile.suno_handle.as_str()),
        (
            "Suno subscription start",
            snapshot.profile.subscription_start_date.as_str(),
        ),
        ("production start", fields.production_start_date.as_str()),
        ("production end", fields.production_end_date.as_str()),
        ("final export date", fields.final_export_date.as_str()),
        ("Suno model", fields.suno_model.as_str()),
        ("Suno project URL", fields.suno_project_url.as_str()),
        (
            "Suno plan at creation",
            fields.suno_plan_at_creation.as_str(),
        ),
        ("lyrics source", fields.lyrics_source.as_str()),
        ("Suno style prompt", fields.suno_style_prompt.as_str()),
        (
            "external audio source",
            fields.external_audio_source.as_str(),
        ),
        (
            "external audio provenance statement",
            fields.external_audio_ownership.as_str(),
        ),
        ("own audio source", fields.own_audio_source.as_str()),
        (
            "own audio provenance statement",
            fields.own_audio_ownership.as_str(),
        ),
        (
            "third-party sample source",
            fields.third_party_sample_source.as_str(),
        ),
        (
            "third-party sample provenance statement",
            fields.third_party_sample_ownership.as_str(),
        ),
        (
            "human editing details",
            fields.human_editing_details.as_str(),
        ),
        (
            "post-export editing details",
            fields.post_export_editing_details.as_str(),
        ),
        ("artwork origin", fields.artwork_origin.as_str()),
        ("AI image service", fields.ai_image_service.as_str()),
        (
            "code-audio post-processing note",
            fields.code_audio_post_processing_note.as_str(),
        ),
        (
            "human artwork process notes",
            fields.human_artwork_process_notes.as_str(),
        ),
        (
            "custom artwork change",
            fields.custom_artwork_change.as_str(),
        ),
        ("disclosure text", fields.disclosure_text.as_str()),
        ("workflow ID", snapshot.track.workflow_id.as_str()),
        ("workflow version", snapshot.track.workflow_version.as_str()),
        ("certificate ID", snapshot.certificate_id),
        ("finalization timestamp", snapshot.finalized_at),
        ("certificate version", snapshot.certificate_version),
    ] {
        validate_win_ansi(label, value)?;
    }

    for (label, values) in [
        (
            "code-audio post-processing operation",
            fields.code_audio_post_processing_operations.as_slice(),
        ),
        (
            "human artwork process operation",
            fields.human_artwork_process_operations.as_slice(),
        ),
        (
            "human artwork modification",
            fields.human_artwork_modifications.as_slice(),
        ),
    ] {
        for value in values {
            validate_win_ansi(label, value)?;
        }
    }

    for step in snapshot.steps {
        if let Some(reason) = step.na_reason.as_deref() {
            validate_win_ansi("workflow N/A reason", reason)?;
        }
    }
    for step in &config.steps {
        validate_win_ansi("workflow step label", &step.name)?;
    }
    for item in snapshot.evidence {
        validate_win_ansi("evidence relative path", &item.relative_path)?;
        validate_win_ansi("evidence imported timestamp", &item.imported_at)?;
        for (label, value) in [
            ("evidence coverage start", item.coverage_start.as_deref()),
            ("evidence coverage end", item.coverage_end.as_deref()),
            (
                "source global evidence ID",
                item.source_global_evidence_id.as_deref(),
            ),
            (
                "derived evidence ID",
                item.derived_from_evidence_id.as_deref(),
            ),
            (
                "evidence generator version",
                item.generator_version.as_deref(),
            ),
        ] {
            if let Some(value) = value {
                validate_win_ansi(label, value)?;
            }
        }
    }
    Ok(())
}

fn validate_win_ansi(label: &str, value: &str) -> Result<()> {
    if let Some(character) = value.chars().find(|character| !is_win_ansi(*character)) {
        return Err(AppError::Data(format!(
            "Certificate PDF {label} contains a character unsupported by the built-in PDF fonts: U+{:04X}.",
            character as u32
        )));
    }
    Ok(())
}

fn is_win_ansi(character: char) -> bool {
    if character == '\n' {
        return true;
    }
    match character as u32 {
        0x20..=0x7e | 0xa0..=0xff => true,
        _ => matches!(
            character,
            '\u{20ac}'
                | '\u{201a}'
                | '\u{0192}'
                | '\u{201e}'
                | '\u{2026}'
                | '\u{2020}'
                | '\u{2021}'
                | '\u{02c6}'
                | '\u{2030}'
                | '\u{0160}'
                | '\u{2039}'
                | '\u{0152}'
                | '\u{017d}'
                | '\u{2018}'
                | '\u{2019}'
                | '\u{201c}'
                | '\u{201d}'
                | '\u{2022}'
                | '\u{2013}'
                | '\u{2014}'
                | '\u{02dc}'
                | '\u{2122}'
                | '\u{0161}'
                | '\u{203a}'
                | '\u{0153}'
                | '\u{017e}'
                | '\u{0178}'
        ),
    }
}

fn render_document_title(layout: &mut PdfLayout) {
    layout.write_wrapped(
        DOCUMENT_TITLE,
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        14.0,
        BuiltinFont::HelveticaBold,
        1.28,
    );
    layout.write_wrapped(
        "Finalisierter technischer Snapshot",
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.5,
        BuiltinFont::Helvetica,
        1.2,
    );
    layout.y_mm -= 1.0;
    layout.rule(LEFT_MM, RIGHT_MM, layout.y_mm, 0.6);
    layout.y_mm -= 3.0;
}

fn render_header_metadata(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("Kopfmetadaten");
    let rows = vec![
        TableRow::plain("Track", documented(&snapshot.track.fields.title)),
        TableRow::plain("Artist", documented(&snapshot.profile.artist_name)),
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::mono("Finalization timestamp", snapshot.finalized_at),
        TableRow::plain("Documentation status", "DOCUMENTATION COMPLETE"),
        TableRow::mono("Application version", env!("CARGO_PKG_VERSION")),
        TableRow::mono("Workflow ID", &snapshot.track.workflow_id),
        TableRow::mono("Workflow version", &snapshot.track.workflow_version),
        TableRow::mono("Certificate version", snapshot.certificate_version),
    ];
    layout.table_rows(&rows, 45.0);
}

fn render_track_data(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("Track- und Suno-Daten");
    let fields = &snapshot.track.fields;
    let rows = vec![
        TableRow::plain("Track title", documented(&fields.title)),
        TableRow::plain("Artist", documented(&snapshot.profile.artist_name)),
        TableRow::plain(
            "Production start",
            documented(&fields.production_start_date),
        ),
        TableRow::plain("Production end", documented(&fields.production_end_date)),
        TableRow::plain("Final export date", documented(&fields.final_export_date)),
        TableRow::plain(
            "Commercial use intended",
            yes_no(Some(fields.commercial_use_intended)),
        ),
        TableRow::plain(
            "Suno profile",
            documented(&snapshot.profile.suno_profile_name),
        ),
        TableRow::mono("Suno handle", documented(&snapshot.profile.suno_handle)),
        TableRow::plain("Suno model", documented(&fields.suno_model)),
        TableRow::plain(
            "Suno plan at creation",
            documented(&fields.suno_plan_at_creation),
        ),
        TableRow::plain(
            "Suno subscription start",
            documented(&snapshot.profile.subscription_start_date),
        ),
        TableRow::mono("Suno project URL", documented(&fields.suno_project_url)),
    ];
    layout.table_rows(&rows, 45.0);
}

fn render_sources_and_generation(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("Quellen und Erzeugung");
    let fields = snapshot.track.fields.normalized_conditionals();
    let mut rows = vec![
        TableRow::plain(
            "External audio uploaded",
            yes_no(fields.external_audio_uploaded),
        ),
        TableRow::plain("Own audio uploaded", yes_no(fields.own_audio_uploaded)),
        TableRow::plain(
            "Third-party samples",
            yes_no(fields.third_party_samples_uploaded),
        ),
        TableRow::plain(
            "Code-based generation",
            yes_no(fields.code_based_generation),
        ),
        TableRow::plain("Lyrics source", documented(&fields.lyrics_source)),
        TableRow::plain("Human editing", yes_no(fields.human_editing_performed)),
        TableRow::plain(
            "Post-export editing",
            yes_no(fields.post_export_editing_performed),
        ),
    ];

    if fields.code_based_generation == Some(true) {
        rows.push(TableRow::plain(
            "Code-audio post-processing",
            yes_no(fields.code_audio_post_processed),
        ));
        if fields.code_audio_post_processed == Some(true) {
            push_documented_detail(
                &mut rows,
                "Code-audio post-processing operations",
                &fields.code_audio_post_processing_operations.join(", "),
            );
            push_documented_detail(
                &mut rows,
                "Other code-audio post-processing",
                &fields.code_audio_post_processing_note,
            );
        }
    }

    if fields.external_audio_uploaded == Some(true) {
        push_documented_detail(
            &mut rows,
            "External audio source",
            &fields.external_audio_source,
        );
        push_documented_detail(
            &mut rows,
            "External audio provenance statement",
            &fields.external_audio_ownership,
        );
    }
    if fields.own_audio_uploaded == Some(true) {
        push_documented_detail(&mut rows, "Own audio source", &fields.own_audio_source);
        push_documented_detail(
            &mut rows,
            "Own audio provenance statement",
            &fields.own_audio_ownership,
        );
    }
    if fields.third_party_samples_uploaded == Some(true) {
        push_documented_detail(
            &mut rows,
            "Third-party sample source",
            &fields.third_party_sample_source,
        );
        push_documented_detail(
            &mut rows,
            "Third-party sample provenance statement",
            &fields.third_party_sample_ownership,
        );
    }
    if fields.human_editing_performed == Some(true) {
        push_documented_detail(
            &mut rows,
            "Confirmed human editing details",
            &fields.human_editing_details,
        );
    }
    if fields.post_export_editing_performed == Some(true) {
        push_documented_detail(
            &mut rows,
            "Confirmed post-export editing details",
            &fields.post_export_editing_details,
        );
    }
    push_documented_detail(&mut rows, "Suno style prompt", &fields.suno_style_prompt);
    push_documented_detail(&mut rows, "Artwork origin", &fields.artwork_origin);
    push_documented_detail(&mut rows, "AI image service", &fields.ai_image_service);
    if fields.artwork_origin == "human" {
        push_documented_detail(
            &mut rows,
            "Human artwork process operations",
            &fields.human_artwork_process_operations.join(", "),
        );
        push_documented_detail(
            &mut rows,
            "Human artwork process notes",
            &fields.human_artwork_process_notes,
        );
    }
    if fields.artwork_origin == "ai_assisted" {
        push_documented_detail(
            &mut rows,
            "Human artwork modifications",
            &fields.human_artwork_modifications.join(", "),
        );
        push_documented_detail(
            &mut rows,
            "Other human artwork modification",
            &fields.custom_artwork_change,
        );
    }
    if let Some(disclosure_applied) = fields.disclosure_applied {
        rows.push(TableRow::plain(
            "Disclosure applied",
            yes_no(Some(disclosure_applied)),
        ));
        if disclosure_applied {
            push_documented_detail(&mut rows, "Disclosure text", &fields.disclosure_text);
        }
    }
    layout.table_rows(&rows, 49.0);
}

fn push_documented_detail(rows: &mut Vec<TableRow>, label: &str, value: &str) {
    if !value.trim().is_empty() {
        rows.push(TableRow::plain(label, value));
    }
}

fn render_workflow(layout: &mut PdfLayout, steps: &[StepState], labels: &HashMap<&str, &str>) {
    layout.section_title("Workflow-Kette");
    layout.column_heading("Schritt", "Autoritativer Status / N/A-Grund", 63.0);
    for step in steps {
        let mut value = step_status(&step.status).to_owned();
        if step.status == StepStatus::NotApplicable {
            value.push_str(" | N/A-Grund: ");
            value.push_str(
                step.na_reason
                    .as_deref()
                    .filter(|reason| !reason.trim().is_empty())
                    .unwrap_or("Not documented"),
            );
        }
        layout.table_row(
            &TableRow::plain(
                labels
                    .get(step.id.as_str())
                    .copied()
                    .expect("validated workflow step label"),
                value,
            ),
            63.0,
        );
    }
}

fn render_evidence_register(layout: &mut PdfLayout, evidence: &[&EvidenceItem]) {
    layout.section_title("Evidenzregister");
    render_evidence_column_heading(layout);
    for (index, item) in evidence.iter().enumerate() {
        let digest = item
            .sha256
            .as_deref()
            .expect("validated certificate PDF evidence digest");
        let minimum_height = 16.0
            + estimated_row_height(&item.relative_path, 144.0, 6.4, BuiltinFont::Courier)
            + estimated_row_height(digest, 144.0, 6.4, BuiltinFont::Courier);
        if !layout.fits(minimum_height) && minimum_height <= layout.full_content_height() {
            layout.new_page();
            layout.continuation_title("Evidenzregister (Fortsetzung)");
            render_evidence_column_heading(layout);
        }

        layout.evidence_summary_row(
            index + 1,
            item.role.as_str(),
            item.provenance.as_str(),
            item.size_bytes,
        );
        layout.table_row(&TableRow::mono("Relative path", &item.relative_path), 34.0);
        layout.table_row(&TableRow::mono("SHA-256", digest), 34.0);

        if !item.imported_at.trim().is_empty() {
            layout.table_row(&TableRow::mono("Imported at", &item.imported_at), 34.0);
        }
        if let Some(value) = nonempty(item.coverage_start.as_deref()) {
            layout.table_row(&TableRow::mono("Coverage start", value), 34.0);
        }
        if let Some(value) = nonempty(item.coverage_end.as_deref()) {
            layout.table_row(&TableRow::mono("Coverage end", value), 34.0);
        }
        if let Some(value) = nonempty(item.source_global_evidence_id.as_deref()) {
            layout.table_row(&TableRow::mono("Source global evidence ID", value), 45.0);
        }
        if let Some(value) = nonempty(item.derived_from_evidence_id.as_deref()) {
            layout.table_row(&TableRow::mono("Derived from evidence ID", value), 45.0);
        }
        if let Some(value) = nonempty(item.generator_version.as_deref()) {
            layout.table_row(&TableRow::mono("Generator version", value), 38.0);
        }
        layout.y_mm -= 1.8;
    }
}

fn render_evidence_column_heading(layout: &mut PdfLayout) {
    layout.ensure_space(6.0);
    let y = layout.y_mm - 2.5;
    layout.text_at(LEFT_MM + 1.0, y, "#", 6.5, BuiltinFont::HelveticaBold);
    layout.text_at(LEFT_MM + 12.0, y, "Role", 6.5, BuiltinFont::HelveticaBold);
    layout.text_at(
        LEFT_MM + 77.0,
        y,
        "Provenance",
        6.5,
        BuiltinFont::HelveticaBold,
    );
    layout.text_at(
        LEFT_MM + 130.0,
        y,
        "Size (bytes)",
        6.5,
        BuiltinFont::HelveticaBold,
    );
    layout.y_mm -= 4.0;
    layout.rule(LEFT_MM, RIGHT_MM, layout.y_mm, 0.45);
    layout.y_mm -= 1.0;
}

fn render_integrity_anchors(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("Integritätsanker");
    let release_wav =
        evidence_digest(snapshot.evidence, EvidenceRole::ReleaseWav).unwrap_or("Not documented");
    let final_artwork =
        evidence_digest(snapshot.evidence, EvidenceRole::FinalArtwork).unwrap_or("N/A");
    let open_blocking_deviations = snapshot
        .deviations
        .iter()
        .filter(|deviation| deviation.blocking && !deviation.resolved)
        .count();
    let rows = vec![
        TableRow::mono("Evidence file count", snapshot.evidence.len().to_string()),
        TableRow::mono("Release WAV SHA-256", release_wav),
        TableRow::mono("Final artwork SHA-256", final_artwork),
        TableRow::mono("SHA256SUMS.txt SHA-256", snapshot.sha256sums_sha256),
        TableRow::mono(
            "EVIDENCE_MANIFEST.json SHA-256",
            snapshot.evidence_manifest_sha256,
        ),
        TableRow::mono(
            "DOCUMENTATION_CERTIFICATE.md SHA-256",
            snapshot.markdown_certificate_sha256,
        ),
        TableRow::plain("Blocking deviations", open_blocking_deviations.to_string()),
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::mono("Finalization timestamp", snapshot.finalized_at),
        TableRow::plain("Final result", "DOCUMENTATION COMPLETE"),
    ];
    layout.table_rows(&rows, 54.0);
}

fn render_certificate_statement(layout: &mut PdfLayout, snapshot: &CertificatePdfSnapshot<'_>) {
    layout.section_title("Technische Zertifikatsaussage");
    layout.write_wrapped(
        CERTIFICATE_STATEMENT,
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        8.0,
        BuiltinFont::Helvetica,
        1.35,
    );
    layout.y_mm -= 2.0;
    let rows = vec![
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::plain("Generated by", "Suno Documentation Manager"),
        TableRow::mono("Application version", env!("CARGO_PKG_VERSION")),
        TableRow::mono(
            "Workflow",
            format!(
                "{} / {}",
                snapshot.track.workflow_id, snapshot.track.workflow_version
            ),
        ),
        TableRow::mono("Finalized at", snapshot.finalized_at),
    ];
    layout.table_rows(&rows, 42.0);
}

fn evidence_digest<'a>(evidence: &'a [&'a EvidenceItem], role: EvidenceRole) -> Option<&'a str> {
    evidence
        .iter()
        .find(|item| item.role == role)
        .and_then(|item| item.sha256.as_deref())
}

fn documented(value: &str) -> &str {
    if value.trim().is_empty() {
        "Not documented"
    } else {
        value
    }
}

fn nonempty(value: Option<&str>) -> Option<&str> {
    value.filter(|value| !value.trim().is_empty())
}

fn yes_no(value: Option<bool>) -> &'static str {
    match value {
        Some(true) => "Yes",
        Some(false) => "No",
        None => "Not documented",
    }
}

fn step_status(status: &StepStatus) -> &'static str {
    match status {
        StepStatus::NotRun => "NOT_RUN",
        StepStatus::Pass => "PASS",
        StepStatus::Fail => "FAIL",
        StepStatus::Blocked => "BLOCKED",
        StepStatus::NotApplicable => "N/A",
        StepStatus::NotVerified => "NOT_VERIFIED",
    }
}

struct TableRow {
    label: String,
    value: String,
    value_font: BuiltinFont,
    value_size_pt: f32,
}

impl TableRow {
    fn plain(label: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            value: value.into(),
            value_font: BuiltinFont::Helvetica,
            value_size_pt: 7.1,
        }
    }

    fn mono(label: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            value: value.into(),
            value_font: BuiltinFont::Courier,
            value_size_pt: 6.4,
        }
    }
}

struct PdfLayout {
    pages: Vec<Vec<Op>>,
    y_mm: f32,
}

impl PdfLayout {
    fn new() -> Self {
        Self {
            pages: vec![Vec::new()],
            y_mm: FIRST_PAGE_TOP_MM,
        }
    }

    fn current_ops(&mut self) -> &mut Vec<Op> {
        self.pages
            .last_mut()
            .expect("PDF layout always contains a page")
    }

    fn fits(&self, height_mm: f32) -> bool {
        self.y_mm - height_mm >= CONTENT_BOTTOM_MM
    }

    fn full_content_height(&self) -> f32 {
        CONTINUATION_TOP_MM - CONTENT_BOTTOM_MM
    }

    fn ensure_space(&mut self, height_mm: f32) {
        if !self.fits(height_mm) {
            self.new_page();
        }
    }

    fn new_page(&mut self) {
        self.pages.push(Vec::new());
        self.y_mm = CONTINUATION_TOP_MM;
        self.text_at(
            LEFT_MM,
            285.0,
            DOCUMENT_TITLE,
            6.8,
            BuiltinFont::HelveticaBold,
        );
        self.rule(LEFT_MM, RIGHT_MM, 281.5, 0.35);
    }

    fn continuation_title(&mut self, title: &str) {
        self.ensure_space(8.0);
        self.text_at(
            LEFT_MM,
            self.y_mm - 3.2,
            title,
            9.5,
            BuiltinFont::HelveticaBold,
        );
        self.y_mm -= 6.5;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.5);
        self.y_mm -= 1.5;
    }

    fn section_title(&mut self, title: &str) {
        self.ensure_space(13.0);
        self.y_mm -= 2.0;
        self.text_at(
            LEFT_MM,
            self.y_mm - 3.5,
            title,
            10.0,
            BuiltinFont::HelveticaBold,
        );
        self.y_mm -= 7.0;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.5);
        self.y_mm -= 1.5;
    }

    fn write_wrapped(
        &mut self,
        text: &str,
        x_mm: f32,
        width_mm: f32,
        size_pt: f32,
        font: BuiltinFont,
        line_factor: f32,
    ) {
        let lines = wrap_text(text, width_mm, size_pt, font);
        let line_height_mm = size_pt * 0.352_778 * line_factor;
        for line in lines {
            self.ensure_space(line_height_mm);
            let baseline = self.y_mm - size_pt * 0.352_778 * 0.82;
            self.text_at(x_mm, baseline, &line, size_pt, font);
            self.y_mm -= line_height_mm;
        }
    }

    fn table_rows(&mut self, rows: &[TableRow], label_width_mm: f32) {
        for row in rows {
            self.table_row(row, label_width_mm);
        }
    }

    fn table_row(&mut self, row: &TableRow, label_width_mm: f32) {
        let label_x = LEFT_MM + 1.0;
        let value_x = LEFT_MM + label_width_mm + 2.0;
        let value_width = RIGHT_MM - value_x - 1.0;
        let label_lines = wrap_text(
            &row.label,
            label_width_mm - 2.0,
            6.7,
            BuiltinFont::HelveticaBold,
        );
        let value_lines = wrap_text(&row.value, value_width, row.value_size_pt, row.value_font);
        let line_count = label_lines.len().max(value_lines.len()).max(1);
        let line_height_mm = 3.35;
        let total_height = line_count as f32 * line_height_mm + 2.0;
        if total_height <= self.full_content_height() && !self.fits(total_height) {
            self.new_page();
        }

        self.y_mm -= 0.8;
        for line_index in 0..line_count {
            let continued = if !self.fits(line_height_mm + 0.8) {
                self.new_page();
                self.text_at(
                    label_x,
                    self.y_mm - 2.45,
                    &format!("{} (Fortsetzung)", row.label),
                    6.7,
                    BuiltinFont::HelveticaBold,
                );
                true
            } else {
                false
            };
            let baseline = self.y_mm - 2.45;
            if !continued {
                if let Some(line) = label_lines.get(line_index) {
                    self.text_at(label_x, baseline, line, 6.7, BuiltinFont::HelveticaBold);
                }
            }
            if let Some(line) = value_lines.get(line_index) {
                self.text_at(value_x, baseline, line, row.value_size_pt, row.value_font);
            }
            self.y_mm -= line_height_mm;
        }
        self.y_mm -= 0.4;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.2);
        self.y_mm -= 0.8;
    }

    fn column_heading(&mut self, left: &str, right: &str, label_width_mm: f32) {
        self.ensure_space(6.0);
        let y = self.y_mm - 2.5;
        self.text_at(LEFT_MM + 1.0, y, left, 6.5, BuiltinFont::HelveticaBold);
        self.text_at(
            LEFT_MM + label_width_mm + 2.0,
            y,
            right,
            6.5,
            BuiltinFont::HelveticaBold,
        );
        self.y_mm -= 4.0;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.45);
        self.y_mm -= 1.0;
    }

    fn evidence_summary_row(
        &mut self,
        index: usize,
        role: &str,
        provenance: &str,
        size_bytes: u64,
    ) {
        self.ensure_space(6.0);
        let y = self.y_mm - 2.5;
        self.text_at(
            LEFT_MM + 1.0,
            y,
            &index.to_string(),
            6.4,
            BuiltinFont::CourierBold,
        );
        self.text_at(LEFT_MM + 12.0, y, role, 6.4, BuiltinFont::Courier);
        self.text_at(LEFT_MM + 77.0, y, provenance, 6.4, BuiltinFont::Courier);
        self.text_at(
            LEFT_MM + 130.0,
            y,
            &size_bytes.to_string(),
            6.4,
            BuiltinFont::Courier,
        );
        self.y_mm -= 4.0;
        self.rule(LEFT_MM, RIGHT_MM, self.y_mm, 0.25);
        self.y_mm -= 0.7;
    }

    fn text_at(&mut self, x_mm: f32, y_mm: f32, text: &str, size_pt: f32, font: BuiltinFont) {
        self.current_ops().extend([
            Op::StartTextSection,
            Op::SetTextCursor {
                pos: Point::new(Mm(x_mm), Mm(y_mm)),
            },
            Op::SetFont {
                font: PdfFontHandle::Builtin(font),
                size: Pt(size_pt),
            },
            Op::ShowText {
                items: vec![TextItem::Text(text.to_owned())],
            },
            Op::EndTextSection,
        ]);
    }

    fn rule(&mut self, from_x_mm: f32, to_x_mm: f32, y_mm: f32, thickness_pt: f32) {
        self.current_ops().extend([
            Op::SaveGraphicsState,
            Op::SetOutlineColor {
                col: Color::Rgb(Rgb {
                    r: 0.48,
                    g: 0.48,
                    b: 0.48,
                    icc_profile: None,
                }),
            },
            Op::SetOutlineThickness {
                pt: Pt(thickness_pt),
            },
            Op::DrawLine {
                line: Line {
                    points: vec![
                        LinePoint {
                            p: Point::new(Mm(from_x_mm), Mm(y_mm)),
                            bezier: false,
                        },
                        LinePoint {
                            p: Point::new(Mm(to_x_mm), Mm(y_mm)),
                            bezier: false,
                        },
                    ],
                    is_closed: false,
                },
            },
            Op::RestoreGraphicsState,
        ]);
    }

    fn into_pages(mut self) -> Vec<PdfPage> {
        let page_count = self.pages.len();
        for (index, ops) in self.pages.iter_mut().enumerate() {
            append_rule(ops, LEFT_MM, RIGHT_MM, FOOTER_RULE_Y_MM, 0.35);
            append_text(
                ops,
                LEFT_MM,
                FOOTER_TEXT_Y_MM,
                GENERATED_BY,
                6.5,
                BuiltinFont::Helvetica,
            );
            append_text(
                ops,
                166.0,
                FOOTER_TEXT_Y_MM,
                &format!("Seite {} / {}", index + 1, page_count),
                6.5,
                BuiltinFont::Helvetica,
            );
        }
        self.pages
            .into_iter()
            .map(|ops| PdfPage::new(Mm(PAGE_WIDTH_MM), Mm(PAGE_HEIGHT_MM), ops))
            .collect()
    }
}

fn append_text(
    ops: &mut Vec<Op>,
    x_mm: f32,
    y_mm: f32,
    text: &str,
    size_pt: f32,
    font: BuiltinFont,
) {
    ops.extend([
        Op::StartTextSection,
        Op::SetTextCursor {
            pos: Point::new(Mm(x_mm), Mm(y_mm)),
        },
        Op::SetFont {
            font: PdfFontHandle::Builtin(font),
            size: Pt(size_pt),
        },
        Op::ShowText {
            items: vec![TextItem::Text(text.to_owned())],
        },
        Op::EndTextSection,
    ]);
}

fn append_rule(ops: &mut Vec<Op>, from_x_mm: f32, to_x_mm: f32, y_mm: f32, thickness_pt: f32) {
    ops.extend([
        Op::SaveGraphicsState,
        Op::SetOutlineColor {
            col: Color::Rgb(Rgb {
                r: 0.48,
                g: 0.48,
                b: 0.48,
                icc_profile: None,
            }),
        },
        Op::SetOutlineThickness {
            pt: Pt(thickness_pt),
        },
        Op::DrawLine {
            line: Line {
                points: vec![
                    LinePoint {
                        p: Point::new(Mm(from_x_mm), Mm(y_mm)),
                        bezier: false,
                    },
                    LinePoint {
                        p: Point::new(Mm(to_x_mm), Mm(y_mm)),
                        bezier: false,
                    },
                ],
                is_closed: false,
            },
        },
        Op::RestoreGraphicsState,
    ]);
}

fn estimated_row_height(text: &str, width_mm: f32, size_pt: f32, font: BuiltinFont) -> f32 {
    wrap_text(text, width_mm, size_pt, font).len() as f32 * 3.35 + 2.0
}

fn wrap_text(text: &str, width_mm: f32, size_pt: f32, font: BuiltinFont) -> Vec<String> {
    let normalized = text
        .chars()
        .map(|character| match character {
            '\n' => '\n',
            '\t' => ' ',
            character if character.is_control() => ' ',
            character => character,
        })
        .collect::<String>();

    let mut result = Vec::new();
    for paragraph in normalized.split('\n') {
        let mut remaining = paragraph.chars().collect::<Vec<_>>();
        if remaining.is_empty() {
            result.push(String::new());
            continue;
        }
        while !remaining.is_empty() {
            let mut used_width_mm = 0.0;
            let mut maximum_fit = 0;
            let mut last_wrap_opportunity = None;
            for (index, character) in remaining.iter().copied().enumerate() {
                let character_width_mm =
                    measure_text_width_mm(&character.to_string(), size_pt, font);
                if maximum_fit > 0 && used_width_mm + character_width_mm > width_mm {
                    break;
                }
                used_width_mm += character_width_mm;
                maximum_fit = index + 1;
                if is_wrap_opportunity(character) {
                    last_wrap_opportunity = Some(maximum_fit);
                }
                if used_width_mm > width_mm {
                    break;
                }
            }
            if maximum_fit >= remaining.len() && used_width_mm <= width_mm {
                result.push(remaining.iter().collect());
                break;
            }
            let minimum_clean_break = maximum_fit / 2;
            let break_at = last_wrap_opportunity
                .filter(|index| *index >= minimum_clean_break)
                .unwrap_or(maximum_fit.max(1));
            result.push(remaining[..break_at].iter().collect());
            remaining.drain(..break_at);
        }
    }
    if result.is_empty() {
        result.push(String::new());
    }
    result
}

fn measure_text_width_mm(text: &str, size_pt: f32, font: BuiltinFont) -> f32 {
    let metrics = builtin_font_metrics(font);
    let units_per_em = f32::from(metrics.units_per_em.max(1));
    let width_in_em = text
        .chars()
        .map(|character| {
            metrics
                .lookup_glyph_index(character as u32)
                .and_then(|glyph| metrics.get_glyph_width(glyph))
                .map(f32::from)
                .unwrap_or(units_per_em)
                / units_per_em
        })
        .sum::<f32>();
    width_in_em * size_pt * 0.352_778
}

fn builtin_font_metrics(font: BuiltinFont) -> &'static ParsedFont {
    static HELVETICA: OnceLock<ParsedFont> = OnceLock::new();
    static HELVETICA_BOLD: OnceLock<ParsedFont> = OnceLock::new();
    static COURIER: OnceLock<ParsedFont> = OnceLock::new();
    static COURIER_BOLD: OnceLock<ParsedFont> = OnceLock::new();

    match font {
        BuiltinFont::Helvetica | BuiltinFont::HelveticaOblique => HELVETICA.get_or_init(|| {
            BuiltinFont::Helvetica
                .get_parsed_font()
                .expect("built-in Helvetica metrics")
        }),
        BuiltinFont::HelveticaBold | BuiltinFont::HelveticaBoldOblique => HELVETICA_BOLD
            .get_or_init(|| {
                BuiltinFont::HelveticaBold
                    .get_parsed_font()
                    .expect("built-in Helvetica Bold metrics")
            }),
        BuiltinFont::Courier | BuiltinFont::CourierOblique => COURIER.get_or_init(|| {
            BuiltinFont::Courier
                .get_parsed_font()
                .expect("built-in Courier metrics")
        }),
        BuiltinFont::CourierBold | BuiltinFont::CourierBoldOblique => {
            COURIER_BOLD.get_or_init(|| {
                BuiltinFont::CourierBold
                    .get_parsed_font()
                    .expect("built-in Courier Bold metrics")
            })
        }
        _ => HELVETICA.get_or_init(|| {
            BuiltinFont::Helvetica
                .get_parsed_font()
                .expect("built-in Helvetica metrics")
        }),
    }
}

fn is_wrap_opportunity(character: char) -> bool {
    character.is_whitespace() || matches!(character, '/' | '\\' | '-' | '_' | '.' | ':' | ';' | ',')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{
        CertificateState, DocumentState, EvidenceProvenance, IntegrityState, TrackFields,
        TrackLibraryPlacement, TrackStatus,
    };

    const CERTIFICATE_ID: &str = "SUNODM-CERT-2026-0001";
    const DIGEST_A: &str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    const DIGEST_B: &str = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    const DIGEST_C: &str = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";

    struct Fixture {
        track: TrackRecord,
        profile: Profile,
        steps: Vec<StepState>,
        evidence: Vec<EvidenceItem>,
        deviations: Vec<BlockingDeviation>,
    }

    impl Fixture {
        fn new(evidence_count: usize) -> Self {
            let profile = Profile {
                artist_name: "Künstlerin Änne Öster".into(),
                suno_profile_name: "Studio Überklang".into(),
                suno_handle: "@ueberklang".into(),
                suno_plan: "Pro".into(),
                subscription_start_date: "2025-01-01".into(),
                ..Profile::default()
            };
            let fields = TrackFields {
                title: "Größe & Präzision".into(),
                production_start_date: "2026-01-02".into(),
                production_end_date: "2026-01-03".into(),
                final_export_date: "2026-01-04".into(),
                suno_model: "v4.5".into(),
                suno_project_url: "https://suno.example/project/fixture".into(),
                suno_plan_at_creation: "Pro".into(),
                lyrics_source: "mixed".into(),
                external_audio_uploaded: Some(false),
                own_audio_uploaded: Some(false),
                code_based_generation: Some(true),
                third_party_samples_uploaded: Some(false),
                human_editing_performed: Some(true),
                human_editing_details: "Timing and cuts; EQ; Mixing".into(),
                post_export_editing_performed: Some(false),
                artwork_origin: "human".into(),
                ..TrackFields::default()
            };
            let track = TrackRecord {
                id: "track-fixture".into(),
                relative_path: ".".into(),
                status: TrackStatus::Ready,
                workflow_id: "suno-track".into(),
                workflow_version: "1.2".into(),
                profile_snapshot: profile.clone(),
                library: TrackLibraryPlacement::default(),
                fields,
                documents: DocumentState::default(),
                integrity: IntegrityState::default(),
                certificate: CertificateState::default(),
                created_at: "2026-01-02T00:00:00Z".into(),
                updated_at: "2026-01-04T00:00:00Z".into(),
                legacy: false,
            };
            let steps = workflow::config()
                .expect("workflow fixture")
                .steps
                .into_iter()
                .map(|step| StepState {
                    id: step.id.clone(),
                    status: if step.id == "ai_transparency" {
                        StepStatus::NotApplicable
                    } else {
                        StepStatus::Pass
                    },
                    na_reason: (step.id == "ai_transparency")
                        .then(|| "Kein AI-Artwork dokumentiert".into()),
                    updated_at: Some("2026-01-04T00:00:00Z".into()),
                })
                .collect();
            let evidence = (0..evidence_count).map(evidence_item).collect();
            Self {
                track,
                profile,
                steps,
                evidence,
                deviations: Vec::new(),
            }
        }

        fn generate(&self) -> Vec<u8> {
            self.generate_result()
                .expect("generate fixture certificate PDF")
        }

        fn generate_result(&self) -> Result<Vec<u8>> {
            let evidence_refs = self.evidence.iter().collect::<Vec<_>>();
            generate_pdf(&CertificatePdfSnapshot {
                track: &self.track,
                profile: &self.profile,
                steps: &self.steps,
                evidence: &evidence_refs,
                deviations: &self.deviations,
                certificate_id: CERTIFICATE_ID,
                finalized_at: "2026-01-04T12:34:56Z",
                certificate_version: "1",
                sha256sums_sha256: DIGEST_A,
                evidence_manifest_sha256: DIGEST_B,
                markdown_certificate_sha256: DIGEST_C,
            })
        }
    }

    fn evidence_item(index: usize) -> EvidenceItem {
        let role = match index % 3 {
            0 => EvidenceRole::ReleaseWav,
            1 => EvidenceRole::SourceCodeFile,
            _ => EvidenceRole::SunoScreenshot,
        };
        EvidenceItem {
            id: format!("evidence-{index:04}"),
            role,
            file_name: format!("evidence-{index:04}.dat"),
            relative_path: format!("02_SUNO/evidence-{index:04}.dat"),
            sha256: Some(format!("{value:064x}", value = index + 1)),
            size_bytes: 1_024 + index as u64,
            imported_at: "2026-01-04T10:00:00Z".into(),
            verified: true,
            verification_error: None,
            source_global_evidence_id: index
                .is_multiple_of(4)
                .then(|| format!("global-{index:04}")),
            coverage_start: index.is_multiple_of(5).then(|| "2026-01-01".into()),
            coverage_end: index.is_multiple_of(5).then(|| "2026-01-31".into()),
            provenance: if index.is_multiple_of(4) {
                EvidenceProvenance::GlobalCopy
            } else {
                EvidenceProvenance::ManagedCopy
            },
            derived_from_evidence_id: index
                .is_multiple_of(6)
                .then(|| format!("source-{index:04}")),
            generator_version: index.is_multiple_of(7).then(|| "generator-1.0".into()),
            generated_disclosure_text: None,
        }
    }

    fn parse_text(bytes: &[u8]) -> (PdfDocument, String) {
        let mut warnings = Vec::new();
        let document = PdfDocument::parse(bytes, &PdfParseOptions::default(), &mut warnings)
            .expect("parse generated certificate PDF");
        assert!(
            warnings
                .iter()
                .all(|warning| warning.severity != PdfParseErrorSeverity::Error),
            "parser errors: {warnings:?}"
        );
        let text = document
            .extract_text()
            .into_iter()
            .flatten()
            .collect::<Vec<_>>()
            .join("\n");
        (document, text)
    }

    #[test]
    fn generates_parseable_pdf_with_identity_full_hash_and_german_text() {
        let bytes = Fixture::new(1).generate();
        assert!(bytes.starts_with(b"%PDF-"));
        validate_pdf_bytes(&bytes).expect("valid generated bytes");

        let (document, text) = parse_text(&bytes);
        assert!(!document.pages.is_empty());
        assert!(text.contains("Größe & Präzision"));
        assert!(text.contains("Künstlerin Änne Öster"));
        assert!(text.contains(CERTIFICATE_ID));
        assert!(text.contains(DIGEST_A));
        assert!(text.contains(&format!("{value:064x}", value = 1)));
        assert!(text.contains("Kein AI-Artwork dokumentiert"));
    }

    #[test]
    fn renders_multiple_evidence_items_and_optional_manifest_fields() {
        let bytes = Fixture::new(4).generate();
        let (_, text) = parse_text(&bytes);
        assert!(text.contains("02_SUNO/evidence-0000.dat"));
        assert!(text.contains("02_SUNO/evidence-0001.dat"));
        assert!(text.contains("02_SUNO/evidence-0002.dat"));
        assert!(text.contains("release_wav"));
        assert!(text.contains("source_code_file"));
        assert!(text.contains("global-0000"));
        assert!(text.contains("generator-1.0"));
    }

    #[test]
    fn large_evidence_register_paginates() {
        let bytes = Fixture::new(80).generate();
        let (document, text) = parse_text(&bytes);
        assert!(document.pages.len() > 1);
        assert!(text.contains("02_SUNO/evidence-0079.dat"));
        assert!(text.contains(&format!("Seite {} / {}", 1, document.pages.len())));
        assert!(text.contains(&format!(
            "Seite {} / {}",
            document.pages.len(),
            document.pages.len()
        )));
    }

    #[test]
    fn long_evidence_paths_wrap_without_truncation() {
        let mut fixture = Fixture::new(1);
        let long_path = format!(
            "02_SUNO/{components}evidence.wav",
            components = "nested_component_".repeat(25)
        );
        fixture.evidence[0].relative_path = long_path.clone();
        let bytes = fixture.generate();
        let (_, text) = parse_text(&bytes);
        let compact_text = text
            .chars()
            .filter(|character| !character.is_whitespace())
            .collect::<String>();
        assert!(compact_text.contains(&long_path));
    }

    #[test]
    fn conditional_details_are_normalized_before_rendering() {
        let mut fixture = Fixture::new(1);
        fixture.track.fields.external_audio_uploaded = Some(false);
        fixture.track.fields.external_audio_source = "stale hidden source".into();
        fixture.track.fields.external_audio_ownership = "stale hidden statement".into();
        let bytes = fixture.generate();
        let (_, text) = parse_text(&bytes);
        assert!(!text.contains("stale hidden source"));
        assert!(!text.contains("stale hidden statement"));
    }

    #[test]
    fn rejects_non_win_ansi_snapshot_text_instead_of_replacing_it() {
        let mut fixture = Fixture::new(1);
        fixture.track.fields.title = "Tokyo 東京".into();
        let error = fixture
            .generate_result()
            .expect_err("unsupported built-in-font character");
        assert!(error.to_string().contains("U+6771"));
    }

    #[test]
    fn rejects_incomplete_statuses_and_open_blocking_deviations() {
        let mut fixture = Fixture::new(1);
        fixture.steps[0].status = StepStatus::Fail;
        assert!(fixture.generate_result().is_err());

        fixture.steps[0].status = StepStatus::Pass;
        fixture.deviations.push(BlockingDeviation {
            id: "deviation-1".into(),
            title: "Open blocker".into(),
            description: "Unresolved technical deviation".into(),
            blocking: true,
            resolved: false,
            created_at: "2026-01-04T00:00:00Z".into(),
            resolved_at: None,
        });
        assert!(fixture.generate_result().is_err());
    }

    #[test]
    fn wrapping_uses_builtin_font_metrics_for_wide_glyphs() {
        let width_mm = 24.0;
        let lines = wrap_text(&"W".repeat(100), width_mm, 8.0, BuiltinFont::HelveticaBold);
        assert!(lines.len() > 1);
        assert!(lines.iter().all(|line| {
            measure_text_width_mm(line, 8.0, BuiltinFont::HelveticaBold) <= width_mm + 0.001
        }));
        assert_eq!(lines.concat(), "W".repeat(100));
    }

    #[test]
    fn rejects_non_pdf_staged_bytes() {
        assert!(validate_pdf_bytes(b"not a PDF").is_err());
    }

    #[test]
    fn rejects_unsorted_or_unverified_evidence_without_reordering_or_filtering() {
        let mut fixture = Fixture::new(2);
        fixture.evidence.swap(0, 1);
        {
            let evidence_refs = fixture.evidence.iter().collect::<Vec<_>>();
            let snapshot = CertificatePdfSnapshot {
                track: &fixture.track,
                profile: &fixture.profile,
                steps: &fixture.steps,
                evidence: &evidence_refs,
                deviations: &fixture.deviations,
                certificate_id: CERTIFICATE_ID,
                finalized_at: "2026-01-04T12:34:56Z",
                certificate_version: "1",
                sha256sums_sha256: DIGEST_A,
                evidence_manifest_sha256: DIGEST_B,
                markdown_certificate_sha256: DIGEST_C,
            };
            assert!(generate_pdf(&snapshot).is_err());
        }

        fixture
            .evidence
            .sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
        fixture.evidence[0].verified = false;
        let evidence_refs = fixture.evidence.iter().collect::<Vec<_>>();
        let snapshot = CertificatePdfSnapshot {
            track: &fixture.track,
            profile: &fixture.profile,
            steps: &fixture.steps,
            evidence: &evidence_refs,
            deviations: &fixture.deviations,
            certificate_id: CERTIFICATE_ID,
            finalized_at: "2026-01-04T12:34:56Z",
            certificate_version: "1",
            sha256sums_sha256: DIGEST_A,
            evidence_manifest_sha256: DIGEST_B,
            markdown_certificate_sha256: DIGEST_C,
        };
        assert!(generate_pdf(&snapshot).is_err());
    }
}
