use super::*;

pub(super) fn render_evidence_column_heading(layout: &mut PdfLayout) {
    layout.ensure_space(6.0);
    let y = layout.y_mm - 2.5;
    layout.text_at(LEFT_MM + 1.0, y, "#", 6.5, BuiltinFont::HelveticaBold);
    let role = layout.label("Role");
    let provenance = layout.label("Provenance");
    let size = layout.label("Size (bytes)");
    layout.text_at(LEFT_MM + 12.0, y, &role, 6.5, BuiltinFont::HelveticaBold);
    layout.text_at(
        LEFT_MM + 77.0,
        y,
        &provenance,
        6.5,
        BuiltinFont::HelveticaBold,
    );
    layout.text_at(LEFT_MM + 130.0, y, &size, 6.5, BuiltinFont::HelveticaBold);
    layout.y_mm -= 4.0;
    layout.rule(LEFT_MM, RIGHT_MM, layout.y_mm, 0.45);
    layout.y_mm -= 1.0;
}

pub(super) fn render_integrity_anchors(
    layout: &mut PdfLayout,
    snapshot: &CertificatePdfSnapshot<'_>,
) {
    layout.section_title("K. Integrity anchors");
    let release_wav =
        evidence_digest(snapshot.evidence, EvidenceRole::ReleaseWav).unwrap_or("NOT DOCUMENTED");
    let final_artwork =
        evidence_digest(snapshot.evidence, EvidenceRole::FinalArtwork).unwrap_or("N/A");
    let open_blocking_deviations = snapshot
        .deviations
        .iter()
        .filter(|deviation| deviation.blocking && !deviation.resolved)
        .count();
    let revision_count_label = layout.label("Previous revision count [System verification]");
    layout.write_wrapped(
        &format!(
            "{revision_count_label}: {}",
            snapshot.revision_references.len()
        ),
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.2,
        BuiltinFont::HelveticaBold,
        1.3,
    );
    let rows = vec![
        TableRow::mono("Evidence file count", snapshot.evidence.len().to_string()),
        TableRow::mono("Release WAV SHA-256", release_wav),
        TableRow::mono("Final artwork SHA-256", final_artwork),
        TableRow::mono("SHA256SUMS.txt SHA-256", snapshot.sha256sums_sha256),
        TableRow::mono(
            "EVIDENCE_MANIFEST.json SHA-256",
            snapshot.evidence_manifest_sha256,
        ),
        TableRow::mono(
            "DOCUMENTATION_CERTIFICATE.md SHA-256",
            snapshot.markdown_certificate_sha256,
        ),
        TableRow::plain("Blocking deviations", open_blocking_deviations.to_string()),
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::mono("Finalization timestamp", snapshot.finalized_at),
        TableRow::system_mono(
            "Previous revision archives [System verification]",
            if snapshot.revision_references.is_empty() {
                "NONE RECORDED"
            } else {
                "Full numbered list in Technical Appendix"
            },
        ),
        TableRow::system_plain("Final result", "DOCUMENTATION COMPLETE"),
    ];
    layout.table_rows(&rows, 54.0);
}

pub(super) fn render_certificate_statement(
    layout: &mut PdfLayout,
    snapshot: &CertificatePdfSnapshot<'_>,
) {
    layout.section_title("L. Technical certificate statement");
    layout.write_localized(
        CERTIFICATE_STATEMENT,
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        8.0,
        BuiltinFont::Helvetica,
        1.35,
    );
    layout.y_mm -= 2.0;
    layout.write_localized(
        "Origin labels: User-confirmed fact / Evidence-derived metadata / System verification / System value.",
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.2,
        BuiltinFont::HelveticaBold,
        1.3,
    );
    layout.y_mm -= 1.0;
    let rows = vec![
        TableRow::mono("Certificate ID", snapshot.certificate_id),
        TableRow::plain("Generated by", "Suno Documentation Manager"),
        TableRow::mono("Application version", env!("CARGO_PKG_VERSION")),
        TableRow::mono(
            "Workflow",
            format!(
                "{} / {}",
                snapshot.track.workflow_id, snapshot.track.workflow_version
            ),
        ),
        TableRow::mono("Finalized at", snapshot.finalized_at),
    ];
    layout.table_rows(&rows, 42.0);
}

pub(super) fn render_technical_appendix(
    layout: &mut PdfLayout,
    snapshot: &CertificatePdfSnapshot<'_>,
) {
    layout.new_page();
    layout.section_title("Technical Appendix");
    layout.write_localized(
        "This appendix retains long technical records that are summarized in the preceding certificate sections.",
        LEFT_MM,
        RIGHT_MM - LEFT_MM,
        7.2,
        BuiltinFont::Helvetica,
        1.3,
    );
    let external = &snapshot.track.audio_screening.external;
    if !external.samples.is_empty() {
        layout.section_title("Appendix A — ACRCloud sample records");
        let response_description = layout.label(&response_archive_description(external));
        layout.table_rows(
            &[
                TableRow::plain("Provider response archive", response_description),
                TableRow::optional_mono(
                    "Response archive",
                    external.response_relative_path.as_deref(),
                    "NOT RECORDED",
                ),
                TableRow::optional_mono(
                    "Response SHA-256",
                    external.response_sha256.as_deref(),
                    "NOT RECORDED",
                ),
                TableRow::documented_mono("Source Evidence ID", &external.source_evidence_id),
                TableRow::documented_mono("Source SHA-256", &external.source_sha256),
            ],
            52.0,
        );
        render_acrcloud_sample_table(layout, external);
    }

    if !snapshot.revision_references.is_empty() {
        layout.section_title("Appendix B — Previous revision references");
        layout.write_wrapped(
            &format!(
                "{}: {}",
                layout.label("Previous revisions"),
                snapshot.revision_references.len()
            ),
            LEFT_MM,
            RIGHT_MM - LEFT_MM,
            7.2,
            BuiltinFont::HelveticaBold,
            1.3,
        );
        for (index, revision) in snapshot.revision_references.iter().enumerate() {
            layout.table_row(&TableRow::mono(format!("{:02}", index + 1), revision), 12.0);
        }
    }

    if external.samples.is_empty() && snapshot.revision_references.is_empty() {
        layout.write_localized(
            "No separate appendix records were required for this snapshot.",
            LEFT_MM,
            RIGHT_MM - LEFT_MM,
            7.2,
            BuiltinFont::Helvetica,
            1.3,
        );
    }
}

pub(super) fn render_acrcloud_sample_table(
    layout: &mut PdfLayout,
    external: &AudioScreeningExternalRecord,
) {
    let consolidated_archive = response_archive_is_consolidated(external);
    render_acrcloud_sample_heading(layout);
    for sample in &external.samples {
        let position = format!(
            "{}–{} ms\n{} – {}",
            sample.offset_milliseconds,
            sample.end_offset_milliseconds,
            precise_milliseconds(sample.offset_milliseconds),
            precise_milliseconds(sample.end_offset_milliseconds),
        );
        let duration = format!("{} ms", sample.duration_milliseconds);
        let result = layout.label(sample_result_label(sample.status));
        let provider = sample
            .provider_status_compact()
            .unwrap_or_else(|| "N/A".into());
        let cells = [
            (format!("{:02}", sample.sequence), 8.0, BuiltinFont::Courier),
            (position, 57.0, BuiltinFont::Courier),
            (duration, 26.0, BuiltinFont::Courier),
            (result, 31.0, BuiltinFont::HelveticaBold),
            (provider, 56.0, BuiltinFont::Helvetica),
        ];
        let wrapped = cells
            .iter()
            .map(|(text, width, font)| wrap_text(text, *width - 2.0, 5.5, *font))
            .collect::<Vec<_>>();
        let line_count = wrapped.iter().map(Vec::len).max().unwrap_or(1);
        let row_height = line_count as f32 * 3.2 + 2.2;
        if !layout.fits(row_height + 2.0) {
            layout.new_page();
            layout.continuation_title("Appendix A — ACRCloud sample records (continuation)");
            render_acrcloud_sample_heading(layout);
        }
        let starts = [
            LEFT_MM,
            LEFT_MM + 8.0,
            LEFT_MM + 65.0,
            LEFT_MM + 91.0,
            LEFT_MM + 122.0,
        ];
        layout.y_mm -= 0.8;
        for line_index in 0..line_count {
            let baseline = layout.y_mm - 2.3;
            for (cell_index, lines) in wrapped.iter().enumerate() {
                if let Some(line) = lines.get(line_index) {
                    layout.text_at(
                        starts[cell_index] + 1.0,
                        baseline,
                        line,
                        5.5,
                        cells[cell_index].2,
                    );
                }
            }
            layout.y_mm -= 3.2;
        }
        layout.rule(LEFT_MM, RIGHT_MM, layout.y_mm, 0.2);
        layout.y_mm -= 1.4;

        for (index, item) in sample.matches.iter().enumerate() {
            layout.table_row(
                &TableRow::plain(
                    format!(
                        "Sample {:02} Provider match {} [Provider-derived metadata]",
                        sample.sequence,
                        index + 1
                    ),
                    audio_screening_match_value(item),
                ),
                78.0,
            );
        }
        if !consolidated_archive {
            if let Some(path) = nonempty(sample.response_relative_path.as_deref()) {
                layout.table_row(
                    &TableRow::mono(
                        format!(
                            "Sample {:02} response archive [System verification]",
                            sample.sequence
                        ),
                        path,
                    ),
                    78.0,
                );
            }
            if let Some(digest) = nonempty(sample.response_sha256.as_deref()) {
                layout.table_row(
                    &TableRow::mono(
                        format!(
                            "Sample {:02} response SHA-256 [System verification]",
                            sample.sequence
                        ),
                        digest,
                    ),
                    78.0,
                );
            }
        }
    }
}

pub(super) fn response_archive_is_consolidated(external: &AudioScreeningExternalRecord) -> bool {
    if external.samples.len() < 2 {
        return false;
    }
    let Some(archive_path) = nonempty(external.response_relative_path.as_deref()) else {
        return false;
    };
    let Some(archive_digest) = nonempty(external.response_sha256.as_deref()) else {
        return false;
    };

    let mut referenced_samples = 0;
    for sample in &external.samples {
        match (
            nonempty(sample.response_relative_path.as_deref()),
            nonempty(sample.response_sha256.as_deref()),
        ) {
            (None, None) => {}
            (Some(path), Some(digest)) if path == archive_path && digest == archive_digest => {
                referenced_samples += 1;
            }
            // A partial, conflicting, or mixed per-sample reference cannot be
            // safely represented by suppressing the individual archive rows.
            _ => return false,
        }
    }
    referenced_samples == external.samples.len()
}

pub(super) fn response_archive_description(external: &AudioScreeningExternalRecord) -> String {
    if response_archive_is_consolidated(external) {
        return format!(
            "Consolidated response archive: {} ACRCloud sample responses",
            external.samples.len()
        );
    }

    let top_level = nonempty(external.response_relative_path.as_deref())
        .zip(nonempty(external.response_sha256.as_deref()));
    let references = external
        .samples
        .iter()
        .filter_map(|sample| {
            nonempty(sample.response_relative_path.as_deref())
                .zip(nonempty(sample.response_sha256.as_deref()))
        })
        .collect::<Vec<_>>();
    let unique_references = references.iter().copied().collect::<HashSet<_>>();
    let has_incomplete_reference = external.samples.iter().any(|sample| {
        nonempty(sample.response_relative_path.as_deref()).is_some()
            != nonempty(sample.response_sha256.as_deref()).is_some()
    });

    if external.samples.len() <= 1 {
        return if top_level.is_some() || !references.is_empty() {
            "Single ACRCloud response archive".into()
        } else {
            "No response archive recorded".into()
        };
    }
    if unique_references.len() > 1 {
        return "Multiple response archives retained in the sample records".into();
    }
    if references.len() == external.samples.len() {
        if let (Some(top_level), Some(sample_reference)) = (top_level, references.first().copied())
        {
            if top_level != sample_reference {
                return "Conflicting top-level and per-sample response archive references retained"
                    .into();
            }
        }
        return "Shared response archive referenced by all sample records".into();
    }
    if !references.is_empty() || has_incomplete_reference {
        return format!(
            "Partial consolidated response archive: {} of {} ACRCloud sample responses",
            references.len(),
            external.samples.len()
        );
    }
    if top_level.is_some() {
        return "Top-level response archive recorded; per-sample bindings not documented".into();
    }
    "No response archive recorded".into()
}

pub(super) fn render_acrcloud_sample_heading(layout: &mut PdfLayout) {
    layout.ensure_space(7.0);
    let labels = ["#", "Position", "Duration", "Result", "Provider"];
    let starts = [
        LEFT_MM,
        LEFT_MM + 8.0,
        LEFT_MM + 65.0,
        LEFT_MM + 91.0,
        LEFT_MM + 122.0,
    ];
    for (label, x) in labels.into_iter().zip(starts) {
        layout.text_at(
            x + 1.0,
            layout.y_mm - 2.5,
            &layout.label(label),
            5.7,
            BuiltinFont::HelveticaBold,
        );
    }
    layout.y_mm -= 4.2;
    layout.rule(LEFT_MM, RIGHT_MM, layout.y_mm, 0.45);
    layout.y_mm -= 1.0;
}

pub(super) fn precise_milliseconds(value: u64) -> String {
    let minutes = value / 60_000;
    let seconds = (value % 60_000) / 1_000;
    let milliseconds = value % 1_000;
    format!("{minutes:02}:{seconds:02}.{milliseconds:03}")
}

pub(super) fn evidence_digest<'a>(
    evidence: &'a [&'a EvidenceItem],
    role: EvidenceRole,
) -> Option<&'a str> {
    evidence
        .iter()
        .find(|item| item.role == role)
        .and_then(|item| item.sha256.as_deref())
}

pub(super) fn documented_list(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| value.trim())
        .filter(|value| !value.is_empty())
        .collect::<Vec<_>>();
    if values.is_empty() {
        "NOT DOCUMENTED".into()
    } else {
        values.join(" | ")
    }
}

pub(super) fn generation_text_field_used(fields: &TrackFields) -> &'static str {
    match fields.suno_content_classification {
        Some(SunoContentClassification::Empty) => "NO",
        Some(_) => "YES",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn content_classification(fields: &TrackFields) -> &'static str {
    match fields.suno_content_classification {
        Some(SunoContentClassification::StructureOnly) => "STRUCTURE_ONLY",
        Some(SunoContentClassification::VocalLyricsOnly) => "VOCAL_LYRICS_ONLY",
        Some(SunoContentClassification::Mixed) => "MIXED",
        Some(SunoContentClassification::Empty) => "EMPTY",
        Some(SunoContentClassification::Other) => "OTHER",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn generation_field_vocal_lyrics_present(fields: &TrackFields) -> &'static str {
    match fields.suno_content_classification {
        Some(SunoContentClassification::VocalLyricsOnly | SunoContentClassification::Mixed) => {
            "YES"
        }
        Some(SunoContentClassification::StructureOnly) => "NO",
        Some(SunoContentClassification::Empty) => "N/A",
        Some(SunoContentClassification::Other) => "NOT DOCUMENTED",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn suno_vocal_intent(fields: &TrackFields) -> &'static str {
    match fields.vocal_intent {
        Some(VocalIntent::Vocal) => "VOCAL",
        Some(VocalIntent::Instrumental) => "INSTRUMENTAL",
        Some(VocalIntent::Unspecified) => "UNSPECIFIED",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn final_audio_contains_vocals(fields: &TrackFields) -> &'static str {
    yes_no(fields.vocal_lyrics_present)
}

pub(super) fn structure_instructions_present(fields: &TrackFields) -> &'static str {
    match fields.suno_content_classification {
        Some(SunoContentClassification::StructureOnly | SunoContentClassification::Mixed) => "YES",
        Some(SunoContentClassification::VocalLyricsOnly) => "NO",
        Some(SunoContentClassification::Empty) => "N/A",
        Some(SunoContentClassification::Other) => "NOT DOCUMENTED",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn documentation_answer(value: Option<DocumentationAnswer>) -> &'static str {
    match value {
        Some(DocumentationAnswer::Yes) => "YES",
        Some(DocumentationAnswer::No) => "NO",
        Some(DocumentationAnswer::NotDocumented) | None => "NOT DOCUMENTED",
    }
}

pub(super) fn controlled_documentation_answer(
    controlling: Option<bool>,
    value: Option<DocumentationAnswer>,
) -> &'static str {
    match controlling {
        Some(true) => documentation_answer(value),
        Some(false) => "N/A",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn deepfake_indicator_summary(fields: &TrackFields) -> &'static str {
    if fields.generative_ai_used == Some(false) {
        return "N/A";
    }
    if fields.generative_ai_used != Some(true) {
        return "INCOMPLETE – generative AI use NOT DOCUMENTED";
    }
    let answers = [
        fields.real_person_voice_intentionally_imitated,
        fields.real_person_identity_intentionally_represented,
        fields.real_event_represented_as_authentic_recording,
        fields.real_location_institution_event_presented_as_authentic_ai_recording,
    ];
    if answers.contains(&Some(DocumentationAnswer::Yes)) {
        "Potential deepfake-related indicator recorded"
    } else if answers
        .iter()
        .all(|answer| *answer == Some(DocumentationAnswer::No))
    {
        "Documented deepfake-related indicators: none recorded"
    } else {
        "Deepfake-related indicator documentation: INCOMPLETE"
    }
}

pub(super) fn documented(value: &str) -> &str {
    if value.trim().is_empty() {
        "NOT DOCUMENTED"
    } else {
        value
    }
}

pub(super) fn fact_origin_label(origin: FactOrigin) -> &'static str {
    match origin {
        FactOrigin::UserConfirmedFact => "User-confirmed fact",
        FactOrigin::EvidenceDerivedMetadata => "Evidence-derived metadata",
        FactOrigin::NotDocumented => "NOT DOCUMENTED",
    }
}

pub(super) fn yes_no_bool(value: bool) -> &'static str {
    if value {
        "YES"
    } else {
        "NO"
    }
}

pub(super) fn evidence_original_file_name<'a>(
    evidence: &'a [&'a EvidenceItem],
    role: EvidenceRole,
) -> Option<&'a str> {
    evidence
        .iter()
        .find(|item| item.role == role)
        .map(|item| item.metadata.original_file_name.as_str())
        .filter(|value| !value.trim().is_empty())
}

pub(super) fn evidence_relative_path<'a>(
    evidence: &'a [&'a EvidenceItem],
    role: EvidenceRole,
) -> Option<&'a str> {
    evidence
        .iter()
        .find(|item| item.role == role)
        .map(|item| item.relative_path.as_str())
}

pub(super) fn artwork_answer(origin: &str, answer: Option<bool>) -> &'static str {
    if origin == "none" {
        "N/A"
    } else if origin.trim().is_empty() {
        "NOT DOCUMENTED"
    } else {
        yes_no(answer)
    }
}

pub(super) fn artwork_note_table_row(
    label: impl Into<String>,
    origin: &str,
    answer: Option<bool>,
    note: &str,
) -> TableRow {
    if origin == "none" {
        TableRow::system_plain(label, "N/A")
    } else if origin.trim().is_empty() {
        TableRow::system_plain(label, "NOT DOCUMENTED")
    } else {
        match answer {
            Some(true) => TableRow::documented_plain(label, note),
            Some(false) => TableRow::system_plain(label, "N/A"),
            None => TableRow::system_plain(label, "NOT DOCUMENTED"),
        }
    }
}

pub(super) fn branch_value(answer: Option<bool>, value: &str) -> &str {
    match answer {
        Some(true) => documented(value),
        Some(false) => "N/A",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn subscription_coverage(snapshot: &CertificatePdfSnapshot<'_>) -> &'static str {
    let evidence = snapshot
        .evidence
        .iter()
        .map(|item| (*item).clone())
        .collect::<Vec<_>>();
    coverage_status_label(workflow::subscription_generation_coverage(
        snapshot.track,
        &evidence,
    ))
}

pub(super) fn subscription_production_coverage(
    snapshot: &CertificatePdfSnapshot<'_>,
) -> &'static str {
    let evidence = snapshot
        .evidence
        .iter()
        .map(|item| (*item).clone())
        .collect::<Vec<_>>();
    coverage_status_label(workflow::subscription_production_coverage(
        snapshot.track,
        &evidence,
    ))
}

pub(super) fn coverage_status_label(status: workflow::CoverageStatus) -> &'static str {
    match status {
        workflow::CoverageStatus::Yes => "YES",
        workflow::CoverageStatus::No => "NO",
        workflow::CoverageStatus::NotVerified => "NOT VERIFIED",
    }
}

pub(super) fn nonempty(value: Option<&str>) -> Option<&str> {
    value.filter(|value| !value.trim().is_empty())
}

pub(super) fn yes_no(value: Option<bool>) -> &'static str {
    match value {
        Some(true) => "YES",
        Some(false) => "NO",
        None => "NOT DOCUMENTED",
    }
}

pub(super) fn step_status(status: &StepStatus) -> &'static str {
    match status {
        StepStatus::NotRun => "NOT_RUN",
        StepStatus::Pass => "PASS",
        StepStatus::Fail => "FAIL",
        StepStatus::Blocked => "BLOCKED",
        StepStatus::NotApplicable => "N/A",
        StepStatus::NotVerified => "NOT_VERIFIED",
    }
}
