use super::*;

pub(super) const DOCUMENT_TITLE: &str = "SunoDM – Technical Documentation and Evidence Certificate";
pub(super) const GENERATED_BY: &str = "Generated by Suno Documentation Manager";
pub(super) const CERTIFICATE_STATEMENT: &str = "This technical certificate confirms the recorded inputs, finalized snapshot, registered evidence, recorded provenance, SHA-256 values, and configured workflow checks. It does not confirm authorship, rights ownership, non-infringement, legality, license validity, judicial evidentiary weight, statutory compliance, or governmental certification.";
pub(super) const EXTERNAL_TIMESTAMP_DISCLAIMER: &str = "The application records technical timestamp evidence separately from provider qualification. It does not infer legal effect; a regulatory qualification is reported only when independently verified.";

pub(super) const PAGE_WIDTH_MM: f32 = 210.0;
pub(super) const PAGE_HEIGHT_MM: f32 = 297.0;
pub(super) const LEFT_MM: f32 = 16.0;
pub(super) const RIGHT_MM: f32 = 194.0;
pub(super) const FIRST_PAGE_TOP_MM: f32 = 282.0;
pub(super) const CONTINUATION_TOP_MM: f32 = 273.0;
pub(super) const CONTENT_BOTTOM_MM: f32 = 21.0;
pub(super) const FOOTER_RULE_Y_MM: f32 = 16.0;
pub(super) const FOOTER_TEXT_Y_MM: f32 = 10.5;
pub(super) const ARTWORK_PREVIEW_MAX_PIXELS: u32 = 640;
pub(super) const ARTWORK_PROCESS_PREVIEW_MAX_PIXELS: u32 = 384;
pub(super) const ARTWORK_SOURCE_MAX_DIMENSION: u32 = 16_384;
pub(super) const ARTWORK_SOURCE_MAX_ALLOCATION: u64 = 128 * 1024 * 1024;
pub(super) const ARTWORK_SOURCE_MAX_FILE_BYTES: u64 = 64 * 1024 * 1024;
pub(super) const PDF_STREAM_MAX_DECOMPRESSED_BYTES: usize = 32 * 1024 * 1024;
pub(super) const PDF_PAGE_CONTENT_MAX_DECOMPRESSED_BYTES: usize = 16 * 1024 * 1024;

pub(super) const PDFA_PART: &str = "2";
pub(super) const PDFA_CONFORMANCE: &str = "B";
pub(super) const ARCHIVE_SANS_REGULAR_ID: &str = "SANSRG";
pub(super) const ARCHIVE_SANS_BOLD_ID: &str = "SANSBD";
pub(super) const ARCHIVE_MONO_REGULAR_ID: &str = "MONORG";
pub(super) const ARCHIVE_MONO_BOLD_ID: &str = "MONOBD";
pub(super) const ARCHIVE_SANS_REGULAR_BYTES: &[u8] =
    include_bytes!("../../assets/fonts/DejaVuSans.ttf");
pub(super) const ARCHIVE_SANS_BOLD_BYTES: &[u8] =
    include_bytes!("../../assets/fonts/DejaVuSans-Bold.ttf");
pub(super) const ARCHIVE_MONO_REGULAR_BYTES: &[u8] =
    include_bytes!("../../assets/fonts/DejaVuSansMono.ttf");
pub(super) const ARCHIVE_MONO_BOLD_BYTES: &[u8] =
    include_bytes!("../../assets/fonts/DejaVuSansMono-Bold.ttf");

pub const CERTIFICATE_PDF_ARCHIVE_FORMAT: &str = "PDF/A-2b";
pub const CERTIFICATE_PDF_FONT_EMBEDDING: &str = "full";
pub const CERTIFICATE_PDF_EMBEDDED_FONTS: [&str; 4] = [
    "DejaVuSans",
    "DejaVuSans-Bold",
    "DejaVuSansMono",
    "DejaVuSansMono-Bold",
];
pub const CERTIFICATE_PDF_FONT_SHA256: [&str; 4] = [
    "7da195a74c55bef988d0d48f9508bd5d849425c1770dba5d7bfc6ce9ed848954",
    "e6476c1b80502924294eed40894c5b18e06c181444ca953e5334262df9c27724",
    "b4a6c3e4faab8773f4ff761d56451646409f29abedd68f05d38c2df667d3c582",
    "bce60f1b4421acd9ea51ba6623d7024ecbe6817a953e3654df62a5e6bdf8f769",
];
pub const CERTIFICATE_PDF_FONT_VERSION: &str = "DejaVu 2.37";
pub const CERTIFICATE_PDF_FONT_LICENSE: &str = "DejaVu Fonts License";
pub const CERTIFICATE_PDF_OUTPUT_INTENT: &str = "Coated FOGRA39 (ISO 12647-2:2004)";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CertificatePdfArchiveMetadata {
    pub archive_format: &'static str,
    pub font_embedding: &'static str,
    pub embedded_fonts: &'static [&'static str],
    pub embedded_font_sha256: &'static [&'static str],
    pub font_version: &'static str,
    pub font_license: &'static str,
    pub output_intent: &'static str,
}

pub const fn certificate_pdf_archive_metadata() -> CertificatePdfArchiveMetadata {
    CertificatePdfArchiveMetadata {
        archive_format: CERTIFICATE_PDF_ARCHIVE_FORMAT,
        font_embedding: CERTIFICATE_PDF_FONT_EMBEDDING,
        embedded_fonts: &CERTIFICATE_PDF_EMBEDDED_FONTS,
        embedded_font_sha256: &CERTIFICATE_PDF_FONT_SHA256,
        font_version: CERTIFICATE_PDF_FONT_VERSION,
        font_license: CERTIFICATE_PDF_FONT_LICENSE,
        output_intent: CERTIFICATE_PDF_OUTPUT_INTENT,
    }
}

/// The immutable, finalized data used to render a documentation certificate PDF.
///
/// `steps` is authoritative and is rendered in exactly the supplied order. `evidence` must be
/// the already filtered and `relative_path`-sorted slice used for the finalized evidence
/// manifest. The renderer validates those invariants but deliberately does not re-evaluate,
/// filter, or sort either slice.
pub struct CertificatePdfSnapshot<'a> {
    pub track: &'a TrackRecord,
    pub automation: &'a TrackAutomation,
    pub profile: &'a Profile,
    pub steps: &'a [StepState],
    pub evidence: &'a [&'a EvidenceItem],
    pub deviations: &'a [BlockingDeviation],
    pub revision_references: &'a [String],
    pub certificate_id: &'a str,
    pub finalized_at: &'a str,
    pub certificate_version: &'a str,
    pub sha256sums_sha256: &'a str,
    pub evidence_manifest_sha256: &'a str,
    pub markdown_certificate_sha256: &'a str,
    pub finalization_timestamp: FinalizationTimestampSnapshot,
    /// Derived, in-memory render assets. Their source evidence remains untouched
    /// and the renderer validates that every asset still names registered
    /// artwork evidence before using it.
    pub artwork_previews: &'a [CertificateArtworkPreview],
    pub render_options: CertificateRenderOptions,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum StatusTone {
    Success,
    Notice,
    Neutral,
    Error,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct OverviewFact {
    pub(super) label: &'static str,
    pub(super) value: String,
    pub(super) tone: StatusTone,
    pub(super) localize_value: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct OverviewGroup {
    pub(super) title: &'static str,
    pub(super) facts: Vec<OverviewFact>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct ProviderResponseSummary {
    pub(super) response: String,
    pub(super) api_version: String,
    pub(super) response_is_system: bool,
    pub(super) api_version_is_system: bool,
}

/// Normalized, language-independent presentation model shared by the German
/// and English summary/overview renderers. Technical detail sections continue
/// to consume the same immutable snapshot and never recompute a different data
/// source for either language.
pub(super) struct CertificateViewModel<'a> {
    pub(super) snapshot: &'a CertificatePdfSnapshot<'a>,
    pub(super) groups: Vec<OverviewGroup>,
    pub(super) final_artwork: Option<&'a EvidenceItem>,
    pub(super) final_artwork_preview: Option<&'a CertificateArtworkPreview>,
    pub(super) provider_response: ProviderResponseSummary,
    pub(super) open_blocking_deviations: usize,
    pub(super) workflow_pass_count: usize,
    pub(super) workflow_na_count: usize,
}

impl<'a> CertificateViewModel<'a> {
    pub(super) fn from_snapshot(snapshot: &'a CertificatePdfSnapshot<'a>) -> Self {
        let evidence_values = snapshot
            .evidence
            .iter()
            .map(|item| (*item).clone())
            .collect::<Vec<_>>();
        let production_coverage =
            workflow::subscription_production_coverage(snapshot.track, &evidence_values);
        let generation_coverage =
            workflow::subscription_generation_coverage(snapshot.track, &evidence_values);
        let external = &snapshot.track.audio_screening.external;
        let open_blocking_deviations = snapshot
            .deviations
            .iter()
            .filter(|deviation| deviation.blocking && !deviation.resolved)
            .count();
        let final_artwork = snapshot
            .evidence
            .iter()
            .copied()
            .find(|item| item.role == EvidenceRole::FinalArtwork);
        let final_artwork_preview = snapshot
            .artwork_previews
            .iter()
            .find(|preview| preview.role == EvidenceRole::FinalArtwork);
        let groups = build_overview_groups(
            snapshot,
            production_coverage,
            generation_coverage,
            open_blocking_deviations,
            final_artwork,
        );
        let workflow_pass_count = snapshot
            .steps
            .iter()
            .filter(|step| step.status == StepStatus::Pass)
            .count();
        let workflow_na_count = snapshot
            .steps
            .iter()
            .filter(|step| step.status == StepStatus::NotApplicable)
            .count();

        Self {
            snapshot,
            groups,
            final_artwork,
            final_artwork_preview,
            provider_response: consolidated_provider_response(external),
            open_blocking_deviations,
            workflow_pass_count,
            workflow_na_count,
        }
    }
}

fn build_overview_groups(
    snapshot: &CertificatePdfSnapshot<'_>,
    production_coverage: workflow::CoverageStatus,
    generation_coverage: workflow::CoverageStatus,
    open_blocking_deviations: usize,
    final_artwork: Option<&EvidenceItem>,
) -> Vec<OverviewGroup> {
    let fields = &snapshot.track.fields;
    let external = &snapshot.track.audio_screening.external;
    let local = &snapshot.track.audio_screening.local;
    let terms_exist = snapshot
        .evidence
        .iter()
        .any(|item| item.role == EvidenceRole::SunoTermsRights);
    let generative_ai_documented = fields.generative_ai_used.is_some();
    let disclosure = match fields.generative_ai_used {
        Some(false) => OverviewFact::neutral("Disclosure documented", "N/A"),
        Some(true) => match fields.audio_disclosure_applied {
            Some(DocumentationAnswer::Yes | DocumentationAnswer::No) => {
                OverviewFact::success("Disclosure documented", "DOCUMENTED")
            }
            Some(DocumentationAnswer::NotDocumented) | None => {
                OverviewFact::notice("Disclosure documented", "NOT DOCUMENTED")
            }
        },
        None => OverviewFact::notice("Disclosure documented", "NOT DOCUMENTED"),
    };

    vec![
        OverviewGroup {
            title: "TRACK",
            facts: vec![
                OverviewFact::documented_neutral(
                    "Final generation",
                    &fields.suno_final_generation_date,
                ),
                OverviewFact::documented_neutral("Suno model", &fields.suno_model),
                OverviewFact::documented_neutral("Suno plan", &fields.suno_plan_at_generation),
                OverviewFact::neutral_system(
                    "Commercial use intended",
                    yes_no(Some(fields.commercial_use_intended)),
                ),
            ],
        },
        OverviewGroup {
            title: "INTEGRITY",
            facts: vec![
                if snapshot.automation.release_identical_to_suno_export {
                    OverviewFact::success("Release = Suno final export", "SHA-256 MATCH")
                } else {
                    OverviewFact::error("Release = Suno final export", "SHA-256 MISMATCH")
                },
                OverviewFact::neutral("Evidence files", snapshot.evidence.len().to_string()),
                if open_blocking_deviations == 0 {
                    OverviewFact::success("Blocking deviations", "0")
                } else {
                    OverviewFact::error("Blocking deviations", open_blocking_deviations.to_string())
                },
            ],
        },
        OverviewGroup {
            title: "RIGHTS EVIDENCE",
            facts: vec![
                coverage_overview_fact("Production period covered", production_coverage),
                coverage_overview_fact("Final generation covered", generation_coverage),
                if terms_exist {
                    OverviewFact::success("Terms archived", "DOCUMENTED")
                } else {
                    OverviewFact::notice("Terms archived", "NOT DOCUMENTED")
                },
            ],
        },
        OverviewGroup {
            title: "AI TRANSPARENCY",
            facts: vec![
                if generative_ai_documented {
                    OverviewFact::success("Generative AI documented", "DOCUMENTED")
                } else {
                    OverviewFact::notice("Generative AI documented", "NOT DOCUMENTED")
                },
                disclosure,
                if final_artwork.is_some() {
                    OverviewFact::success("Artwork documented", "DOCUMENTED")
                } else {
                    OverviewFact::notice("Artwork documented", "NOT AVAILABLE")
                },
            ],
        },
        OverviewGroup {
            title: "AUDIO SCREENING",
            facts: vec![
                screening_overview_fact("Chromaprint", local.status),
                screening_overview_fact("ACRCloud", external.status),
                OverviewFact::neutral(
                    "Coverage",
                    format!("{:.2} %", external.track_coverage_percent),
                ),
                OverviewFact::neutral("Unique samples", external.unique_sample_count.to_string()),
            ],
        },
        finalization_timestamp_overview_group(&snapshot.finalization_timestamp),
    ]
}

pub(super) fn finalization_timestamp_overview_group(
    timestamp: &FinalizationTimestampSnapshot,
) -> OverviewGroup {
    let provider = if timestamp.provider.trim().is_empty() {
        "NOT DOCUMENTED"
    } else {
        timestamp.provider.as_str()
    };
    let configuration = match timestamp.provider_configuration_status {
        TimestampProviderConfigurationStatus::Ready => OverviewFact::success(
            "Provider configuration",
            provider_configuration_status_label(timestamp.provider_configuration_status),
        ),
        TimestampProviderConfigurationStatus::Disabled
        | TimestampProviderConfigurationStatus::NotConfigured => OverviewFact::notice(
            "Provider configuration",
            provider_configuration_status_label(timestamp.provider_configuration_status),
        ),
        _ => OverviewFact::error(
            "Provider configuration",
            provider_configuration_status_label(timestamp.provider_configuration_status),
        ),
    };
    let technical = match timestamp.technical_status {
        ExternalTimestampStatus::Verified => OverviewFact::success(
            "Technical status",
            provider_verification_status_label(timestamp.technical_status),
        ),
        ExternalTimestampStatus::VerificationFailed
        | ExternalTimestampStatus::AnchorMismatch
        | ExternalTimestampStatus::UnsupportedResponse => OverviewFact::error(
            "Technical status",
            provider_verification_status_label(timestamp.technical_status),
        ),
        _ => OverviewFact::notice(
            "Technical status",
            provider_verification_status_label(timestamp.technical_status),
        ),
    };
    let metadata = timestamp.provider_metadata.as_ref();
    let protocol = metadata
        .map(|value| value.protocol.as_str())
        .filter(|value| !value.trim().is_empty())
        .unwrap_or("NOT DOCUMENTED");
    let qualification = metadata
        .and_then(|value| value.qualification.as_ref())
        .map(|value| value.eidas_qualification_status)
        .unwrap_or(TimestampQualificationStatus::NotChecked);
    let qualification = if qualification == TimestampQualificationStatus::QualifiedServiceVerified {
        OverviewFact::success(
            "Provider qualification",
            "eIDAS QUALIFIED TRUST SERVICE – VERIFIED",
        )
    } else {
        OverviewFact::notice(
            "Provider qualification",
            qualification_status_label(qualification),
        )
    };

    OverviewGroup {
        title: "EXTERNAL TIMESTAMP",
        facts: vec![
            OverviewFact::neutral("Provider", provider),
            configuration,
            technical,
            OverviewFact::neutral("Protocol", protocol),
            qualification,
        ],
    }
}

impl OverviewFact {
    pub(super) fn success(label: &'static str, value: impl Into<String>) -> Self {
        Self {
            label,
            value: value.into(),
            tone: StatusTone::Success,
            localize_value: true,
        }
    }

    pub(super) fn notice(label: &'static str, value: impl Into<String>) -> Self {
        Self {
            label,
            value: value.into(),
            tone: StatusTone::Notice,
            localize_value: true,
        }
    }

    pub(super) fn neutral(label: &'static str, value: impl Into<String>) -> Self {
        Self {
            label,
            value: value.into(),
            tone: StatusTone::Neutral,
            localize_value: false,
        }
    }

    pub(super) fn neutral_system(label: &'static str, value: impl Into<String>) -> Self {
        Self {
            label,
            value: value.into(),
            tone: StatusTone::Neutral,
            localize_value: true,
        }
    }

    pub(super) fn documented_neutral(label: &'static str, value: &str) -> Self {
        if value.trim().is_empty() {
            Self::neutral_system(label, "NOT DOCUMENTED")
        } else {
            Self::neutral(label, value)
        }
    }

    pub(super) fn error(label: &'static str, value: impl Into<String>) -> Self {
        Self {
            label,
            value: value.into(),
            tone: StatusTone::Error,
            localize_value: true,
        }
    }
}

pub(super) fn coverage_overview_fact(
    label: &'static str,
    status: workflow::CoverageStatus,
) -> OverviewFact {
    match status {
        workflow::CoverageStatus::Yes => OverviewFact::success(label, "COMPLETE"),
        workflow::CoverageStatus::No => OverviewFact::error(label, "NOT COVERED"),
        workflow::CoverageStatus::NotVerified => OverviewFact::notice(label, "NOT VERIFIED"),
    }
}

pub(super) fn screening_overview_fact(
    label: &'static str,
    status: AudioScreeningStatus,
) -> OverviewFact {
    let value = audio_screening_status_label(status);
    match status {
        AudioScreeningStatus::FingerprintGenerated | AudioScreeningStatus::NoMatchDetected => {
            OverviewFact::success(label, value)
        }
        AudioScreeningStatus::MatchDetected => OverviewFact::notice(label, value),
        AudioScreeningStatus::NotRun | AudioScreeningStatus::SkippedNotConfigured => {
            OverviewFact::notice(label, value)
        }
        _ => OverviewFact::error(label, value),
    }
}

pub(super) fn consolidated_provider_response(
    external: &AudioScreeningExternalRecord,
) -> ProviderResponseSummary {
    let values = external
        .samples
        .iter()
        .map(|sample| {
            (
                sample.provider_status_code,
                nonempty(sample.provider_status_message.as_deref()),
                nonempty(sample.provider_api_version.as_deref()),
            )
        })
        .collect::<Vec<_>>();
    let Some(first) = values.first().copied() else {
        return ProviderResponseSummary {
            response: "N/A".into(),
            api_version: "N/A".into(),
            response_is_system: true,
            api_version_is_system: true,
        };
    };
    if values.iter().any(|value| *value != first) {
        return ProviderResponseSummary {
            response: "MULTIPLE — see Technical Appendix".into(),
            api_version: "MULTIPLE — see Technical Appendix".into(),
            response_is_system: true,
            api_version_is_system: true,
        };
    }
    let response = match (first.0, first.1) {
        (Some(code), Some(message)) => format!("{code} · {message}"),
        (Some(code), None) => code.to_string(),
        (None, Some(message)) => message.to_owned(),
        (None, None) => "N/A".into(),
    };
    ProviderResponseSummary {
        response,
        api_version: first.2.unwrap_or("N/A").to_owned(),
        response_is_system: first.0.is_none() && first.1.is_none(),
        api_version_is_system: first.2.is_none(),
    }
}
